vmware/terraform-provider-nsxt

README.md

Now that the provider has been released, there are a number of items in
the old README that are no longer relevant. This commit replaces the
README with one that has been template from the vSphere provider, and
should better reflect what one would need to do to use the provider or
develop it, including up to date installation and development
instructions, and a referral to the Terraform website for documentation.
CC @avoltmer. Fixes #1.

Update README to reflect provider release

---

nsxt/resource_nsxt_dhcp_relay_profile_test.go
nsxt/resource_nsxt_dhcp_relay_service_test.go
nsxt/resource_nsxt_firewall_section_test.go
nsxt/resource_nsxt_ip_set_test.go
nsxt/resource_nsxt_ns_group_test.go

There was a copy/paste bug in some unittests which caused the destruction
tests to be skipped.

Fix destruction test in unittests

---

nsxt/resource_nsxt_firewall_section.go
nsxt/resource_nsxt_logical_port.go
nsxt/resource_nsxt_logical_router_downlink_port.go
nsxt/resource_nsxt_logical_router_link_port_on_tier0.go
nsxt/resource_nsxt_logical_router_link_port_on_tier1.go
nsxt/resource_nsxt_logical_switch.go
nsxt/resource_nsxt_logical_tier1_router.go
nsxt/resource_nsxt_ns_group.go
nsxt/resource_nsxt_static_route.go
nsxt/utils.go

The schema set command can fail some times.
Adding the validation on the returned error helps debugging
the problem.

Check schema set err for complex types

---

nsxt/provider.go
nsxt/resource_nsxt_dhcp_relay_profile_test.go
nsxt/resource_nsxt_dhcp_relay_service_test.go
nsxt/resource_nsxt_firewall_section_test.go
nsxt/resource_nsxt_ip_block.go
nsxt/resource_nsxt_ip_block_subnet.go
nsxt/resource_nsxt_ip_block_subnet_test.go
nsxt/resource_nsxt_ip_block_test.go
nsxt/resource_nsxt_ip_pool.go
nsxt/resource_nsxt_ip_pool_test.go
nsxt/resource_nsxt_ip_set_test.go
nsxt/resource_nsxt_ns_group_test.go
nsxt/utils.go
nsxt/validators.go
tools/terragen.py
vendor/github.com/vmware/go-vmware-nsxt/api_client.go
vendor/github.com/vmware/go-vmware-nsxt/configuration.go
vendor/vendor.json
website/docs/r/ip_block.html.markdown
website/docs/r/ip_block_subnet.html.markdown
website/docs/r/ip_pool.html.markdown
website/nsxt.erb

Adding support for ip_pool and ip_block resources

Initial IPAM support

---

nsxt/provider.go
nsxt/resource_nsxt_logical_dhcp_port.go
nsxt/resource_nsxt_logical_dhcp_port_test.go
nsxt/resource_nsxt_logical_dhcp_server.go
nsxt/resource_nsxt_logical_dhcp_server_test.go
website/docs/r/logical_dhcp_port.html.markdown
website/nsxt.erb

This resource will create a logical port on a logical switch with
an attachment to a DHCP server.
In addition - Fixing and improving the logical dhcp server resource and tests.

Adding Logical DHCP port resource

---

nsxt/resource_nsxt_logical_dhcp_port.go

The NSX does not support it, so the comments should not stay.

Remove switching profiles comments from dhcp port resource

---

nsxt/resource_nsxt_icmp_type_ns_service_test.go

Some ICMP type/code combinations were removed from NSX support.
This commit adjust tests accordingly.

Adjust ICMP test to latest backend

---

nsxt/resource_nsxt_logical_switch.go

Cascade delete would delete all ports on logical switch.
Since we assume all configuration is created by terraform, terraform
should take care of all switch dependencies before deleting the switch.
Cascade delete would help to clean up dangling ports that result from
errors (for example, on vpshere provider side).

Adding cascade delete for LS

---

nsxt/lb_rule_utils.go
nsxt/lb_utils.go
website/docs/r/lb_http_forwarding_rule.html.markdown
website/docs/r/lb_http_monitor.html.markdown
website/docs/r/lb_http_request_rewrite_rule.html.markdown
website/docs/r/lb_http_response_rewrite_rule.html.markdown
website/docs/r/lb_https_monitor.html.markdown

HTTP_VERSION_2_0 is not supported in current platform, although
declared in spec. This option will be added here when backed by
platform.

Fix http version validation in LB resources

---

nsxt/provider.go
nsxt/resource_nsxt_algorithm_type_ns_service.go
nsxt/resource_nsxt_ether_type_ns_service.go
nsxt/resource_nsxt_icmp_type_ns_service.go
nsxt/resource_nsxt_igmp_type_ns_service.go
nsxt/resource_nsxt_ip_protocol_ns_service.go
nsxt/resource_nsxt_l4_port_set_ns_service.go
nsxt/resource_nsxt_ns_service_group.go
nsxt/resource_nsxt_ns_service_group_test.go
website/docs/r/ns_service_group.html.markdown
website/nsxt.erb

The Service group contains NS services of any type as its members.
Please Note - nested NS services groups is currently not supported
by the NSX backend, although the api exists.

Adding NS Service Group resource

---

vendor/github.com/vmware/go-vmware-nsxt/manager/icmp_type_ns_service.go
vendor/vendor.json

Due to bug in early versions of NSX, icmp_code can not be omitted
from request.

Fix icmp_code in icmp_type_ns_service resource

---

nsxt/resource_nsxt_icmp_type_ns_service_test.go

From next release, platform only supports subset on icmp type+code
combinations. Adjust acc tests to configure correct combinations.

Fix icmp ns service tests

---

vendor/github.com/vmware/go-vmware-nsxt/manager/icmp_type_ns_service.go
vendor/vendor.json

Icmp code needs to be omitted when configuring type-only services.
This fix may cause rejected request in early platform versions.

govendor update for icmp service

---

nsxt/resource_nsxt_lb_pool.go
nsxt/resource_nsxt_lb_pool_test.go
vendor/github.com/vmware/go-vmware-nsxt/loadbalancer/pool_member_group.go
vendor/vendor.json
website/docs/r/lb_pool.html.markdown

Introduce another attribute to specify whether to limit number of
addresses in pool.

Allow unspecified value for max size in LB pool

---

nsxt/provider.go
nsxt/provider_test.go
nsxt/resource_nsxt_algorithm_type_ns_service_test.go
vendor/github.com/vmware/go-vmware-nsxt/api_client.go
vendor/github.com/vmware/go-vmware-nsxt/configuration.go
vendor/vendor.json
website/docs/index.html.markdown

Setting remote_auth flag to true in provider will triger remote
authorization (Remote keyword in Authorization header). The default
for the flag is false.

Add remote_auth option for vIDM case

---

nsxt/provider.go
nsxt/resource_nsxt_logical_switch.go
nsxt/resource_nsxt_logical_switch_test.go
nsxt/resource_nsxt_vlan_logical_switch.go
nsxt/resource_nsxt_vlan_logical_switch_test.go
vendor/github.com/vmware/go-vmware-nsxt/manager/logical_switch.go
vendor/vendor.json
website/docs/r/logical_switch.html.markdown
website/docs/r/vlan_logical_switch.html.markdown
website/nsxt.erb

This way default/required attributes are easier to manage and
understand.
In addition, allow zero value for vlan.

Separate vlan logical switch to dedicated resource

---

nsxt/resource_nsxt_logical_tier1_router.go

Backend does not allow changing edge cluster with single update call,
we would need to disable firewall first, then dissassociate the cluster
and associate the new one. Until this is implemented, use ForceNew as
workaround.
This seems to trigger a mismatch bug on terraform apply, but the bug
goes away if we apply again. Will open the bug upstream.

Mark edge_cluster_id as ForceNew in T1 router

---

nsxt/resource_nsxt_lb_client_ssl_profile_test.go
nsxt/resource_nsxt_lb_cookie_persistence_profile_test.go
nsxt/resource_nsxt_lb_fast_tcp_application_profile_test.go
nsxt/resource_nsxt_lb_fast_udp_application_profile_test.go
nsxt/resource_nsxt_lb_http_application_profile_test.go
nsxt/resource_nsxt_lb_http_forwarding_rule_test.go
nsxt/resource_nsxt_lb_http_virtual_server_test.go
nsxt/resource_nsxt_lb_icmp_monitor_test.go
nsxt/resource_nsxt_lb_l4_monitor_test.go
nsxt/resource_nsxt_lb_l7_monitor_test.go
nsxt/resource_nsxt_lb_passive_monitor_test.go
nsxt/resource_nsxt_lb_pool_test.go
nsxt/resource_nsxt_lb_server_ssl_profile_test.go
nsxt/resource_nsxt_logical_router_centralized_service_port_test.go

LB and centralized port features are not fully supported pre 2.3.0

Skip certain tests for old platform

---

website/docs/r/lb_service.html.markdown

` at the end of line 45 after the } was breaking syntax highlighting and invalidated the example code.

Removed extra ` from line 45 after }

---

nsxt/resource_nsxt_firewall_section.go
nsxt/resource_nsxt_firewall_section_test.go
website/docs/r/firewall_section.html.markdown

Add insert_before attribute that would indicate fw section id that
should come immediately after added section.
This would only be possible during create operation. The user would
be responsible for consistent section order (if duplicates are present
in insert_before, resulting section order would depend on order of
execution)
Tests and docs to follow.

Add ability to control FW section

---

nsxt/resource_nsxt_firewall_section.go

Currently when updating a firewall rules internally they get
deleted and the new ones are created (causing their IDs to change).
This is not always a desired behaviour, as the NSX-T API itself
allows changing the rules in place.
This patch adds the current firewall section and rule ID to the
payload in order to allow preserving the IDs.

Pass IDs for the FW sections and rules for update

---

nsxt/resource_nsxt_firewall_section.go
website/docs/r/firewall_section.html.markdown

EdgeFirewall sections cannot currently be edited due to lack of support for LogicalRouter applied_to sections. In a similar way, it is not possible to create a rule within a edge firewall section that applies to only a LogicalRouterPort.
Both are within /firewall/sections and can be updated using same API as DFW rules so there should be no reason the provider can't be used for them.

Support for LogicalRouter FirewallSection and LogicalRouterPort Rule

---

nsxt/resource_nsxt_nat_rule.go

NSX returns 400 response code for NAT rule that can not be found,
instead of the conventional 404. This leads to provider erroring out,
while it should just detect resource absence. To work around this,
this change handles 400 response code as if it was 404.

Fix nat READ for non-existant rule

---

nsxt/resource_nsxt_vm_tags.go
nsxt/resource_nsxt_vm_tags_test.go
nsxt/utils.go
website/docs/r/vm_tags.html.markdown

When VM is created in vsphere provider, a logical port is created
automatically (not managed by terraform). This patch extends
nsxt_vm_tags resource to enable user to configure tags on this port
in addition to the ability to configure tags on the VM.

Enable logical port tags config for discovered VM

---

GNUmakefile

Acceptance tests need to be run in go module mode.

Switch go modules on in acc tests

---

nsxt/provider_test.go
nsxt/resource_nsxt_logical_router_downlink_port.go
nsxt/resource_nsxt_logical_router_downlink_port_test.go

In NSX 2.5, resource type for dhcp relay attachment on router
downlink port has changed.
This patch extends validation to allow new type, and fixes the test
to assign and validate resource type based on backend version.

Fix resource type for dhcp relay attachment

---

nsxt/provider.go
nsxt/resource_nsxt_logical_switch.go
website/docs/index.html.markdown

Before this change, when logical switch realization status was
partial success, provider failed configuration. This flag would
allow to treat partial success as valid state. Default setting for
this flag is false. Currently the flag only relates to logical
switch realization.

Add provider flag to tolerate partial success

---

nsxt/resource_nsxt_vm_tags.go
nsxt/resource_nsxt_vm_tags_test.go
nsxt/utils_test.go

In order to pass test with port tags, VM needs to reside on opaque
switch. In order not to fail existing test setups, dedicate another
env variable for test of tagging VM port.

Allocate another env variable for vm port test

---

nsxt/data_source_nsxt_ip_pool.go
nsxt/data_source_nsxt_ip_pool_test.go
nsxt/provider.go
nsxt/resource_nsxt_ip_pool_allocation_ip_address.go
nsxt/resource_nsxt_ip_pool_allocation_ip_address_test.go
nsxt/utils_test.go
website/docs/d/ip_pool.html.markdown
website/docs/r/ip_pool_allocation_ip_address.html.markdown
website/nsxt.erb

For allocating and releasing IP addresses from an IP pool, the resource `nsxt_ip_pool_allocation_ip_address` and the data source `nsxt_ip_pool` have been added.
Acceptance tests and documentation have also been added. For the data source and the allocation tests, an existing IP pool is needed. A new environmental variable `NSXT_TEST_IP_POOL` has been defined to specify it.

Add resource nsxt_ip_pool_allocation_ip_address

---

nsxt/resource_nsxt_ip_pool_allocation_ip_address.go

A bug was introduced with the reordering of the error handling during the review of PR #190

fix for "Error during IPPoolAllocationIPAddress delete: EOF"

---

nsxt/data_source_nsxt_certificate.go
nsxt/data_source_nsxt_edge_cluster.go
nsxt/data_source_nsxt_logical_tier0_router.go
nsxt/data_source_nsxt_logical_tier1_router.go
nsxt/data_source_nsxt_mac_pool.go
nsxt/data_source_nsxt_ns_group.go
nsxt/data_source_nsxt_ns_service.go
nsxt/data_source_nsxt_switching_profile.go
nsxt/data_source_nsxt_transport_zone.go

404 error handling was based on false assumtion that API call does
not return error in case of 404 response. This was fixed earlier for
resources, this change completes the fix for data sources.

Fix error handling in data sources

---

nsxt/resource_nsxt_ip_set.go
nsxt/resource_nsxt_ns_group.go

In addition, force deletion of IPSet resource, in order to allow
deletion even if this set is active member in group via membership
criteria.

Support IPSet type in ns group membership criteria

---

CHANGELOG.md
nsxt/resource_nsxt_ip_discovery_switching_profile.go
nsxt/resource_nsxt_ip_discovery_switching_profile_test.go
nsxt/resource_nsxt_mac_management_switching_profile.go
nsxt/resource_nsxt_mac_management_switching_profile_test.go
nsxt/resource_nsxt_qos_switching_profile.go
nsxt/resource_nsxt_qos_switching_profile_test.go
nsxt/resource_nsxt_spoofguard_switching_profile.go
nsxt/resource_nsxt_spoofguard_switching_profile_test.go
nsxt/resource_nsxt_switch_security_switching_profile.go
nsxt/resource_nsxt_switch_security_switching_profile_test.go

Revision was not conveyed to server in switching profiles update.
This caused the update to be rejected in some cases. This change
adds revision and tests for scenario that was failing.

Add revision in switching profile update

---

CHANGELOG.md
nsxt/resource_nsxt_logical_switch.go

This should allow deleting logical switch even if it still has
dependencies.
In future, we plan to add a provider flag that would control all "detach" and "force-delete" behaviors.

Detach logical switch before deleting it

---

nsxt/provider.go

Zero value causes provider to crash.

Require min retry delay in provider to be 10ms+

---

nsxt/data_source_nsxt_policy_vm_test.go

Add PreCheck conditions for TestAccDataSourceNsxtPolicyVM_basic to skip
the test if the NSXT_TEST_VM_ID and NSXT_TEST_VM_NAME env vars are not
set.

skip TestAccDataSourceNsxtPolicyVM_basic without env var

---

nsxt/resource_nsxt_policy_service.go

Use ConflictsWith to validate that ether type entry can not coexist with
other entry types unders the same service.

Improve policy service validation

---

nsxt/data_source_nsxt_policy_edge_cluster.go
nsxt/data_source_nsxt_policy_edge_node.go
nsxt/data_source_nsxt_policy_transport_zone.go
nsxt/data_source_nsxt_policy_transport_zone_test.go
nsxt/policy_common.go
nsxt/provider.go
nsxt/resource_nsxt_policy_vm_tags.go
website/docs/d/policy_transport_zone.html.markdown
website/docs/index.html.markdown

Some policy data sources make use of APIs based on enforcement points.
In VMC environment, enforcement point ID has non-default setting.
This change allows user to configure enforcement point on provider
level.
In addition, this change allows to pull default TZ per transport type
via nsxt_policy_transport_zone data source.

Expose enforcement point argument on provider

---

website/docs/r/policy_segment.html.markdown
website/docs/r/policy_vlan_segment.html.markdown

According to [this](https://github.com/terraform-providers/terraform-provider-nsxt/blob/master/nsxt/segment_common.go#L109), `dhcp_ranges` should be a list of strings.

Update doc for dhcp_ranges

---

nsxt/resource_nsxt_policy_ip_pool_block_subnet.go
nsxt/resource_nsxt_policy_ip_pool_block_subnet_test.go

Due to asyncronous IPAM implementation in NSXT Policy, deleting
block subnet doesn't guarantee subnet is actually freed. This can
cause issues like subsequent block deletion. To verify consistency,
this change implements waiting for delete realization.
Note: This workaround will not be needed for future platform
versions, where IPAM will be fully managed by NSXT Policy.

Policy block subnet - wait for delete realization

---

nsxt/resource_nsxt_vm_tags.go
website/docs/r/vm_tags.html.markdown

When VM is attached to multiple NSX switches, nsxt_vm_tags resource
needs to update logical port tags on all relevant logical ports.
We assume tags are fully managed by terraform and thus are the same
for all ports.

Apply logical_port_tags to all VM ports

---

nsxt/utils.go

In order to update tags to empty list, sdk expects empty slice,
rather then nil slice, to be passed to update tags call. This way
tags will not be omitted from API call.
This doesn't affect general resources, since update function
uses PUT Api which will wipe out tags if not passed.

Fix tag removal in vm tags resource

---

nsxt/policy_errors.go

With NSX 2.5, some API errors are badly formatted by nsx (error
format does not meet API spec). In this case, sdk conversion fails.
Message details are lost, but some information (such as error type)
should be presented for the user.

Improve error report when error conversion fails

---

nsxt/resource_nsxt_logical_switch.go

This change reapplies patch d6d6675a18410b3a0f51b1f91c23380c82ec38c1
that got lost in merge.

Re-apply detach fix for logical switch resource

---

nsxt/resource_nsxt_policy_tier0_gateway.go
nsxt/resource_nsxt_policy_tier0_gateway_test.go
website/docs/r/policy_group.html.markdown

This was failing due to revision check enforcement. This patch
removes revision check enforcement and changes default for
multipath_relax according to platform default.
In addition, it clarifies group memebership tag usage to match by
tag scope.

Fix creation of Tier0 with bgp config

---

nsxt/data_source_nsxt_policy_realization_info_test.go
nsxt/resource_nsxt_policy_tier0_gateway_interface.go
nsxt/resource_nsxt_policy_tier0_gateway_interface_test.go
nsxt/resource_nsxt_policy_tier0_gateway_test.go
nsxt/resource_nsxt_policy_tier1_gateway_interface_test.go

In Tier0 Interface, define segment_path as Optional, in order to
allow LOOPBACK interface with no segment.
In addition, new validation introduced by the platform requires
adjustments in acceptance tests.

Allow loopback T0 interface and fix VRF acc tests

---

nsxt/resource_nsxt_policy_nat_rule.go

Scope can be auto assigned by platform, hence needs to be computed.

Mark scope as Computed in policy_nat_rule resource

---

nsxt/policy_utils.go
nsxt/resource_nsxt_policy_vm_tags.go

Fix nsxt_policy_vm_tags resource to take enforcement point into
account. This fixes VMC use case.

Allow non-default enforcement point in policy vm

---

nsxt/resource_nsxt_policy_dhcp_server.go
nsxt/resource_nsxt_policy_segment_test.go
nsxt/resource_nsxt_policy_vlan_segment_test.go
nsxt/segment_common.go
website/docs/r/policy_dhcp_server.html.markdown
website/docs/r/policy_segment.html.markdown
website/docs/r/policy_vlan_segment.html.markdown

Platform now allows to specify server_address on subnet level.
Server addresses are no longer mandatory on server config level.

Add server_address in policy segment subnet dhcp

---

nsxt/data_source_nsxt_policy_gateway_qos_profile.go
nsxt/data_source_nsxt_policy_gateway_qos_profile_test.go
nsxt/provider.go
nsxt/resource_nsxt_policy_tier1_gateway.go
nsxt/resource_nsxt_policy_tier1_gateway_test.go
website/docs/d/policy_gateway_qos_profile.html.markdown
website/docs/r/policy_tier1_gateway.html.markdown
website/nsxt.erb

Expose pool_allocation, ingress_qos_profile_path,
egress_qos_profile_path attributes on nsxt_policy_tier1_gateway.
In addition, expose nsxt_policy_gateway_qos_profile data source.

Expose pool_allocation and qos settings on Tier1

---

nsxt/resource_nsxt_policy_vm_tags.go
nsxt/resource_nsxt_policy_vm_tags_test.go
nsxt/resource_nsxt_vm_tags.go
nsxt/utils.go

* Make tags required in policy resource, since its the only
attribute that can be set
* Avoid update backend call if there is no change in corresponding
configuration
* Avoid update backend call in delete function if there were no
tags to provider config

Optimize vm tag resources

---

nsxt/policy_utils.go

With policy global manager, policy path can start with global-infra.
We need to allow referencing global policy objects in policy paths.

Allow global-infra in policy path validation

---

nsxt/provider.go
website/docs/index.html.markdown
website/docs/r/policy_gateway_policy.html.markdown
website/docs/r/policy_group.html.markdown
website/docs/r/policy_security_policy.html.markdown

This reverts commit 07fb1d166c3540edd51ba3a6561d0a1144e79daf.
VMC was disabled before 2.0.0 release since the feature is not
officially supported. This change re-enables VMC support.

Re-enable VMC

---

nsxt/resource_nsxt_policy_group.go

This fixes the issue of loosing group criteria during import.

Fix policy group read function

---

nsxt/provider.go

Following SDK change that validates http security context to
contain auth type, we need to avoid setting http security context
when TLS client auth is responsible for authentication.

Fix client auth in policy resources

---

nsxt/provider.go
nsxt/utils.go

Since the provider pulls NSX version on init, this request can
serve as connectivity check. This solves permission issue for
users that did not have permission to read resource used for
connectivity check.
In addition, reduce default retry count to reasonable value.

Remove provider connectivity check

---

nsxt/policy_common.go
nsxt/resource_nsxt_policy_gateway_policy_test.go
nsxt/resource_nsxt_policy_security_policy_test.go
website/docs/r/policy_gateway_policy.html.markdown
website/docs/r/policy_security_policy.html.markdown

The optional argument "Tag" under rule as part of the nsxt_policy_security_policy resource does not configure the Tag on the rules.
In Policy the Tag of a rule is a string not a scope:tag like on other objects as ultimatelty this is a field propagated to the Syslog.

Add the correct type of security policy rule tag

---

nsxt/provider.go

This is needed for vIDM use case with NSX version < 3.0.0

Support remote auth for policy resources

---

nsxt/data_source_nsxt_policy_segment_realization.go
nsxt/data_source_nsxt_policy_segment_realization_test.go
website/docs/d/policy_segment_realization.html.markdown

This should make it more intuitive for users to define vsphere
network based on this attribute, in which case implicit dependency
will be created. With the dependency in place, vm resource will
wait until network is realized.

Expose network_name in segment realization data

---

nsxt/data_source_nsxt_policy_edge_cluster.go
nsxt/data_source_nsxt_policy_edge_node.go
nsxt/data_source_nsxt_policy_segment_realization.go
nsxt/data_source_nsxt_policy_transport_zone.go
nsxt/data_source_nsxt_policy_vm.go
nsxt/policy_utils.go
nsxt/provider.go
nsxt/resource_nsxt_logical_switch.go
nsxt/resource_nsxt_policy_vm_tags.go
nsxt/resource_nsxt_policy_vm_tags_test.go
nsxt/resource_nsxt_vlan_logical_switch.go

In order to enable multiple provider instances, we need to make
sure resources do not rely on global variables for provider
settings.

Provider aliasing support

---

nsxt/resource_nsxt_policy_service.go
nsxt/resource_nsxt_policy_tier0_gateway_interface_test.go

The error used to be swallowed.
In addition, fix few linter errors.

Fix policy segment delete error reporting

---

nsxt/policy_common.go
nsxt/resource_nsxt_policy_tier0_gateway.go
nsxt/resource_nsxt_policy_tier0_gateway_interface.go
website/docs/r/policy_tier0_gateway.html.markdown

Support multiple instances of locale services on tier0 resource
for global manager.
Tests will be added later, when edge cluster and edge node data
sources are supported on global manager.

Support locale_service clause on GM tier0

---

nsxt/resource_nsxt_policy_tier0_gateway.go
nsxt/resource_nsxt_policy_tier1_gateway.go
nsxt/resource_nsxt_policy_tier1_gateway_interface.go

It would be easier to introduce global manager support with H-API
since only one API call needs to be handled. H-API is more efficient
even regardless GM support.
In addition, fix revision check parameter in T0 Update.

Switch to H-API in policy T1 Gateway

---

nsxt/resource_nsxt_policy_lb_service_test.go
nsxt/resource_nsxt_policy_tier0_gateway.go
nsxt/resource_nsxt_policy_tier1_gateway.go

Terraform test does not respect gateway dependency on destroy.
To work around this problem, detach the gateways before destroying.
In addition, add printout on gateway delete to ease debugging (delete
using H-API seems to be slow)

Refactor LB service test to fix destroy issue

---

nsxt/data_source_nsxt_policy_edge_cluster.go
nsxt/gateway_common.go
nsxt/resource_nsxt_policy_lb_service_test.go
nsxt/resource_nsxt_policy_tier0_gateway.go
nsxt/resource_nsxt_policy_tier0_gateway_gm_test.go
nsxt/resource_nsxt_policy_tier0_gateway_test.go
nsxt/resource_nsxt_policy_tier1_gateway.go
nsxt/resource_nsxt_policy_tier1_gateway_gm_test.go
nsxt/resource_nsxt_policy_tier1_gateway_test.go
nsxt/utils_test.go

Fix some issues with gateway resources.
In addition, allow fetching edge cluster by site only.

Add GM-specific tests for gateways

---

nsxt/data_source_nsxt_policy_edge_cluster_test.go
nsxt/data_source_nsxt_policy_tier1_gateway_test.go
nsxt/data_source_nsxt_policy_transport_zone.go
nsxt/data_source_nsxt_policy_transport_zone_test.go
nsxt/resource_nsxt_policy_group_test.go
nsxt/resource_nsxt_policy_segment_test.go
nsxt/resource_nsxt_policy_vlan_segment_test.go
nsxt/utils_test.go

In addition, fix transport zone data source to respect is_default
attribute for global manager environment.

Adjust global manager tests to testing topology

---

nsxt/resource_nsxt_algorithm_type_ns_service_test.go
nsxt/resource_nsxt_ether_type_ns_service_test.go
nsxt/resource_nsxt_icmp_type_ns_service_test.go
nsxt/resource_nsxt_igmp_type_ns_service_test.go
nsxt/resource_nsxt_ip_protocol_ns_service_test.go
nsxt/resource_nsxt_ip_set_test.go
nsxt/resource_nsxt_l4_port_set_ns_service_test.go
nsxt/resource_nsxt_lb_http_forwarding_rule_test.go
nsxt/resource_nsxt_lb_http_request_rewrite_rule_test.go
nsxt/resource_nsxt_lb_http_response_rewrite_rule_test.go
nsxt/resource_nsxt_logical_switch_test.go
nsxt/resource_nsxt_ns_group_test.go
nsxt/resource_nsxt_policy_tier1_gateway_test.go
nsxt/resource_nsxt_vlan_logical_switch_test.go

In addition, remove a test that validates removal of edge cluster
from policy gateway. With edge cluster marked as computed, terraform will not detect edge cluster change to null, and thus edge cluster will not be removed unless another diff is detected.

Paralellize some of resource tests

---

nsxt/data_source_nsxt_policy_gateway_qos_profile_test.go
nsxt/data_source_nsxt_policy_qos_profile_test.go
nsxt/resource_nsxt_policy_service.go
nsxt/resource_nsxt_policy_tier0_gateway.go
nsxt/resource_nsxt_policy_tier1_gateway.go
nsxt/segment_common.go

In some blocks error definition was shadowed, which lead to
swallowing backend error.

Fix error handling in Global Manager section

---

nsxt/provider.go

Some client certificates may not work when assigning client cert via
Certificate field (https://github.com/golang/go/issues/23924).
This commit uses GetClientCertificate instead.

A better way to assign client auth for policy

---

nsxt/resource_nsxt_dhcp_relay_service_test.go
nsxt/resource_nsxt_ip_block_test.go
nsxt/resource_nsxt_ip_discovery_switching_profile_test.go
nsxt/resource_nsxt_mac_management_switching_profile_test.go
nsxt/resource_nsxt_ns_service_group_test.go
nsxt/resource_nsxt_policy_dhcp_relay_test.go
nsxt/resource_nsxt_policy_dhcp_server_test.go
nsxt/resource_nsxt_qos_switching_profile_test.go
nsxt/resource_nsxt_spoofguard_switching_profile_test.go
nsxt/resource_nsxt_static_route_test.go
nsxt/resource_nsxt_switch_security_switching_profile_test.go
nsxt/resource_nsxt_vm_tags_test.go

In addition, skip tests that are not supported for global manager
(these tests pass, but we rather not run them to save time)

Parallelize more acceptance tests

---

nsxt/resource_nsxt_policy_security_policy_test.go

GM Security Policy rules for non-default domain must include a group belonging to that domain in source and/or destination

Fix TestAccResourceNsxtGlobalPolicySecurityPolicy_withSite

---

nsxt/gateway_common.go
nsxt/policy_utils.go
nsxt/provider.go
nsxt/resource_nsxt_policy_bgp_config.go
nsxt/resource_nsxt_policy_bgp_config_test.go
nsxt/resource_nsxt_policy_tier0_gateway.go
nsxt/resource_nsxt_policy_tier1_gateway.go
website/docs/r/policy_bgp_config.html.markdown
website/docs/r/policy_tier0_gateway.html.markdown
website/nsxt.erb

In order to ease user experience while configuring bgp for Global
Manager, bgp config is exposed here as a separate resource, that
is defined by gateway path and site path.
Since BGP is auto-configured by NSX for each locale service, this
resource will de-facto perform only update operations.
For local manager, BGP config remains part of T0 gateway.

Expose T0 gbp config on GM as a resource

---

nsxt/policy_utils.go
nsxt/resource_nsxt_policy_vm_tags.go
nsxt/resource_nsxt_policy_vm_tags_test.go
nsxt/utils_test.go
website/docs/r/policy_vm_tags.html.markdown

In addition to tagging inventory VM on NSX, there is an ask to tag
ports that are auto-created for this VM. This change extends vm_tags
resource to specify port tags per segment.
Note that import is not supported for port tags.

Support tagging VM segment port

---

nsxt/gateway_common.go
nsxt/resource_nsxt_policy_tier0_gateway.go
nsxt/resource_nsxt_policy_tier1_gateway.go

This reverts commit d313896e79a1362366e176d1d9eba75a144a5a5e.
HA_vip support will require keeping the tier0 locale-service unchanged for tier0 / interfaces actions.

Revert "Avoid extra roundtrip for updating GW services" for HA_vip support

---

nsxt/policy_errors.go
nsxt/provider.go

As of today, provied cannot rely on vapi converter to return
conversion error in case target type does not match the actual
content. This change works around this issue and prints raw error
data whenever conversion is not succesful.
In addition, avoid erroring when VMC token decoder returns an error,
since for some error the token remains functional. Print a warning
instead.

Improve error handling for policy resources

---

nsxt/provider.go

This fix is only relevant for VMC

Fix data type to avoid warning on token decoding

---

nsxt/data_source_nsxt_policy_security_policy.go
nsxt/data_source_nsxt_policy_security_policy_test.go
nsxt/provider.go
website/docs/d/policy_gateway_policy.html.markdown
website/docs/d/policy_security_policy.html.markdown

This is mainly for convenience of retrieving default policy to use
in predefined security policy resource.
In addition, some fixes in docs for gateway policy data source.

Add policy security policy data sources

---

nsxt/data_source_nsxt_policy_gateway_policy.go
nsxt/data_source_nsxt_policy_security_policy.go

This parameter is not supported in earlier versions.

Remove include_rule_count param in policy list

---

nsxt/data_source_nsxt_policy_gateway_policy_test.go
nsxt/resource_nsxt_policy_predefined_gateway_policy_test.go

This test assumes NSX 3.1.0 gateway policy allocation (policy per
GW) and thus can run in parallel.

Refactor predefined GW policy test

---

nsxt/data_source_nsxt_policy_group_test.go

Tests that perform deletion by object name should use different
names to avoid collisions.

Prevent parallelizaton issue in group tests

---

nsxt/resource_nsxt_policy_segment.go
nsxt/resource_nsxt_policy_segment_test.go
nsxt/resource_nsxt_policy_vlan_segment.go
nsxt/segment_common.go
website/docs/r/policy_segment.html.markdown

This is to allow use case where VM tags packets and/or EVPN

Expose vlan_ids attribute for overlay segments

---

nsxt/data_source_nsxt_policy_realization_info.go

This parameter is not supported before NSX 3.0.0

Avoid using site_path parameter in realization ds

---

nsxt/policy_utils.go
nsxt/provider.go
nsxt/resource_nsxt_policy_ip_pool_block_subnet.go

Therefore we shouldn't use it in realization check unless necessary

site_path is not supported for NSX < 3.0.0

---

nsxt/resource_nsxt_policy_bgp_config_test.go
nsxt/resource_nsxt_policy_tier0_gateway.go
nsxt/resource_nsxt_policy_tier0_gateway_test.go
website/docs/r/policy_bgp_config.html.markdown
website/docs/r/policy_tier0_gateway.html.markdown
website/docs/r/policy_tier0_gateway_interface.html.markdown

* Mark inter_sr_ibgp and multipath_relax as computed for sake of
vrf gateways. Defer assigning defaults for these settings to NSX.
* Remove default local_as_num setting, since for VRF this setting
will be auto-assigned, and cause subsequent plan diff.
* Clarify VRF usage and add examples in documentation. In particular,
point out that explicit dependency needs to be created in VRF interface,
to avoid deletion issue.

Fix VRF configuration issues

---

nsxt/provider.go
nsxt/resource_nsxt_policy_lb_virtual_server.go

As opposed to FW objects, LB objects on NSX do not support partial
patch updates by default. This leads to LB virtual server deleting
existing rules on unrelated terraform config update. To fix this,
enable partial patch by adding corresponding header.

Do not modify policy LB VS rules on VS update

---

nsxt/resource_nsxt_policy_tier0_gateway_ha_vip_config.go

This is for sake of consistency with non-imported instances.

Assign UUID to ha vip resource upon import

---

nsxt/provider.go
nsxt/resource_nsxt_policy_lb_virtual_server.go

Original fix by using partial-patch header would fail to delete
tags on update.

Alternative fix for preserving LB VS rules

---

GNUmakefile
nsxt/data_source_nsxt_provider_info.go
nsxt/provider.go

This data source exposes commit and build date for the provider, in
order to ease testing effort. This data source is for internal use
and thus not documented.

Introduce provider_info data source

---

nsxt/resource_nsxt_policy_tier0_gateway.go
nsxt/resource_nsxt_policy_tier0_gateway_test.go
website/docs/r/policy_tier0_gateway.html.markdown

Support rd_admin_address in T0

Rd admin address

---

nsxt/resource_nsxt_policy_segment_test.go
nsxt/resource_nsxt_policy_vlan_segment_test.go
nsxt/segment_common.go
website/docs/r/policy_segment.html.markdown
website/docs/r/policy_vlan_segment.html.markdown

On Global Manager, transport zone can be different for each site,
and is auto-assigned on site level.
In future, when latest SDK is available, the provider may be
extended to specify segment TZ per site.

Make TZ optional in segment for sake of GM

---

nsxt/segment_common.go

Fro single subnet, user should not be able to configure both
dhcp_v4_config and dhcp_v6_config, since the subnet can be only
IPv4 or IPv6. Unfortunately ConflictsWith does not work here due
to nested structure.

Disallow both DHCP versions in single subnet

---

nsxt/resource_nsxt_policy_predefined_gateway_policy.go
website/docs/r/policy_predefined_gateway_policy.html.markdown

VMC auto-creates a rule under default policy. In order to provide best
experience for the user, we give an option to import this rule into
terraform state.
However, the user is not required to import the policy, if the
predefined rule is present in terraform config. This change also
expands the doc to cover both approaches.

Add importer for predefined gateway policy

---

nsxt/resource_nsxt_policy_tier0_gateway_test.go
nsxt/validators.go

This allows to configure /32 and /128 subnets for gateway interfaces.

Fix CIDR validation for max subnet prefix length

---

nsxt/resource_nsxt_logical_dhcp_server.go
nsxt/resource_nsxt_policy_segment_test.go

In dhcp option 121, platform allows to specify IP CIDR, we will
allow the same in provider.

Allow to specify IP cidr in dhcp option

---

nsxt/provider.go
nsxt/utils.go
vendor/github.com/vmware/vsphere-automation-sdk-go/services/nsxt/search/DefaultDslClient.go
vendor/github.com/vmware/vsphere-automation-sdk-go/services/nsxt/search/DefaultQueryClient.go
vendor/github.com/vmware/vsphere-automation-sdk-go/services/nsxt/search/DslClient.go
vendor/github.com/vmware/vsphere-automation-sdk-go/services/nsxt/search/DslTypes.go
vendor/github.com/vmware/vsphere-automation-sdk-go/services/nsxt/search/QueryClient.go
vendor/github.com/vmware/vsphere-automation-sdk-go/services/nsxt/search/QueryTypes.go
vendor/github.com/vmware/vsphere-automation-sdk-go/services/nsxt/search/SearchPackageTypes.go
vendor/modules.txt

This si required for version-dependant code paths.
In future, we need to find a way to either find out underlying
NSX version in VMC deployment, or maintain a mapping of VMC version
to NSX version.

Initialize VMC NSX version to 3.0.0

---

nsxt/provider.go
website/docs/index.html.markdown

Currently, the token is passed to the proxy using CSP header. This
wouldn't work for direct VMC connections. A new provider attribute
is offered here to switch to Bearer token authorization. Default
behavior does not change.

Allow Bearer token authorization in VMC

---

nsxt/data_source_nsxt_policy_bfd_profile_test.go
nsxt/data_source_nsxt_policy_dhcp_server_test.go
nsxt/resource_nsxt_policy_dhcp_v4_static_binding_test.go
nsxt/resource_nsxt_policy_dhcp_v6_static_binding_test.go
nsxt/resource_nsxt_policy_fixed_segment_test.go
nsxt/resource_nsxt_policy_intrusion_service_policy_test.go
nsxt/resource_nsxt_policy_tier0_gateway.go
nsxt/resource_nsxt_policy_tier0_gateway_test.go
website/docs/d/policy_bfd_profile.html.markdown
website/docs/r/policy_dhcp_v4_static_binding.html.markdown
website/docs/r/policy_dhcp_v6_static_binding.html.markdown
website/docs/r/policy_intrusion_service_policy.html.markdown
website/docs/r/policy_tier0_gateway.html.markdown
website/docs/r/policy_tier1_gateway.html.markdown

In addition, make sure tests pass for NSX < 3.0.0, and add
version info in docs.

Fix T0 gateway resource for old NSX version

---

nsxt/resource_nsxt_policy_gateway_dns_forwarder_test.go

This is to avoid IP collisions on NSX, due to tests running in
parallel.

Avoid using repeated IP in DNS forwarder tests

---

nsxt/resource_nsxt_policy_evpn_tenant_test.go
nsxt/resource_nsxt_policy_vm_tags.go

The platform does not populate pagination values as expected,
therefore extra logic is required to make sure full set of VMs
in presented to the data source.
In addition, fix unrelated linter issue.

Fix policy VM data source pagination issue

---

nsxt/gateway_common.go
nsxt/policy_utils.go
nsxt/resource_nsxt_policy_bgp_config.go
nsxt/resource_nsxt_policy_bgp_config_test.go
nsxt/resource_nsxt_policy_ospf_config.go
website/docs/r/policy_bgp_config.html.markdown

This resource should not be used together with bgp_config clause
in T0 gateway. A corresponding note was added to the doc.

Support bgp config resource for Local Manager

---

nsxt/resource_nsxt_policy_nat_rule.go

VMC environment does not accept empty string as source network

Fix source network ssignment in policy nat resource

---

website/docs/r/policy_gateway_policy.html.markdown
website/docs/r/policy_predefined_gateway_policy.html.markdown

Due to platform issue, assigning context profiles to gateway policy
only works from NSX 3.2 onwards.

Include a note in docs regarding context profiles

---

nsxt/provider.go

To allow basic authentication with VMC, this change is adding "Basic"
vmc_auth_mode option. With this mode, in spite of no vmc token defined,
provider will still detect VMC environment and avoid MP API for version
management.
The default for vmc_auth_mode is not changed here.

Allow basic auth mode for VMC PCI use case

---

nsxt/gateway_common.go

Make sure global-infra prefix is respected in profile type conditional.

Fix ipv6 profile assignment on Global Manager

---

nsxt/resource_nsxt_policy_tier0_gateway.go

VrfRouteTargets needs to be allocated only if targets are specified,
otherwise realization for VRF gateway may fail.

Dont assign VRF route targets unless specified

---

nsxt/policy_common.go
nsxt/resource_nsxt_policy_gateway_policy_test.go
nsxt/resource_nsxt_policy_security_policy_test.go
nsxt/validators.go
website/docs/r/policy_gateway_policy.html.markdown
website/docs/r/policy_predefined_gateway_policy.html.markdown
website/docs/r/policy_predefined_security_policy.html.markdown
website/docs/r/policy_security_policy.html.markdown

Adds a new validator specific to source and destination policy groups.
NSX-T can accept an IP, Range, CIDR, or a Group Path as a source
and/or destination group through the security policy interface.
Updates the getSecurityPolicyAndGatewayRulesSchema function to use the
new validator.
Resolves: Issue #584

Allow IP CIDR Range or Any as Source and/or Destination Policy Groups

---

nsxt/resource_nsxt_policy_tier0_gateway.go
website/docs/r/policy_tier0_gateway.html.markdown

In addition, clarify that deprecated redistribution config is not
set with import command.

Fix reading redistribution config for LM

---

nsxt/data_source_nsxt_policy_group_test.go
nsxt/data_source_nsxt_policy_realization_info_test.go
nsxt/data_source_nsxt_policy_site_test.go
nsxt/resource_nsxt_policy_domain_test.go
nsxt/resource_nsxt_policy_group_test.go
nsxt/resource_nsxt_policy_segment_test.go
nsxt/resource_nsxt_policy_tier0_gateway_gm_test.go
nsxt/resource_nsxt_policy_tier0_gateway_ha_vip_config_test.go
nsxt/resource_nsxt_policy_tier1_gateway_gm_test.go
nsxt/resource_nsxt_policy_vlan_segment_test.go

This will sligtly improve test running time

Make sure env vars are checked before provider init

---

nsxt/data_source_nsxt_policy_bfd_profile.go
nsxt/data_source_nsxt_policy_dhcp_server.go
nsxt/data_source_nsxt_policy_intrusion_service_profile.go
nsxt/policy_common.go

In standard policy data source, when ID is specified, no further
input is needed. To avoid confision, procider will error out if both
id and display_name are specified. This change is for new data sources
only in order not to break backwards compatibility.

For new data sources, disallow setting id and name

---

website/docs/r/policy_gateway_route_map.html.markdown

"community_list_match" and "prefix_list_matches" cannot be configured
together in the resource. If configured together, "prefix_list_matches"
will be ignored.

Document policy_gateway_route_map properly

---

nsxt/policy_search.go
nsxt/resource_nsxt_policy_gateway_dns_forwarder_test.go

When id is specified together with display_name in data source, it
should still return the object as expected.
With newer data sources, configuration of id with display_name is
rejected. This fix applies to older data sources.

Fix policy data source search to support name + id

---

nsxt/resource_nsxt_policy_fixed_segment_test.go
nsxt/segment_common.go

In fact, requiring TZ is causing issues with fixed segment import.
In addition, mark TZ as ForceNew in all segments, since updating is
not allowed on the platform.

TZ should not be required for fixed segments

---

.travis.yml
nsxt/resource_nsxt_policy_static_route.go
nsxt/resource_nsxt_policy_static_route_test.go
website/docs/r/policy_static_route.html.markdown

As platform allows this, the provider should follow suite.

Mark ip address as optional in static route

---

nsxt/resource_nsxt_policy_tier0_gateway_interface.go
website/docs/r/policy_tier0_gateway_interface.html.markdown

Enable_pim is not applicable for types other than "EXTERNAL", hence
adding more documentation for that.

Add Documentation for enable_pim in Tier0 GW Interface

---

nsxt/policy_common.go
nsxt/resource_nsxt_policy_gateway_route_map.go
website/docs/r/policy_gateway_route_map.html.markdown

Certain empty fields are accepted by policy API by fail on
realization. Set these only if specified.
In addition, fix documentation and linter suggestion.

Fix realization issue in gateway route map

---

README.md
nsxt/resource_nsxt_policy_gateway_redistribution_config.go
nsxt/resource_nsxt_policy_tier0_gateway_ha_vip_config.go
nsxt/resource_nsxt_policy_tier0_gateway_interface.go
nsxt/resource_nsxt_policy_tier1_gateway_interface.go

In some resources for Local Manager, default locale service id was
coded rather than actual locale service. This resulted in read errors
for environments with pre-created non-default locale service, especially
with imported resources.

Fix default locale service

---

nsxt/resource_nsxt_policy_nat_rule.go
nsxt/resource_nsxt_policy_nat_rule_test.go

This fixes non-empty diff in case platform reorders scopes

Fix nat rule scope to be Set instead of List

---

nsxt/data_source_nsxt_firewall_section.go
nsxt/data_source_nsxt_ip_pool.go
nsxt/data_source_nsxt_logical_tier0_router.go
nsxt/data_source_nsxt_logical_tier1_router.go
nsxt/data_source_nsxt_mac_pool.go
nsxt/data_source_nsxt_ns_group.go
nsxt/data_source_nsxt_ns_service.go
nsxt/data_source_nsxt_switching_profile.go
nsxt/utils.go

These data sources were limited to 1K objects, and recommendation is
to use policy counterparts. However some customers that can not yet
move to policy require support for MP data sources at scale.
The support was not added to fabric data sources that are not
expected to reach triple digit scale.

Support pagination in non-policy data sources

---

nsxt/resource_nsxt_policy_gateway_prefix_list.go
nsxt/segment_common.go

Some breaking changes were introduced in new release, including:
* always populating advanced config in segments
* changing default to lowercase in gateway route map
In order to avoid non-empty diff, segment resource would now rely
on terraform config in order to determine whether advanced settings
should be brought into state.

Adjust the provider for NSX 3.2 release

---

nsxt/data_source_nsxt_policy_lb_service.go
nsxt/data_source_nsxt_policy_lb_service_test.go
nsxt/provider.go
nsxt/utils_test.go
website/docs/d/policy_lb_service.html.markdown

This is my attempt to work on #618 which is marked as "good first issue". 
I've created the new data source which is pretty straight forward for this resource and added the appropriate basic tests as well. 
I ran the acceptance tests in the lab and they look fine (see below). I also used the development provider to run some actual terraform plan/apply's using the new resource and everything looks good so far. 
```
martin@ubuntu20:~/devel/terraform-provider-nsxt$ make testacc TESTARGS="-run=TestAccDataSourceNsxtPolicyLBService"
==> Checking that code complies with gofmt requirements...
GO111MODULE=on TF_ACC=1 go test $(go list ./... |grep -v 'vendor') -v -run=TestAccDataSourceNsxtPolicyLBService -timeout 360m
?   	github.com/vmware/terraform-provider-nsxt	[no test files]
=== RUN …
```

Add nsxt_policy_lb_service data source as per issue #618

---

nsxt/data_source_nsxt_policy_ip_discovery_profile_test.go
nsxt/data_source_nsxt_policy_mac_discovery_profile_test.go
nsxt/data_source_nsxt_policy_segment_security_profile_test.go
nsxt/data_source_nsxt_policy_spoofguard_profile_test.go
nsxt/resource_nsxt_policy_group.go

This is a temporary solution until sdk-based retry is introduced.
With NSX 3.2, platform async deletion problem manifests more
frequently with group dependency. This change retries group deletion
twice in case of invalid request error.
In addition, adjust tests to NSX 3.2 description change for profiles.

Retry group deletion

---

nsxt/resource_nsxt_policy_lb_virtual_server.go
nsxt/resource_nsxt_policy_lb_virtual_server_test.go
nsxt/utils.go
website/docs/r/policy_lb_virtual_server.html.markdown

The nsxt_policy_lb_virtual_server is still missing support for rules which my client could really use so I started working on this.
I modelled the interface along the lines of the manager resource nsxt_lb_http_request_rewrite_rule so you simply include one or more rule blocks and can add one or more action- and condition-types beneath it, for example:
```
resource "nsxt_policy_lb_virtual_server" "test" {
display_name             = "test"
application_profile_path = data.nsxt_policy_lb_app_profile.default_http.path
ip_address               = "1.1.1.1"
ports                    = [ "80" ]
pool_path                  = nsxt_policy_lb_pool.pool.path
rule {
display_name = "http_redirect_action_test"
http_redirect_action {
redirect_status = "301"
redirect_url = "dummy"
} …
```

Add rules to LB policy virtual server.

---

website/docs/r/policy_gateway_route_map.html.markdown

See https://vdc-download.vmware.com/vmwb-repository/dcr-public/ce4128ae-8334-4f91-871b-ecce254cf69e/488f1280-204c-441d-8520-8279ac33d54b/api_includes/types_CommunityMatchCriteria.html
Fix #704
Signed-off-by: Alexis La Goutte <alexis.lagoutte@gmail.com>

gateway_route_map(doc): fix missing MATCH to match_operator

---

nsxt/resource_nsxt_policy_vm_tags.go

Fix for issue #709. In such cases, provider should just swallow
the error, and print error messages.

Fix VM Not Found Issue in VM Tag

---

nsxt/resource_nsxt_policy_nat_rule.go
nsxt/resource_nsxt_policy_nat_rule_test.go
website/docs/r/policy_nat_rule.html.markdown

This requires support nat_type NAT64 in rule path.

Support NAT64 option in policy nat rule resource

---

nsxt/data_source_nsxt_policy_vm.go
nsxt/data_source_nsxt_policy_vms.go
nsxt/data_source_nsxt_policy_vms_test.go
nsxt/provider.go
nsxt/resource_nsxt_policy_vm_tags.go
website/docs/d/policy_vms.html.markdown

This data source returns full VM inventory mapped by display
name. It allows to control type of VM ID with `value_type` argument.
The purpose of this data source is to improve efficiency and also
provide user more flexibility in dealing with VM inventory without
necessarily failing apply (such as ignoring deleted VM).

Add data source for policy VMs map

---

nsxt/resource_nsxt_policy_group.go
nsxt/resource_nsxt_policy_group_test.go
website/docs/r/policy_group.html.markdown

This change adds external ids support for Group.

Add External IDs Support for Group

---

nsxt/policy_search.go

Certain special characters (such as brackets) are used in NSX ids.
Policy search requires the client to escape those characters.

Escape special charachers in policy ID search

---

nsxt/policy_search.go

When data source searches for objects, it needs to search for LM
or GM objects only. This change adds path verification to each
search - /infra for Local Manager and /global-infra for Global
Manager.

Include object scope into policy search

---

nsxt/resource_nsxt_policy_bgp_config.go
nsxt/resource_nsxt_policy_tier0_gateway.go
nsxt/resource_nsxt_policy_tier0_gateway_test.go

Since BGP on VRF gateway is mostly inherited from parent gateway,
recent NSX versions disallow configuring most of BGP settings on it.
Even resource defaults would cause BGP resource on VRF to error out.
This change fixes this issue, and in addition fixes potential
segmentation fault for BGP resource when locale service is not
present.

Fix bgp config for VRF gateway

---

nsxt/policy_utils.go
nsxt/resource_nsxt_policy_nat_rule.go
nsxt/resource_nsxt_policy_nat_rule_test.go

Fix some issues with NAT
(1) When creating REFLEXIVE Nat rules, the destination_network should be set to nil instead of empty string (issue #758)
(2) Allow translated_network field to be optional for no_snat/no_dnat (issue #753)

Fix some issues with NAT

---

nsxt/resource_nsxt_policy_bgp_config.go
nsxt/resource_nsxt_policy_tier0_gateway.go

Due to platform validations, AS number needs to remain nil
unless specified. In order to avoid non-empty diff when AS
is set by platform, we need to define this attribute as
computed.

Do not set AS number in BGP unless specified

---

nsxt/gateway_common.go
nsxt/resource_nsxt_policy_tier0_gateway.go
nsxt/resource_nsxt_policy_tier0_gateway_ha_vip_config_test.go
nsxt/resource_nsxt_policy_tier0_gateway_interface_test.go
nsxt/resource_nsxt_policy_tier1_gateway.go
nsxt/resource_nsxt_policy_tier1_gateway_interface_test.go
website/docs/r/policy_bgp_config.html.markdown
website/docs/r/policy_tier0_gateway.html.markdown
website/docs/r/policy_tier1_gateway.html.markdown

Today, locale service clause is only supported on Global Manager.
This change allows to configure it for Local Manager as well. This
configuration conflicts with edge_cluster_path and allows more
flexibility.
When importing Gateway, edge_cluster_path will be initialized rather
than locale_service, and additional apply is required to switch to
locale_service configuration.

Support locale_service Gateway clause for LM

---

website/docs/index.html.markdown

Global Manager realization times are slower, which reflects in
need for more retries, especially for resource recreate scenarios.
This recommendation is in documentation only.

Recommend to increase retry parameters for GM

---

nsxt/resource_nsxt_policy_fixed_segment_test.go
nsxt/resource_nsxt_policy_segment_test.go
nsxt/resource_nsxt_policy_vlan_segment_test.go
nsxt/segment_common.go

This attribute was added in NSX 3.0.0
In addition, remove cidr requirement for segment subnet, as
its no longer required on the platform.

Support replication mode in Segment resources

---

nsxt/resource_nsxt_policy_lb_virtual_server.go

We should perform change based on change in any rule, as
opposed to looking only at rule count.

Fix change detection in lb virtual server rules

---

nsxt/policy_common.go
nsxt/resource_nsxt_policy_gateway_policy.go
nsxt/resource_nsxt_policy_predefined_gateway_policy.go
nsxt/resource_nsxt_policy_predefined_security_policy.go
nsxt/resource_nsxt_policy_security_policy.go

In security policy and gateway policy resources, any change would trigger an update for the whole list of rules. This change switches to use H-API, and would update rules on individual basis, and rule will be updated only if terraform detects a change in it. This will prevent needless reset of statistics for untouched rules.
Please note that if a rule is deleted, terraform would detect a change in all subsequent rules, since rules are considered an ordered list. User can consider disabling rule as an alternative.

Update FW policy rules only if needed

---

nsxt/data_source_nsxt_policy_bridge_profile.go
nsxt/data_source_nsxt_policy_bridge_profile_test.go
nsxt/provider.go
nsxt/resource_nsxt_policy_segment_test.go
nsxt/segment_common.go
nsxt/utils_test.go
website/docs/d/policy_bridge_profile.html.markdown
website/docs/r/policy_segment.html.markdown
website/docs/r/policy_vlan_segment.html.markdown

Add policy_bridge_profile data source and bridge_config clause
on segments.

Support bridge confguration on segment

---

nsxt/data_source_nsxt_policy_gateway_policy_test.go
nsxt/policy_common.go

This test was only relevant for early NSX versions, and VPN configuration breaks the tests since one extra GW policy is added.

Remove test for default GW policy data source

---

nsxt/policy_common.go
nsxt/resource_nsxt_policy_predefined_gateway_policy.go
nsxt/resource_nsxt_policy_predefined_security_policy.go

nsx_id should only be configurable in predefined policy resources, and read-only in other resources.

Disallow setting nsx_id attribute in policy rules

---

nsxt/resource_nsxt_policy_gateway_route_map.go
nsxt/resource_nsxt_policy_gateway_route_map_test.go

Zero default values were incorrect for local_preference and med attributes. We leave those attributes to be determined by the platform unless the user set them explicitly.

Fix computed attributes in route map set clause

---

nsxt/gateway_common.go
nsxt/resource_nsxt_policy_tier0_gateway_gm_test.go
nsxt/resource_nsxt_policy_tier1_gateway_gm_test.go

In Gateway locale service definition, preferred_edge_paths attribute should be an ordered list rather than set.

Ensure ordered list when preferred edges are set

---

nsxt/resource_nsxt_policy_ip_discovery_profile.go
nsxt/resource_nsxt_policy_ip_discovery_profile_test.go
website/docs/r/policy_ip_discovery_profile.html.markdown

nsxt_policy_ip_discovery_profile was missing the tufo_enabled attribute (trust on first use).
Fixes: #833
Signed-off-by: Kobi Samoray <ksamoray@vmware.com>

Add tofu_enabled attr to ip_discovery_profile

---

.github/workflows/website-lint.yml
nsxt/data_source_nsxt_policy_ipsec_vpn_local_endpoint.go
nsxt/data_source_nsxt_policy_ipsec_vpn_local_endpoint_test.go
nsxt/data_source_nsxt_policy_ipsec_vpn_service.go
nsxt/data_source_nsxt_policy_l2_vpn_service.go
nsxt/data_source_nsxt_policy_qos_profile_test.go
nsxt/resource_nsxt_policy_ipsec_vpn_local_endpoint.go

With latest NSX, search API result omits locale-service component, which data sources use in filtering.
This breaks vpn local endpoint data source when used with service_path. This change switches from search API to List API for such cases.
In addition, expose local_address in local enpoint data source.

Fix VPN data sources for newer NSX version

---

.gitignore
nsxt/provider.go
nsxt/resource_nsxt_policy_context_profile_custom_attribute.go
nsxt/resource_nsxt_policy_context_profile_custom_attribute_test.go
vendor/github.com/vmware/vsphere-automation-sdk-go/services/nsxt-gm/global_infra/context_profiles/custom_attributes/CustomAttributesPackageTypes.go
vendor/github.com/vmware/vsphere-automation-sdk-go/services/nsxt-gm/global_infra/context_profiles/custom_attributes/DefaultClient.go
vendor/github.com/vmware/vsphere-automation-sdk-go/services/nsxt-gm/global_infra/context_profiles/custom_attributes/DefaultTypes.go
vendor/github.com/vmware/vsphere-automation-sdk-go/services/nsxt/infra/context_profiles/custom_attributes/CustomAttributesPackageTypes.go
vendor/github.com/vmware/vsphere-automation-sdk-go/services/nsxt/infra/context_profiles/custom_attributes/DefaultClient.go
vendor/github.com/vmware/vsphere-automation-sdk-go/services/nsxt/infra/context_profiles/custom_attributes/DefaultTypes.go
vendor/modules.txt
website/docs/r/policy_context_profile_custom_attribute.html.markdown

To allow addition of custom URLs or FQDNs to context profile objects.
Fixes: #699, #721
Signed-off-by: Kobi Samoray <ksamoray@vmware.com>

 Add FQDN or URL Custom support for context profile

---

nsxt/resource_nsxt_policy_lb_virtual_server.go
website/docs/d/policy_segment_realization.html.markdown
website/docs/r/policy_lb_virtual_server.html.markdown

A negation was missing in assesment of rule change, that relates to provider version upgrade workaround. When no change in rules is detected, we assume current rules should be preserved, for sake of rules that were added manually on NSX when rule feature was not present in proveder.
In addition, fix inconsistent documentation.

Fix mixup in condition to address lb rules

---

nsxt/resource_nsxt_policy_service.go
nsxt/resource_nsxt_policy_service_test.go
website/docs/r/policy_service.html.markdown

Hi! 
As requested in Issue #700 and #831, my contribution is adding support for nested service. 
Fixes: https://github.com/vmware/terraform-provider-nsxt/issues/700 
Fixes: https://github.com/vmware/terraform-provider-nsxt/issues/831

Adding support for Nested Services in Policy Service

---

nsxt/provider.go
website/docs/index.html.markdown

In addition, support ability to disable session auth for both MP and policy resources on provider level.
This change does not cover session reestablishment when xsrf token expires. This will be addressed in a follow-up.

Support session auth for policy resources

---

nsxt/resource_nsxt_policy_context_profile.go
nsxt/resource_nsxt_policy_context_profile_custom_attribute_test.go
nsxt/resource_nsxt_policy_context_profile_test.go
nsxt/resource_nsxt_policy_security_policy_test.go
nsxt/utils_test.go
website/docs/r/policy_context_profile.html.markdown

Allow usage of custom attributes in context profile objects.
Fixes: #698, #839

Add custom attribute support to context profile

---

nsxt/policy_common.go
nsxt/resource_nsxt_policy_security_policy_test.go
website/docs/r/policy_security_policy.html.markdown

Creation of Ethernet rules fails when ip_protocol is not null
Fixes: #841

Allow creation of Ethernet category rules

---

nsxt/data_source_nsxt_policy_gateway_policy.go
nsxt/policy_common.go
nsxt/resource_nsxt_policy_predefined_gateway_policy.go

For both GW policy and predefined GW policy resources, it makes no sense to configure categories that are reserved for system RO policies. GW policy data source is still allowed to read those categories.

Disallow creating GW policy of Read-Only category

---

nsxt/resource_nsxt_policy_ipsec_vpn_session.go
website/docs/r/policy_ipsec_vpn_session.html.markdown

In addition, make sources and destinations Optional rather than Required to match NSX validation.

Fix an issue in Policy-Based VPN session import

---

nsxt/resource_nsxt_policy_group.go
nsxt/resource_nsxt_policy_group_test.go
website/docs/r/policy_group.html.markdown

Add group_type attribue to policy group

---

nsxt/data_source_nsxt_policy_ipsec_vpn_local_endpoint_test.go
nsxt/data_source_nsxt_policy_ipsec_vpn_service_test.go
nsxt/data_source_nsxt_policy_l2_vpn_service_test.go
nsxt/resource_nsxt_policy_ipsec_vpn_local_endpoint_test.go
nsxt/resource_nsxt_policy_ipsec_vpn_service_test.go
nsxt/resource_nsxt_policy_ipsec_vpn_session_test.go
nsxt/resource_nsxt_policy_l2_vpn_service_test.go
nsxt/resource_nsxt_policy_l2_vpn_session_test.go
nsxt/utils_test.go

When VPN objects are deleted, the test still needs to leave the gateway intact, otherwise all VPN objects get auto-deleted together with parent gateway.

Fix delete scenario in VPN tests

---

nsxt/resource_nsxt_policy_tier1_gateway.go
nsxt/resource_nsxt_policy_tier1_gateway_test.go
website/docs/r/policy_tier1_gateway.html.markdown

Add ha_mode attribute to T1 gateway

---

nsxt/resource_nsxt_policy_context_profile.go
nsxt/resource_nsxt_policy_context_profile_test.go
website/docs/r/policy_context_profile.html.markdown

Context profile attributes are missing custom_url_partial_match field which was added in NSX 4.0

Add custom_url_partial_match to context profile

---

nsxt/data_source_nsxt_policy_ipsec_vpn_local_endpoint.go
nsxt/resource_nsxt_policy_ipsec_vpn_service.go
nsxt/resource_nsxt_policy_ipsec_vpn_service_test.go
nsxt/resource_nsxt_policy_ipsec_vpn_session.go
nsxt/resource_nsxt_policy_l2_vpn_service.go
nsxt/resource_nsxt_policy_l2_vpn_service_test.go
nsxt/resource_nsxt_policy_l2_vpn_session.go
nsxt/resource_nsxt_policy_l2_vpn_session_test.go
vendor/github.com/vmware/vsphere-automation-sdk-go/services/nsxt/infra/tier_0s/l2vpn_services/L2vpnServicesPackageTypes.go
vendor/github.com/vmware/vsphere-automation-sdk-go/services/nsxt/infra/tier_0s/l2vpn_services/SessionsClient.go
vendor/github.com/vmware/vsphere-automation-sdk-go/services/nsxt/infra/tier_0s/l2vpn_services/SessionsTypes.go
vendor/github.com/vmware/vsphere-automation-sdk-go/services/nsxt/infra/tier_1s/l2vpn_services/L2vpnServicesPackageTypes.go
vendor/github.com/vmware/vsphere-automation-sdk-go/services/nsxt/infra/tier_1s/l2vpn_services/SessionsClient.go
vendor/github.com/vmware/vsphere-automation-sdk-go/services/nsxt/infra/tier_1s/l2vpn_services/SessionsTypes.go
vendor/modules.txt
website/docs/r/policy_ipsec_vpn_service.html.markdown
website/docs/r/policy_ipsec_vpn_session.html.markdown
website/docs/r/policy_l2_vpn_service.html.markdown
website/docs/r/policy_l2_vpn_session.html.markdown

NSX API that uses locale service path of VPN resources will be deprecated this PR adds support for the new API that uses gateway path.
Also change data_source_nsxt_policy_ipsec_vpn_local_endpoint to use regex-based search API.
Signed-off-by: Shizhao Liu <lshizhao@vmware.com>

API Refactoring for VPN resources

---

nsxt/provider.go

With VMC, we can not rely on MP connector to be initialized.

Fix potential segmentation fault for VMC

---

website/docs/r/policy_security_policy.html.markdown

Missing  backtick right before IPv4
Fix #903

Update policy_security_policy.html.markdown: fix typo for ip_version

---

nsxt/utils.go

As the ForceNew attribute for the context doesn't apply to the project_id underneath, set this explicitly.

Force new object creation when project_id changes

---

website/docs/r/policy_ip_address_allocation.html.markdown

Documentation doesn't contain the full explanation of how to allocate an IP.

Fix ip_allocation examples in doc

---

nsxt/segment_common.go

With multitenancy and in VMC, tz is auto-assigned

Mark transport zone as computed in segments

---

nsxt/policy_common.go
nsxt/resource_nsxt_policy_gateway_policy.go
nsxt/resource_nsxt_policy_predefined_gateway_policy.go
nsxt/resource_nsxt_policy_predefined_security_policy.go
nsxt/resource_nsxt_policy_security_policy_test.go
website/docs/r/policy_gateway_policy.html.markdown
website/docs/r/policy_security_policy.html.markdown

In security policy and gateway policy, user can specify sequence numbers for the rules. This change validates their consistency with rule order upon apply and throws an error if validation fails. Before this change, inconsistent sequence number in rules would be applied and cause a permanent non-empty diff.

Validate order of rules is consistent with seq

---

nsxt/policy_utils.go
nsxt/resource_nsxt_policy_dhcp_v4_static_binding.go
nsxt/resource_nsxt_policy_fixed_segment.go
nsxt/resource_nsxt_policy_ip_address_allocation.go
nsxt/resource_nsxt_policy_ip_address_allocation_test.go
nsxt/resource_nsxt_policy_ip_pool_block_subnet.go
nsxt/resource_nsxt_policy_nat_rule.go
nsxt/resource_nsxt_policy_static_route.go
nsxt/resource_nsxt_policy_tier1_gateway_interface.go
website/docs/r/policy_ip_address_allocation.html.markdown

When importing using policy path, the provider could crash due to
invalid input. Change to terminate gracefully with an error.

Handle path parse errors

---

nsxt/provider.go
website/docs/index.html.markdown

When the new `on_demand_connection` provider flag is set to true, provider will not verify connection and pull NSX version on provider startup. Instead, those operations will be done for each provider instance when terraform objects are evaluated.
This setting is useful when NSX appliance is being deployed via same apply process, and not yet responsive when the provider is initialized. This setting is not supported for VMC and not compatible with deprecated objects implemented via the old SDK. It is also temporarily incompatible with license feature (this will be fixed in follow up PR)

Support on-demand connection init in the provider

---

nsxt/data_source_nsxt_policy_transport_zone.go
nsxt/provider.go
nsxt/resource_nsxt_policy_transport_zone.go
nsxt/resource_nsxt_policy_transport_zone_test.go
website/docs/d/policy_transport_zone.html.markdown
website/docs/r/policy_transport_zone.html.markdown

This change adds PolicyTransportZone as resource.
Compared to existing data source, the following changes are made:
- Added `site_path` and `enforcement_point_id` in case a TZ is to be created under non-default site / ep. When left out, the resource will still be CRUD'ed from default / default, or default / `nsxt.enforcement_point` in case of VMC
- `site_path`, `enforcement_point_id` and `transport_type` are made `ForceNew` as they are immutable.
- Added `uplink_teaming_policy_names` which is only supported on `VLAN_BACKED` transport zones.
- When importing, only policy path is accepted.
Fields not added due to missing from current SDK:
- `forwarding_mode`: Choice of `IPV4_ONLY`, `IPV6_ONLY`, `IPV4_AND_IPV6`
- Global manager does not support C/U/D of TZs. Thus only `infra` client is used. …

Add PolicyTransportZone resource

---

nsxt/resource_nsxt_nat_rule.go
vendor/github.com/vmware/vsphere-automation-sdk-go/services/nsxt-mp/nsx/logical_routers/nat/NatPackageTypes.go
vendor/github.com/vmware/vsphere-automation-sdk-go/services/nsxt-mp/nsx/logical_routers/nat/RulesClient.go
vendor/github.com/vmware/vsphere-automation-sdk-go/services/nsxt-mp/nsx/logical_routers/nat/RulesTypes.go
vendor/modules.txt

firewall_match attribute replace nat_pass in nsxt_nat_rule resource.
Fixes: #945

Update nsxt_nat_rule with firewall_match

---

nsxt/provider.go

As the SDK doesn't provide the capability to review the outputs towards NSX, this could become handy

Log HTTP request before sending towards NSX

---

nsxt/resource_nsxt_uplink_host_switch_profile.go
nsxt/resource_nsxt_uplink_host_switch_profile_test.go

For VDS switch type, MTU field should be blank. Therefore it cannot have a default value.

MTU value can be set to nothing

---

nsxt/policy_common.go
nsxt/resource_nsxt_policy_gateway_policy.go
nsxt/resource_nsxt_policy_security_policy.go
nsxt/resource_nsxt_policy_security_policy_test.go

NSX can not guarantee rule order unless sequence_number is provided, or `revise` API is called.
This change auto-assigns sequence number to all rules in list, for which it was not provided by the user.
It takes care of provider upgrade by making sure rules without assigned sequence number are updated even if terraform does not detect a change in them.

Fix rule order bug

---

nsxt/provider.go
nsxt/resource_nsxt_cluster_virtual_ip.go
website/docs/r/cluster_virtual_ip.html.markdown
website/docs/r/manager_cluster.html.markdown

An implementation for resource nsxt_cluster_virtual_ip to configure NSXT cluster virtual IPv4 and IPv6 address.
The virtual IP property can be part of nsxt_manager_cluster resource or an independent resource like in this PR, if we decide to implement it as part of nsxt_manage_cluster resource we can still use this PR as a reference.

Add support for configuring cluster virtual IP

---

nsxt/policy_errors.go
nsxt/resource_nsxt_compute_manager.go
nsxt/resource_nsxt_edge_cluster.go
nsxt/resource_nsxt_failure_domain.go
nsxt/resource_nsxt_manager_cluster.go
nsxt/resource_nsxt_transport_node.go

Make sure all new fabric resources use error handling helpers, and those helpers work for error spec defined in all SDK services

Fix error handling for MP SDK resources

---

nsxt/resource_nsxt_transport_node.go

In addition, mark computed fields as such. to avoid non-empty diff problem. Sinsitive attributes (such as `root_password`) will be addressed in follow-up PR.

Fix crash in transport node resource

---

nsxt/provider.go

Prevent auth and csp auth tokens from being dumped into logs

Hide sensitive info in HTTP logs

---

website/docs/r/policy_host_transport_node_profile.html.markdown
website/docs/r/transport_node.html.markdown

Remove redundant "Should be set to true" comment from documentation.

Update assigned_by_dhcp documentation

---

nsxt/data_source_nsxt_compute_manager_realization.go
nsxt/data_source_nsxt_transport_node_realization.go
nsxt/provider.go
website/docs/d/compute_manager_realization.html.markdown
website/docs/r/policy_transport_zone.html.markdown

Plus some documentation and string fixes

Implement Compute Manager realization datasource

---

nsxt/data_source_nsxt_compute_manager.go
nsxt/data_source_nsxt_compute_manager_test.go
website/docs/d/compute_manager.html.markdown

Since usually only one compute manager is configured, it is useful to retrieve its ID without providing any filters. This PR enables this.

Improve Compute Manager data source

---

nsxt/utils_test.go

The NSXT_TEST_MP test var has been renamed to NSXT_TEST_DEPRECATED as some MP resources (mostly fabric resources) are relevant.

Rename NSXT_TEST_MP environment var

---

nsxt/data_source_nsxt_policy_service_test.go
nsxt/policy_search.go

For data sources that rely on search API, functionality was broken when searched string contained special characters. This change fixes the issue by escaping special characters according to search API spec.

Fix searching by special chars in data sources

---

nsxt/provider.go
nsxt/resource_nsxt_node_user.go
nsxt/resource_nsxt_node_user_test.go
nsxt/resource_nsxt_policy_role.go
nsxt/resource_nsxt_policy_role_binding.go
nsxt/resource_nsxt_policy_role_binding_test.go
nsxt/resource_nsxt_policy_role_test.go
nsxt/utils_test.go
website/docs/r/node_user.html.markdown
website/docs/r/policy_user_management_role.html.markdown
website/docs/r/policy_user_management_role_binding.html.markdown

This PR adds the following 3 resources related to user management:
- Local users (`/api/v1/node/users`)
- Roles (`policy/api/v1/aaa/roles`)
- Role bindings (`policy/api/v1/aaa/role-bindings`)
- As password is not returned on GET, and it's possible for terraform created users to change the password out of terraform, password updates from config is not checked. Password resets could be done by deactivating then reactivate the same account.
- SSH keys (`api/v1/node/users/{userid}/ssh-keys`) and auth policy (`/api/v1/node/aaa/auth-policy`) not included
- Role validation API doesn't return error on invalid set of feature permissions. Instead, a list of "recommended" permissions will be returned. An error is raised reporting such missing permissions if the list is not empty.
- Multi-tenancy API …

Add User Management Resources

---

nsxt/policy_utils.go
nsxt/resource_nsxt_transport_node.go

NSX does not return sensitive data (e.g passwords) on GET operation, and therefore TF detects a diff.
But as the schema.Resource object contains the credentials from the state, we can keep these intact and then the value will remain as is and stored again in the state.
This is relevant to the transport_node resource as it contains multiple password attributes, which are as of now placed in empty maps during read - hence state values are ignored.

On read, extract sensitive data from state

---

nsxt/policy_utils.go
nsxt/resource_nsxt_compute_manager.go
nsxt/resource_nsxt_transport_node.go

Values used for type identifier parsing were incorrect

Fix login credential type identifier parsing

---

nsxt/resource_nsxt_manager_cluster.go

Main changes:
1. Resolve provider host address, if needed, rather than relying on comparing host names in cluster config and in provider config
2. Rely on nodes IP version rather than host IP version, which is unknown when not specified in provider config
3. Refactor Read function to update only Computed fields in state

Refactor manager cluster resource

---

.github/workflows/release.yml
nsxt/provider.go
nsxt/resource_nsxt_node_user.go
nsxt/resource_nsxt_policy_role_binding.go

This PR is to fix the broken release note header rendering since [v3.2.0](https://github.com/vmware/terraform-provider-nsxt/releases/tag/v3.2.0), due to the command line option in `goreleaser` changed from `--release-header` to `--release-header-tmpl`, where the prior one is now treated as a static file.
Also addresses the following nits in our release action:
- Bumps `ghaction-import-gpg` action to latest to address deprecation warnings of `save-state` and `set-output`
- Uses `--clean` instead of `--rm-dist` per https://goreleaser.com/deprecations/#-rm-dist
- Sets job content write permission per guideline
Takes care of regex quoting of several instances as previously not being captured by PR golang lint jobs.
Testing done:
- Action run under personal repo: …

Fix release header template

---

nsxt/policy_common.go
nsxt/resource_nsxt_policy_predefined_gateway_policy.go
nsxt/resource_nsxt_policy_predefined_security_policy.go
nsxt/resource_nsxt_policy_security_policy.go

Since sequence number is Computed in rule, bad sequence numbers may be stuck in state as a result of configurations with previous provider version.
Rather than throwing an error, the provider will auto-correct the sequence number while also logging this event.
For create flow, we leave sequence number validation since state for new object is clean.

Validate rule sequence numbers on create only

---

nsxt/provider.go
website/docs/index.html.markdown

Previous code assumed GetChange SDK routine works for provider attributes, which it doesn't (provider attributes are not stored in state).
In order to avoid reapplying licenses on every init, this change pulls license keys from backend and only applies/removes the diff.

Avoid applying lisence on every init

---

nsxt/provider.go
nsxt/resource_nsxt_manager_cluster.go
website/docs/r/manager_cluster.html.markdown

In manager cluster resource, probe for NSX connectivity before joining cluster nodes. Parameters for connection probing are specified within `node_connectivity` block.
This option is useful since nsx manager nodes might be spawned within same apply process, in which case it would take a while for NSX API endpoint to become responsive. Rather than using custom provisioner script to ensure connectivity, we give a probe and wait option in manager cluster resource.
Standard retry mechanism will not be present in this connection probing in order to avoid duplication (we expect retry parameters to be very different for regular retry and initial connection probing)

Probe NSX API endpoint in manager cluster

---

nsxt/data_source_nsxt_policy_edge_cluster.go
nsxt/data_source_nsxt_policy_tier0_gateway.go

Tenant user should be able to pull T0 gateway and edge cluster that are shared with the project, using corresponding data sources. Get API would not be available for tenant user, so this change switches data source implementation to search API.

Support tenant user creds in T0 and edge cluster

---

nsxt/data_source_nsxt_policy_ip_pool.go
nsxt/data_source_nsxt_policy_ip_pool_test.go
nsxt/resource_nsxt_policy_ip_pool.go
nsxt/resource_nsxt_policy_ip_pool_test.go
website/docs/d/policy_ip_pool.html.markdown
website/docs/r/policy_ip_pool.html.markdown

This id should be used in transport node resource

Support realized_id in ip pool data source

---

nsxt/provider.go
nsxt/resource_nsxt_policy_ldap_identity_source.go
nsxt/resource_nsxt_policy_ldap_identity_source_test.go
nsxt/utils_test.go
nsxt/validators.go
website/docs/r/policy_ldap_identity_source.html.markdown

This PR adds policy LDAP identity source resource. Both `ActiveDirectoryIdentitySource` and `OpenLdapIdentitySource` type LDAP are supported. The two resources have different resource type on NSX API, but shares the same attributes.

Add LDAP identity source resource

---

nsxt/provider.go
nsxt/resource_nsxt_policy_role_binding.go
nsxt/resource_nsxt_policy_role_binding_test.go
nsxt/resource_nsxt_principal_identity.go
nsxt/resource_nsxt_principal_identity_test.go
nsxt/utils_test.go
website/docs/r/policy_user_management_role_binding.html.markdown
website/docs/r/principle_identity.html.markdown

This PR adds support of Principle Identity resource. A principle identity is identified as a pair of PI `name` and `cert`. If an API is called with SSL client cert matching with a registered PI, the caller is recognized as the PI, granted with its roles and associated privileges.
Currently, the only non-deprecated API on NSX are:
- `createWithPem`: PI's cert pem is in-lined as part of PI creation call. The inlined pem has to be unique / new to NSX. NSX then creates a certificate in the background, and populates the MP cert id in `certificate_id` in response. This cert, however, will not be removed by NSX upon PI deletion.
- `updateCert`: If a PI's cert has expired, it can be updated by using this API call to replace the current `certificate_id` with another cert that is already in the …

Add Principle Identity resource

---

nsxt/data_source_nsxt_manager_cluster_node.go
nsxt/data_source_nsxt_manager_cluster_node_test.go
nsxt/provider.go
nsxt/utils_test.go

A data source which exposes manager cluster nodes

Implement nsxt_manager_cluster_node data source

---

nsxt/resource_nsxt_policy_tier0_gateway.go
nsxt/resource_nsxt_policy_tier0_gateway_test.go
website/docs/r/policy_tier0_gateway.html.markdown

The vrf_transit_subnets attribute is supported for NSX>=4.1.0.

Add vrf_transit_subnets to nsxt_policy_tier0_gateway (#1002)

---

nsxt/provider.go
nsxt/resource_nsxt_policy_lb_client_ssl_profile.go
nsxt/resource_nsxt_policy_lb_client_ssl_profile_test.go
website/docs/r/policy_lb_client_ssl_profile.html.markdown

Implement nsxt_policy_lb_client_ssl_profile resource

Implement policy_lb_client_ssl_profile resource

---

nsxt/resource_nsxt_policy_bgp_neighbor.go

Since password is not sent back from NSX for security reasons, it will not be present in state after import.
In this scenario, we need to avoid the password from being cleared next time an update is triggered on the imported resource. Hence we only update the password if a change in this field s detected. Note that user can leave the password blank in configuration of the imported resource.

Change password for BGP neighbor only on demand

---

nsxt/resource_nsxt_policy_tier0_gateway_test.go

TestAccResourceNsxtPolicyTier0Gateway_redistribution test fails with the following error:
resource_nsxt_policy_tier0_gateway_test.go:204: Step 2/3 error: Error running apply: exit status 1
Error: A valid edge_cluster_path is required when BGP is enabled
with nsxt_policy_tier0_gateway.test,
on terraform_plugin_test.tf line 3, in resource "nsxt_policy_tier0_gateway" "test":
3: resource "nsxt_policy_tier0_gateway" "test" {
To resolve, added the edge cluster configuration.

Fix Tier0Gateway redistribution for NSX v4.1.1

---

nsxt/resource_nsxt_policy_project.go
nsxt/resource_nsxt_policy_project_test.go

NSX sets site_info automatically to default when site isn't set. Therefore site_info attribute should be computed and tests should check this attribute according to version.

Update nsxt_policy_project to NSX v4.1.1 behavior

---

nsxt/gateway_common.go
nsxt/policy_common.go
nsxt/resource_nsxt_policy_tier0_gateway.go
nsxt/resource_nsxt_policy_tier0_gateway_test.go
nsxt/resource_nsxt_policy_tier1_gateway.go
nsxt/utils.go
nsxt/utils_test.go
website/docs/r/policy_tier0_gateway.html.markdown
website/docs/r/policy_tier1_gateway.html.markdown

Rather than recreating locale services with every update, allow to change existing locale service by specifying it nsx_id 
When nsx_id is specified for locale service, update will happen in place. When not specified, update on locale service will force new gateway object, thus recreating dependant objects such as service interfaces.

Allow to configure nsx_id for locale service

---

website/docs/r/policy_segment.html.markdown

On segment resource doc, multitenancy context has been mistakenly added to non-multitenancy example.

Remove context block from non-mutitenancy example

---

nsxt/utils.go

Empty project id is meaningless and also crashes the provider.

Verify that project_id contains a value

---

nsxt/resource_nsxt_policy_lb_virtual_server_test.go

In some test cases, we only specify the type for LbAppProfile data source when retrieving the default NSX LB app profile,
for example:
```
data "nsxt_policy_lb_app_profile" "default_http"{
type = "HTTP"
}
```
this will fail if there are other test cases that run in parallel and create LB app profile of the same type.
We need to also specify display name for the default lb app profile when creating such data source
```
data "nsxt_policy_lb_app_profile" "default_http"{
type = "HTTP"
display_name = "default-http-lb-app-profile"
}
```

[CI Fix] Specify display_name of LBAppProfile data source in test case

---

nsxt/resource_nsxt_policy_role_binding.go
nsxt/resource_nsxt_policy_role_binding_test.go
nsxt/resource_nsxt_principal_identity.go
website/docs/r/policy_user_management_role_binding.html.markdown
website/docs/r/principle_identity.html.markdown

This PR adds`overwrite_local_user` to role binding resource. When set to true, allows `Create` and `Delete` of role bindings of local users. On create, existing role bindings which comes with local user creation will be overwritten per terraform definition. On delete, the role binding will be reverted back to auditor only.
Also refactors `roles_for_path` as a set instead of list. This affects both principle identity and role binding resource, but no further doc change is needed.
Added build-in roles on NSX to doc for easier referenced. Linked NSX doc for actual permission matrix.

Add support of overwriting role binding of local user

---

nsxt/resource_nsxt_node_user_test.go
nsxt/resource_nsxt_policy_role_binding_test.go
nsxt/resource_nsxt_principal_identity_test.go
website/docs/r/node_user.html.markdown
website/docs/r/policy_user_management_role_binding.html.markdown
website/docs/r/principle_identity.html.markdown

As the API used isn't implemented before this version.

Node user tests should run for v4.1 and above

---

nsxt/policy_utils.go
nsxt/resource_nsxt_policy_ip_address_allocation.go

In IP address allocation resource, allow to configure timeout for IP realization.

Allow to configure timeout for ip allocation

---

nsxt/provider.go
nsxt/resource_nsxt_principal_identity.go
nsxt/resource_nsxt_principal_identity_test.go
website/docs/r/principal_identity.html.markdown

Those two words are used around the code and in filenames for the same resource. Standardized this to 'principal' all over for consistency.

Rename 'principle' to 'principal' around the code

---

nsxt/data_source_nsxt_certificate.go

This PR adds pagination support to certificate data source when getting a cert by name.
Fixes #849 
Testing done:
Verified importing cert on NSX-T by name with overriding `info.LocalVarOptionals["pageSize"] = int64(20)`
while total cert count is 100. 
Confirmed with debug log with proper pagination, for both found, not found and multiple found casaes.

Add pagination to certificate data source

---

nsxt/provider.go
nsxt/resource_nsxt_manager_cluster.go

When a connector is initialized for the sake of joining the manager cluster, the endpoint is different from main provider endpoint, thus global connection init flows such as NSX Version retrieval and licenses should not be triggered by such connection.

Fix connection initialization flow for joined node

---

nsxt/lb_utils.go
nsxt/policy_utils.go
nsxt/provider.go
nsxt/resource_nsxt_policy_lb_http_monitor_profile.go
nsxt/resource_nsxt_policy_lb_http_monitor_profile_test.go
nsxt/resource_nsxt_policy_lb_https_monitor_profile.go
nsxt/resource_nsxt_policy_lb_https_monitor_profile_test.go
nsxt/resource_nsxt_policy_lb_icmp_monitor_profile.go
nsxt/resource_nsxt_policy_lb_icmp_monitor_profile_test.go
nsxt/resource_nsxt_policy_lb_passive_monitor_profile.go
nsxt/resource_nsxt_policy_lb_passive_monitor_profile_test.go
nsxt/resource_nsxt_policy_lb_tcp_monitor_profile.go
nsxt/resource_nsxt_policy_lb_tcp_monitor_profile_test.go
nsxt/resource_nsxt_policy_lb_udp_monitor_profile.go
nsxt/resource_nsxt_policy_lb_udp_monitor_profile_test.go
nsxt/utils.go
website/docs/r/policy_lb_http_monitor_profile.html.markdown
website/docs/r/policy_lb_https_monitor_profile.html.markdown
website/docs/r/policy_lb_icmp_monitor_profile.html.markdown
website/docs/r/policy_lb_passive_monitor_profile.html.markdown
website/docs/r/policy_lb_tcp_monitor_profile.html.markdown
website/docs/r/policy_lb_udp_monitor_profile.html.markdown

Implement several lb monitor profile resources using policy API including:
- lb_http_monitor
- lb_https_monitor
- lb_icmp_monitor
- lb_passive_monitor
- lb_tcp_monitor
- lb_udp_monitor

Implement policy resources for lb monitor profile

---

website/docs/r/policy_intrusion_service_profile.html.markdown

Different representation of values in the UI causes confusion. This PR adds examples to the docs and adds a note about potential confusion.

Clarify and enhance docs for IDS Profile

---

nsxt/data_source_discover_node.go
nsxt/provider.go
nsxt/resource_nsxt_policy_host_transport_node.go
website/docs/d/discover_node.html.markdown
website/docs/r/policy_host_transport_node.html.markdown

1. Add Discover Node data source.
2. Remove node_deployment_info from Host Transport Node. Considering we only support Host Transport Node create from vCenter server managing the ESXi type HostNode and in this case, discovered_node_id is required, so no need to provide node_deployment_info.
Additionally, this could fix the issue that using node_deployment_info with VDS type host switch, which is the only host switch type supported, will receive error from NSX:
```
Failed to create HostTransportNode 9756979d-0165-4cc6-93dc-0c30bb6da065:
VDS Configuration is specified for host 9756979d-0165-4cc6-93dc-0c30bb6da065
and its not managed by a vCenter. Please correct TransportNode configuration
or connect the host to a VCenter. (code 9549)
```

Add discover node data source

---

nsxt/provider.go
nsxt/resource_nsxt_manager_cluster.go
website/docs/index.html.markdown

This change adds support of NSX token exchange on VMC using Oauth app, which is a newer method compared to using refresh token.
Implementation mainly referenced [python client for vmc on aws](https://github.com/vmware/python-client-for-vmware-cloud-on-aws/blob/development/pyvmc_fxns.py#L166) and terraform vmc provider.
Testing done:
With Oauth app created in server-to-server mode, assigned with all roles under "VMware Cloud on AWS" category, provider configured as:
```
provider "nsxt" {
host                 = "<nsx-private-ip>.rp.vmwarevmc.com/vmc/reverse-proxy/api/orgs/<org-id>/sddcs/<ssdc-id>/sks-nsxt-manager"
allow_unverified_ssl = true
max_retries          = 2
enforcement_point    = "vmc-enforcementpoint"
vmc_client_id        = "<oauth-app-id>"
vmc_client_secret    = …
```

Add VMC Oauth app support

---

nsxt/gateway_common.go

Multitenancy path have different formats than infra/global-infra paths.
Instead of:
```
/infra/ipv6-ndra-profiles/test
```
It would be:
```
/orgs/default/projects/test/infra/ipv6-ndra-profiles/test
```

Handle IPv6 paths correctly with multitenancy

---

nsxt/data_source_nsxt_policy_segment_realization_test.go
nsxt/resource_nsxt_policy_dhcp_server_test.go
nsxt/resource_nsxt_policy_dhcp_v4_static_binding_test.go
nsxt/resource_nsxt_policy_dns_forwarder_zone_test.go
nsxt/resource_nsxt_policy_fixed_segment_test.go
nsxt/resource_nsxt_policy_ip_pool_block_subnet_test.go
nsxt/resource_nsxt_policy_tier0_gateway_interface_test.go
nsxt/resource_nsxt_policy_tier1_gateway_interface_test.go
nsxt/resource_nsxt_policy_vlan_segment_test.go

There are a few multitenancy tests which fail while executing with a non-admin user.
This PR fixes these.

Fix multitenancy tests to pass with tenant user

---

nsxt/data_source_nsxt_policy_edge_node.go

When retrieving an edge node using the data source, set member_index attribute into state.

Set edge_node data source member_index attribute

---

nsxt/resource_nsxt_policy_bgp_config.go
nsxt/resource_nsxt_policy_tier0_gateway.go
website/docs/r/policy_bgp_config.html.markdown
website/docs/r/policy_tier0_gateway.html.markdown

These two attributes can also be specified for BGP configuration on VRFs. The terraform provider currently only sets them for BGP config for Tier-0 routers.

BGP config: support local_as_num and tags for VRFs.

---

nsxt/provider.go
nsxt/resource_nsxt_policy_tier0_gateway_gre_tunnel.go
nsxt/resource_nsxt_policy_tier0_gateway_gre_tunnel_test.go
website/docs/r/policy_tier0_gateway_gre_tunnel.html.markdown

GRE tunnel resource implementation

---

nsxt/resource_nsxt_manager_cluster.go

Output messages weren't outputed properly from provider.

Handle errors on manager_cluster resource properly

---

website/docs/d/compute_manager.html.markdown
website/docs/r/policy_host_transport_node_collection.html.markdown
website/docs/r/policy_host_transport_node_profile.html.markdown
website/docs/r/policy_ipsec_vpn_service.html.markdown

For compute manager, lookup attribute was missing from example.
For host transport node resources, edit the import part to match the same convention used elsewhere.
For IPSec VPN service, replace deprecated attribute with supported one.

Documentation fixes

---

nsxt/resource_nsxt_edge_transport_node.go

Some optional attributes aren't returned from NSX with v4.2.0 backend, the PR handles this matter.

Handle edge_node import failures

---

nsxt/resource_nsxt_policy_gateway_policy_test.go
nsxt/resource_nsxt_policy_group_test.go

Test fail occasionally due to delays in deletion of domains in global manager topologies.

Make domain name unique to address test failures

---

nsxt/resource_nsxt_edge_transport_node.go

When user provides empty strings or empty lists, NSX fails the request without specifying what exactly is missing. It is preferrable to fail those invalid configs on plan stage.

Add validators to transport node resource

---

nsxt/resource_nsxt_policy_host_transport_node_collection.go
website/docs/r/policy_host_transport_node_collection.html.markdown

While removing a host transport node collection, allow cleaning up the NSX bits from the hypervisors.
Also set revision attribute on update to allow updating.

Add the option to remove NSX during deletion

---

nsxt/resource_nsxt_policy_host_transport_node.go
nsxt/resource_nsxt_policy_host_transport_node_collection.go
website/docs/r/policy_host_transport_node.html.markdown
website/docs/r/policy_host_transport_node_collection.html.markdown

When a policy_host_transport_node is deleted, optionally remove the NSX components from the hypervisor.
Also, as NSX removal from hypervisor is the default for transport nodes, changed the behavior for transport_node_collections as well, and it make sense that destroy operation will revert the creation entirely.

Handle deletion of host_transport_node properly

---

nsxt/resource_nsxt_compute_manager.go

Since port is int rather than string, int validation is required

Fix port validation in compute manager

---

nsxt/resource_nsxt_node_user.go

NSX requires sending the old password while changing password. So the change uses the old password from the state, to verify that password change is legal.
There is an API to reset password - it requires an admin permission and won't check old password. IMO it's better so as otherwise it would indicate that state is not in sync with NSX.

Handle password change in update

---

nsxt/resource_nsxt_policy_role_binding.go

Without ForceNew for the nested attributes, replace is not triggered for principal identity resource once roles are changed. Instead, the user gets an error "doesn't support update"

Add ForceNew to nested role bindings spec

---

nsxt/resource_nsxt_policy_project.go

site is auto-assigned by NSX if edge cluster is specified

Mark site_path as Computed in project resource

---

nsxt/resource_nsxt_policy_context_profile.go
nsxt/utils.go

In addition, make sure context profile resource renders errors correctly when NSX validation fails for attributes

Validate project_id can not be whitespace string

---

nsxt/resource_nsxt_edge_transport_node.go

When an edge node is created from OVA or is a bare metal node, it should be imported into state before it's being configured.
In this case it will not have a host switch configuration.

Handle edge node with no host switch spec

---

nsxt/data_source_nsxt_edge_upgrade_group.go
nsxt/data_source_nsxt_upgrade_postcheck.go
nsxt/policy_errors.go
nsxt/provider.go
nsxt/resource_nsxt_upgrade_run.go
website/docs/d/upgrade_postcheck.html.markdown
website/docs/r/upgrade_run.html.markdown

Add Upgrade Run Resource

---

nsxt/data_source_nsxt_upgrade_prepare_ready.go
nsxt/provider.go
nsxt/resource_nsxt_upgrade_precheck_acknowledge.go
nsxt/resource_nsxt_upgrade_prepare.go
website/docs/d/upgrade_prepare_ready.html.markdown
website/docs/r/upgrade_precheck_acknowledge.html.markdown
website/docs/r/upgrade_prepare.html.markdown

Implement resources to support the upgrade for NSXT cluster
New resources and data source include:
1. nsxt_upgrade_prepare - upload precheck bundle and run precheck
2. nsxt_upgrade_precheck_acknowledge - acknowledge the warnings from precheck
3. data source nsxt_upgrade_prepare_status - Check if NSX Manager is ready for upgrade by checking if there are errors in precheck.

Resource to prepare for NSXT cluster upgrade

---

nsxt/resource_nsxt_node_user.go
nsxt/resource_nsxt_node_user_test.go

Node user tests were not specifying a password during update and therefore were failing.

Fix node user password misbehavior

---

main.go

Add some necessary code for execution of the provider with a debugger, e.g delve.
More information about using debuggers is available [here](https://developer.hashicorp.com/terraform/plugin/debugging) and [here](https://opencredo.com/blogs/running-a-terraform-provider-with-a-debugger/).

Add debug capabilities to main.go

---

nsxt/resource_nsxt_policy_qos_profile.go

When QoS profile resource is updated with incorrect value that NSX rejects, the value would still get updated in the state, even though Update returned an error.
This is terraform SDK bug:
https://github.com/hashicorp/terraform-plugin-sdk/issues/476
This change implements the suggested workaround.
We should consider to always implement this workaround as part of `handleUpdateError`, however first it would help to understand why this problem appears only for certain resources.

Fix incorrect state update following NSX error

---

nsxt/segment_common.go

Sometimes NSX sends a segment binding map with empty segment for QoS profile. This change works around this NSX issue by ignoring binding map with empty profile path.

Fix empty QoS profile issue in segment

---

nsxt/data_source_nsxt_compute_collection_test.go
nsxt/utils_test.go

A topology where compute ESXi nodes are not a part of a compute cluster should be a usable use case with acceptance tests.

Support testing of non-clustered ESXi nodes

---

nsxt/resource_nsxt_policy_host_transport_node.go

Discovered node id was not set in Read function, which was causing it not to show in state post import.

Read discovered id in host transport node resource

---

nsxt/resource_nsxt_edge_transport_node.go

When defining state refresh functions for terraform sdk wait mechanism, we normally return nil for object while waiting for state. This is actually 'not found' indication for sdk code, and sdk implements an additional stop mechanism for such cases, which causes the wait loop to exit  prematurely before timeout is reached. This fix was made for all resources in previous commit. This change completes the fix for edge transport node, which had its delete wait mechanism introduced recently and thus does not contain the fix.

Fix edge transport node state func

---

nsxt/resource_nsxt_edge_transport_node.go
website/docs/r/edge_transport_node.html.markdown

When an edge appliance is configured with no HostID attribute for the VM, the deployment fails. When host_id attribute isn't configured, HostID should be set to nil (or not set at all).
Fixes: #1053

Set edge HostId to null when host_id isn't specified

---

nsxt/provider.go
nsxt/resource_nsxt_policy_metadata_proxy.go
nsxt/resource_nsxt_policy_metadata_proxy_test.go
nsxt/segment_common.go
website/docs/r/policy_fixed_segment.html.markdown
website/docs/r/policy_metadata_proxy.html.markdown
website/docs/r/policy_segment.html.markdown
website/docs/r/policy_vlan_segment.html.markdown

Add a resource for metadata proxy and allow its configuration in segment objects.
Fixes: #1142

Implement MD proxy and use in segment resources

---

nsxt/resource_nsxt_edge_transport_node.go
website/docs/r/edge_transport_node.html.markdown
website/docs/r/policy_host_transport_node.html.markdown
website/docs/r/policy_host_transport_node_profile.html.markdown

NSX requires host_switch_name specification even though this attribute is marked as deprecated.
Without it, NSX issues an error when using multiple host switches. As this is an issue even if NSX addresses this later, it's better to add this attribute to the provider resources.
Fixes: #1146

Add host_switch_name attribute to transport node

---

nsxt/data_source_nsxt_management_cluster.go
nsxt/data_source_nsxt_management_cluster_test.go

Management cluster datasource is required to retrieve the managemnet endpoint sha256 thumbprint.
This change un-deprecates this DS as it has no replacement and changes the API in use to the NSX golang SDK.

Revise nsxt_management_cluster datasource

---

nsxt/provider.go
nsxt/resource_nsxt_edge_transport_node.go
nsxt/resource_nsxt_edge_transport_node_rtep.go
website/docs/r/edge_transport_node.html.markdown
website/docs/r/edge_transport_node_rtep.html.markdown

Sub-config objects were not set into schema in read operation.

Set sub-config in transport_node_profile resource

---

nsxt/resource_nsxt_edge_transport_node_rtep.go

RTEP configuration is used in federation topologies and should be defined after the LM managers are joined to a GM.
As edges could already exist in this point of time, it would make sense to configure the RTEP with a separate resource as also the NSX UI defines these elsewhere than the edge management (in the cluster panel).

Split edge RTEP config into separate resource

---

nsxt/resource_nsxt_edge_transport_node.go

Transport node profile doesn not support ipv6 due to SDK being outdated. This change adds a comprehensive error message when transport node profile with IPv6 assignment is imported.
When SDK is updated, this change will be reverted together with new IPv6 structures support in the resource.

Return an error message for Ipv6 assignment in TNP

---

nsxt/resource_nsxt_edge_transport_node.go

Id field is maintained within TF id property, this duplication is redundant.

Remove "id" property from edge_transport_node

---

nsxt/resource_nsxt_policy_ip_address_allocation_test.go

When an IP address is consument from an IP pool, wait for the subnet to be realized before consuming IPs from the pool.

Wait for subnet realization in ip_allocation test

---

nsxt/resource_nsxt_edge_transport_node.go

When a switch sub-config is created with no specification of IP assignment, the code mishandles it and tries set it anyway.

Switch sub-config with no IP assignment bug

---

nsxt/resource_nsxt_edge_cluster_test.go

When an edge cluster is deleted in acceptance tests, occasionally the test is failing because the code checks for successful deletion - but deletion is sometimes too slow.
Change increases the wait time before checking.

Increase sleep time before checking deletion

---

website/docs/r/policy_distributed_flood_protection_profile.html.markdown
website/docs/r/policy_gateway_flood_protection_profile.html.markdown
website/docs/r/policy_nat_rule.html.markdown

In addition, add `context` attribute to flood protection profile docs.

Clarify NAT rule docs with regards to ANY network

---

nsxt/data_source_nsxt_policy_host_transport_node_collection_realization.go
website/docs/d/policy_host_transport_node_collection_realization.html.markdown

Since corresponding resource is policy resource, it makes more sense to use path and remove the need for site_path parameter, which is part of the path.
In addition, make sure the error returned is never empty.

Change input of TNC realization from id to path

---

nsxt/resource_nsxt_policy_distributed_flood_protection_profile_binding.go
nsxt/resource_nsxt_policy_distributed_flood_protection_profile_binding_test.go
nsxt/resource_nsxt_policy_gateway_flood_protection_profile_binding.go

When revision is specified, there is no need to recreate the object manually.
In addition, remove parallelism in test because of sequence number conflict.

Support revision in flood protection binding

---

nsxt/resource_nsxt_policy_gateway_flood_protection_profile.go

It causes compilation error on some platforms. Set default value to Computed instead.

Remove hard-coded maxint default in flood profile

---

nsxt/resource_nsxt_policy_vm_tags.go

This PR adds external_id as the sortByParam for calls to the realized VM endpoint. This is needed in larger environments (1k+ VMs) because as of NSX-T 3.2.3 the /policy/api/v1/infra/realized-state/virtual-machines endpoint is not respecting a consistent ordering by default. This means that the internal slice representing VMs returned from listAllPolicyVirtualMachines may include duplicates and may be missing VMs that actually exist. Explicitly setting an order forces consistent results across the paginated calls.
Resolves: #1193

order realized VM results by external_id

---

nsxt/validators.go

validateSinglePort() validates a string value and therefore unsuitable for use in this case.
Validator is modified to allow usage also when port type is int.
Fixes: #1186

Change port validation to support both string and int types

---

nsxt/data_source_nsxt_policy_vm.go
nsxt/policy_search.go
nsxt/resource_nsxt_policy_vm_tags.go

Since 4.1.2, search API works for inventory objects, this change uses it instead of listing all VMs, dependant of NSX version. For older versions, previous codepath is used.

Use search API for pulling VM on latest nsx

---

nsxt/resource_nsxt_policy_parent_security_policy.go
nsxt/resource_nsxt_policy_security_policy.go

handleReadError swallows error in case of 404 response, so its not suitable as safeguard against returned object having nil value.

Fix a crash in security policy

---

nsxt/resource_nsxt_edge_transport_node.go

Port should follow the API spec and be defined as string rather than int. Spec allows port range, however NSX rejects multiple port config, so we'll leave the single port validation for now, while allowing to change it later without deprecating the attribute. In addition, this change removes name attribute for syslog since NSX seems to ignore it.

Update syslog config spec in edge TN resource

---

nsxt/resource_nsxt_policy_lb_client_ssl_profile_test.go

SSL protocol support has changed in this version and test should adapt accordingly

Update LB SSL tests for NSX v4.2.0

---

nsxt/resource_nsxt_policy_tier0_inter_vrf_routing.go

The code assigns the values into the wrong variable and therefore changes aren't applied correctly.
Fixes: #1210

Update out_filter in nsxt_policy_gateway_route_map

---

nsxt/provider.go

When NSX password contains certain special characters(such as &), those need to be encoded when sent to session/create API

Escape password when requesting for session token

---

GNUmakefile

Make failed when GOPATH was set as it was overwritten in the make script.
Used another name for output variable.

Fix makefile error

---

nsxt/policy_common.go
nsxt/policy_utils.go
nsxt/resource_nsxt_policy_segment_test.go
nsxt/segment_common.go
website/docs/r/policy_fixed_segment.html.markdown
website/docs/r/policy_segment.html.markdown
website/docs/r/policy_vlan_segment.html.markdown

Other tools (like VCD) may add tags to certain NSX objects managed by terraform, and expect those tags to be persisted. However, terraform provider assumes itself to be the only source of truth, and in case described above it detects drift in tags, and deletes them with apply.
This PR allows user to specify a list of tag scopes that should be ignored by the provider, more specifically:
1. diff should not be detected when such tags are present on NSX but not in terraform config
2. when provider applies tags from its own config, tags from the `ignore` list should not be deleted.
Implementation suggested here changes the Read function to sort tags into two buckets: regular tags and ignored tags. Regular tags are managed as before, whilw ignored tags (computed attribute) are appended to …

Add ignore_tags feature for segments

---

nsxt/resource_nsxt_edge_transport_node.go
nsxt/resource_nsxt_upgrade_run.go
nsxt/utils.go
website/docs/r/upgrade_run.html.markdown

Add the logic to create and update custom host groups while running the upgrade process.

Add custom groups support to upgrade run resource

---

nsxt/policy_utils.go

Before the fix, the code did not respect empty lists for certain attributes, which resulted in non-empty plan.

Fix read in separate security policy rule resource

---

nsxt/resource_nsxt_policy_ip_block.go

This change fixes setting policy IP block visibility on READ if NSX is below 4.2, where the value will always be nil. This will cause tf to always show diff if the resource spec has non-empty value.
Closes #1227

Fix set IP block visibility on READ if NSX version too low

---

nsxt/metadata/metadata.go
nsxt/metadata/metadata_poly_test.go

This PR adds support of polymorphic struct for the reflect lib. Two approaches used in existing TF resource schema are supported in this PR.
Suppose an attr `poly_struct` can accept two types: `cat` and `coffee`, the "wrapped" format expects the followings:
Suppose `poly_struct` is a list, and resource is defined as below:
```
resource "fake_poly_res" "test" {
poly_struct {
cat {
name = "matcha"
age  = 1
}
}
poly_struct {
coffee {
name      = "latte"
is_decaf  = false
}
}
}
```
`metadata` definition expects the followings:
- Declare `PolymorphicType` as `wrapped`
- Provide `ResourceTypeMap`, where the key is all potential tf sub-object (in this case, `cat` and `coffee`), and value is the `ResourceType` value reported from NSX
- Optional `TypeIdentifier` providing the SDK field name and …

Add support of polymorphic struct in reflect lib

---

nsxt/gateway_common.go
nsxt/policy_common.go
nsxt/provider.go
nsxt/resource_nsxt_policy_intrusion_service_policy.go
nsxt/resource_nsxt_policy_parent_security_policy.go
nsxt/resource_nsxt_policy_predefined_security_policy.go
nsxt/resource_nsxt_policy_security_policy.go
nsxt/resource_nsxt_policy_security_policy_test.go
nsxt/resource_nsxt_vpc_security_policy.go
nsxt/resource_nsxt_vpc_security_policy_test.go
nsxt/utils_test.go
website/docs/r/vpc_security_policy.html.markdown

Implement the resource for east-west VPC security policy.

VPC E-W security policy resource

---

api/api_list.yaml
api/infra/domains/gateway_policy.go
nsxt/policy_common.go
nsxt/provider.go
nsxt/resource_nsxt_policy_gateway_policy.go
nsxt/resource_nsxt_policy_gateway_policy_test.go
nsxt/resource_nsxt_policy_predefined_gateway_policy.go
nsxt/resource_nsxt_vpc_gateway_policy.go
nsxt/resource_nsxt_vpc_gateway_policy_test.go
website/docs/r/vpc_gateway_policy.html.markdown

Implement the resource for north-south VPC security policy.

VPC N-S security policy resource

---

nsxt/metadata/metadata.go

NSX would not accept empty value for some attributes. For those, the attribute should  be omitted in request. This PR add such support this behavior when flag is specified in metadata.

Add OmitIfEmpty option in metadata library

---

nsxt/policy_utils.go
nsxt/resource_nsxt_vpc_gateway_policy.go
nsxt/resource_nsxt_vpc_group.go
nsxt/resource_nsxt_vpc_security_policy.go

VPC resources use policy path to import resources into the TF state. This importer func does some validation that the required attributes for a policy resource import do exist.

Add VPC path importer func

---

nsxt/data_source_nsxt_vpc_test.go

VPC data source tests were prefixed with "multitenancy" but as there is a VPC test job, they could run there instead.

Rename VPC data source tests

---

nsxt/resource_nsxt_policy_share_test.go
nsxt/resource_nsxt_policy_shared_resource_test.go
website/docs/r/policy_share.html.markdown
website/docs/r/policy_shared_resource.html.markdown

As NSX v4.1.0 sharing API is different than later versions.

Skip sharing tests for v4.1.0

---

nsxt/data_source_nsxt_upgrade_prepare_ready.go
website/docs/guides/multitenancy.html.markdown
website/docs/guides/upgrade.html.markdown
website/docs/r/upgrade_prepare.html.markdown

Add a document describing the upgrade process.
Plus improve precheck failure and warning reporting, as it lacks documentation on NSX side.

Upgrade guide document

---

nsxt/data_source_nsxt_vpc_nat.go
nsxt/provider.go
nsxt/resource_nsxt_vpc_ip_address_allocation.go
nsxt/resource_nsxt_vpc_nat_rule.go
nsxt/resource_nsxt_vpc_nat_rule_test.go

This PR offers support for:
1. vpc nat rule resource
2. vpc ip address allocation resource only addresses allocated from vpc subnet can be used as dest in nat rule
3. vpc nat data source this is helpful for specifying parent_path for nat rule

Support vpc nat resource and its friends

---

nsxt/resource_nsxt_policy_ldap_identity_source.go
nsxt/resource_nsxt_policy_ldap_identity_source_test.go
website/docs/r/policy_ldap_identity_source.html.markdown

Since starting from NSX 4.2, display_name has to be identical to id, display_name attribute is redundant

Remove display_name from ldap resource

---

nsxt/policy_common.go

This would apply to all resources that inherit from ManagedResource object. Length limits are taked from NSX spec and are enforced by NSX, hence we're not breaking backwards compatibility for valid terraform configs.

Add length validation to display name and desc

---

nsxt/resource_nsxt_upgrade_prepare.go

When upload fails, report properly and fail the resource.

Handle upload failures properly

---

website/docs/r/vpc_gateway_policy.html.markdown
website/docs/r/vpc_group.html.markdown
website/docs/r/vpc_security_policy.html.markdown

nsxt_policy_vpc datasource has been renamed to nsxt_vpc

Fix VPC documentation with correct DS name

---

nsxt/policy_utils.go
nsxt/utils.go
nsxt/validators.go

To avoid entry of invalid ids to the context fields.

Add id field validator and apply to context ids

---

nsxt/resource_nsxt_policy_tier1_gateway.go

Setting empty string to tier0path attribute of tier1 causes failures later on in NAT creation.

Fix tier1 for v4.2.0

---

nsxt/metadata/metadata.go
nsxt/metadata/metadata_test.go

When empty clause is specified in resource, the code needs to guard against nil value before casting the value to map. This PR ensures this protection.

Fix crash in metadata code with empty clause

---

nsxt/provider.go
nsxt/resource_nsxt_vpc_service_profile.go
nsxt/resource_nsxt_vpc_service_profile_test.go
nsxt/utils_test.go
website/docs/r/vpc_service_profile.html.markdown

Extended tests will be added as follow up

Vpc20 service profile support

---

nsxt/data_source_nsxt_policy_uplink_host_switch_profile.go
website/docs/d/policy_ip_pool.html.markdown
website/docs/d/policy_uplink_host_switch_profile.html.markdown

Uplink host switch profile data source does not retrieve the realized_id of the object. It is also not retrievable with the nsxt_policy_realization_info data source, as the data returned by NSX doesn't contain this info, e.g
```
{
"results" : [ {
"entity_type" : "RZ_BASE_HOST_SWITCH_PROFILE",
"intent_paths" : [ "/infra/host-switch-profiles/da7ea85b-e286-47bd-950e-bd7a8519c120" ],
"resource_type" : "GenericPolicyRealizedResource",
"id" : "da7ea85b-e286-47bd-950e-bd7a8519c120",
"display_name" : "da7ea85b-e286-47bd-950e-bd7a8519c120",
"path" : "/infra/realized-state/enforcement-points/default/host-switch-profiles/da7ea85b-e286-47bd-950e-bd7a8519c120",
"relative_path" : "da7ea85b-e286-47bd-950e-bd7a8519c120",
"parent_path" : "/infra/realized-state/enforcement-points/default",
"remote_path" : …
```

Address issue with nsxt_policy_uplink_host_switch_profile

---

nsxt/data_source_nsxt_upgrade_prepare_ready.go
nsxt/resource_nsxt_upgrade_prepare.go
nsxt/resource_nsxt_upgrade_run.go
nsxt/util/utils.go

We added some id attributes in the upgrade resources to enforce dependency, yet we never validate these.

Verify that id is actually from the prepare resource

---

nsxt/policy_utils.go
nsxt/resource_nsxt_policy_gateway_policy.go
nsxt/resource_nsxt_policy_group.go
nsxt/resource_nsxt_policy_parent_security_policy.go
nsxt/resource_nsxt_policy_security_policy.go
nsxt/resource_nsxt_transit_gateway.go
nsxt/resource_nsxt_vpc_connectivity_profile.go
nsxt/resource_nsxt_vpc_service_profile.go

To avoid exessive merges, non-vpc resources will follow later.

Disallow empty tag{} clause in VPC resources

---

go.sum
nsxt/resource_nsxt_policy_project.go
nsxt/resource_nsxt_policy_project_test.go

This commit adds attributes introduced in recent NSX versions to the Project resource.
This commit also refactors the test module for reourceNSXTPolicyProject adding multiple CRUD tests, each one tailored for a different NSX versions. These tests are meant to be backward compatible, ie: the test for NSX 4.1.0 also works, on 4.1.x, 4.2.x, and subsequent releases.

Sync Project resource with latest API

---

nsxt/resource_nsxt_vpc_connectivity_profile.go

Enabling the service gateway requires specification of an edge cluster, and therefore the default value cannot be "true"

VPC conn profile: do not enable service gateway by default

---

nsxt/resource_nsxt_policy_group.go
nsxt/resource_nsxt_policy_group_test.go

As every element in the CriteriaSet schema is empty, users migth specify an empty block (ie: 'criteria {}'). This causes the provider to panic as the criteria validation routine tries to cast from nil.
With this change, the provider will reject this configuration as invalid.

Policy Group: Check for nil entries in criteria block

---

website/docs/r/policy_transit_gateway_attachment.html.markdown

The connection path property is for specifying a TGW external connection rather than a connectivity profile.

[TGW attachment] Fix documentation for connection_path

---

nsxt/resource_nsxt_upgrade_run.go
nsxt/util/utils.go

NSX preserve some information in this object and therefore it shouldn't be replaced. Instead, values should be set within this list, or appended when the key doesn't exist.

Do not overwrite extended_configuration attribute of upgrade unit group

---

nsxt/resource_nsxt_policy_transit_gateway.go

NSX sets a default transit subnet for a TGW if None is specified. As this default subnet is returned in the API response, the Terraform provider must treat the transit_subnet attribute as computed.

[VPC 2.0] Make transit_subnets for TGW computed

---

nsxt/resource_nsxt_vpc_subnet.go

This attribute was added with the latest SDK bump, the vpcSubnetModeAccessValues enum must be updated to include it.
Entry has been manually added to enum.

[VPC 2.0] Add Private_TGW subnet access mode

---

nsxt/resource_nsxt_compute_manager.go
website/docs/r/compute_manager.html.markdown

Although changing the default is not a backward compatible change, we are making an exception for this attribute since compute manager without service account will be forbidden in NSX 9.0.0 onwards.

Change default for create_service_account in CM

---

nsxt/resource_nsxt_vpc.go
nsxt/resource_nsxt_vpc_test.go

With this change, when short_id is not specified in the TF config, the provider won't send anymore an empty string to NSX, ensuring the short_id is auto-generated as expected.
Also adding a case for short_id autogeneration in acceptance tests.

 [VPC2.0] VPC: short_id must use OmitIfEmpty

---

nsxt/resource_nsxt_policy_context_profile_test.go
nsxt/resource_nsxt_policy_security_policy_test.go
nsxt/resource_nsxt_vpc_security_policy_test.go
nsxt/utils_test.go

This test creates context profile and shares it with the VPC

Enable VPC policy rule test with context profiles

---

nsxt/resource_nsxt_policy_share_test.go
nsxt/resource_nsxt_policy_shared_resource.go
nsxt/resource_nsxt_policy_shared_resource_test.go
nsxt/utils_test.go
website/docs/r/policy_shared_resource.html.markdown

Context is determined fromthe parent share_path
For consistency with other resources, we don't expose the context block (which provides redundant info) when parent path is present and required.

Remove context block from shared resource

---

nsxt/resource_nsxt_compute_manager.go
website/docs/r/compute_manager.html.markdown

This comes as NSX changes default for this attribute

Mark service_account computed in compute manager

---

nsxt/resource_nsxt_policy_project.go
nsxt/resource_nsxt_policy_project_test.go
website/docs/r/policy_project.html.markdown

Add the attribute above and manage it vs the VpcSecurityProfiles client

Add default_security_profile attribute to project

---

.github/workflows/golangci-lint.yml
.github/workflows/golangci-ut.yml
.github/workflows/release.yml
.golangci.yml
nsxt/data_source_nsxt_policy_uplink_host_switch_profile.go
nsxt/data_source_nsxt_upgrade_prepare_ready.go
nsxt/resource_nsxt_upgrade_run.go

And fix resuting linter errors

Bump up golang in github actions

---

nsxt/provider.go
nsxt/resource_nsxt_policy_project_ip_address_allocation.go
nsxt/resource_nsxt_policy_project_ip_address_allocation_test.go

Functions for the resource above were using a non-policy prefixed names which is inconsistent.

Rename nsxt_policy_ip_address_allocation funcs

---

nsxt/resource_nsxt_policy_transit_gateway_attachment.go
website/docs/r/policy_transit_gateway_attachment.html.markdown

This is not properly set in the API spec but NSX enforces this requirement.

TGW attachment connection_path attribute should be required

---

nsxt/resource_nsxt_upgrade_run.go

When host upgrade is done with VLCM, there is the possibility that host upgrade will not be concluded and then, result will be a paused state. This case should be handled as partial upgrade.

Handle VLCM upgrade as potentially partial

---

nsxt/policy_utils.go

While processing an import request with a policy path, make sure that URL is valid.

Validate policy path is actually an acceptable URL in path importers

---

nsxt/resource_nsxt_upgrade_run.go

Upgrade state can be erased in NSX due to various reasons, e.g restoration from backup. In this case the TF state could allow execution of the nsxt_upgrade_run resource even though there is no ongoing backup.
This case should be properly handled instead of failing with a SIGSEGV.

Check that target version is set

---

nsxt/resource_nsxt_edge_transport_node.go
website/docs/r/policy_host_transport_node.html.markdown
website/docs/r/policy_host_transport_node_profile.html.markdown

In host_transport_node_profile, host_switch_mode attribute can be set by NSX, and the default behavior is changed.

Remove default for host_switch_mode, set to Computed

---

nsxt/resource_nsxt_policy_distributed_vlan_connection.go
website/docs/r/policy_distributed_vlan_connection.html.markdown

These are not properly set in the API spec but NSX enforces them as required.

 Distributed VLAN connection: set vlan_id and gateway_addresses as required

---

nsxt/resource_nsxt_edge_transport_node.go

If this attribute is set only as Computed, the SDK plugin won't accept any ValidateFunc for it.

Standard Host switch: set host switch mode as Optional

---

.github/workflows/golangci-lint.yml
.github/workflows/golangci-ut.yml
.github/workflows/release.yml
.golangci.yml
nsxt/data_source_nsxt_policy_host_transport_node_collection_realization.go
nsxt/data_source_nsxt_policy_uplink_host_switch_profile.go
nsxt/data_source_nsxt_upgrade_prepare_ready.go
nsxt/policy_errors.go
nsxt/resource_nsxt_lb_pool.go
nsxt/resource_nsxt_policy_ipsec_vpn_session.go
nsxt/resource_nsxt_upgrade_prepare.go
nsxt/resource_nsxt_upgrade_run.go

And adjust code to new linter settings

Bump up github action versions and linter

---

nsxt/resource_nsxt_upgrade_run.go

Edge components do not have this attribute and host components potentially could miss it as well. The code should handle this case to avoid crash.

Handle upgrade components with no upgrade_mode property

---

website/docs/d/policy_project_ip_address_allocation.html.markdown
website/docs/d/vpc_ip_address_allocation.html.markdown

This change fixes the documentation for Project and VPC IP allocation data sources, replacing ip_allocations with allocation_ips.

IP allocation data sources documentation

---

nsxt/policy_utils.go
nsxt/resource_nsxt_policy_distributed_vlan_connection.go
nsxt/resource_nsxt_policy_gateway_connection.go
nsxt/resource_nsxt_policy_project_ip_address_allocation.go
nsxt/resource_nsxt_policy_share.go
nsxt/resource_nsxt_policy_transit_gateway.go
nsxt/resource_nsxt_vpc_connectivity_profile.go
nsxt/resource_nsxt_vpc_service_profile.go

For resources residing under a project, we only support policy path as import ID. This change introduces PolicyPathOnly importer that only allows policy paths, as opposed to old validator that allows both policy path and ID

Improve validation for project importers

---

nsxt/policy_common.go

Excessive long URIs will not be accepted by NSX.
There should be no need to specify long NSX ids in Terraform resources, therefore capping length to
1024 characters to avoid hitting unexpected issues while refreshing resource state.

Limit NSX Id to 1024 characters

---

nsxt/resource_nsxt_vpc_nat_rule.go
website/docs/r/policy_transit_gateway_nat_rule.html.markdown
website/docs/r/vpc_nat_rule.html.markdown

NSX mandates rule action to be specified for both TGW and VPC NAT rules, but in the API spec this attribute is not specified as required.
This change addresses this.
Resources' documentaiton has been updated to mark the attribute as required.

VPC and TGW NAT rules: make Action Required

---

nsxt/resource_nsxt_policy_project_ip_address_allocation.go
nsxt/resource_nsxt_vpc.go
nsxt/resource_nsxt_vpc_connectivity_profile.go
nsxt/resource_nsxt_vpc_dhcp_v4_static_binding_config.go
nsxt/resource_nsxt_vpc_external_address.go
nsxt/resource_nsxt_vpc_ip_address_allocation.go
nsxt/resource_nsxt_vpc_nat_rule.go
nsxt/resource_nsxt_vpc_service_profile.go
nsxt/resource_nsxt_vpc_static_routes.go
nsxt/resource_nsxt_vpc_subnet.go

After merging VPC branch, this will be refactored to apply to all resources as part of handleUpdateError routine.

Mark partial update when NSX update fails for vpc

---

.github/workflows/release.yml

This is cherry-picked from 3.7.0 release branch

Fix release spec to use organization secrets rather than repository secrets

---

main.go

Replaces the deprecated `plugin.Debug` with the `Debug` field in `ServeOpts`.
Also simplifies `debugMode`.

chore: replace deprecated `plugin.Debug`

---

nsxt/resource_nsxt_vpc_connectivity_profile.go
website/docs/r/vpc_connectivity_profile.html.markdown

This attribute is removed from first VPC2.0 release on platform

Remove IP blocks from connectivity profiles NAT

---

nsxt/resource_nsxt_policy_vm_tags.go

This is needed for VMC use case

While listing VMs, pass enforcement point param

---

nsxt/resource_nsxt_policy_transit_gateway_attachment.go
website/docs/r/policy_transit_gateway_attachment.html.markdown

In addition, refine documentaion for this resource

Remove context from transit gateway attachment resource

---

nsxt/resource_nsxt_edge_transport_node.go
nsxt/resource_nsxt_policy_host_transport_node.go
nsxt/resource_nsxt_policy_host_transport_node_profile.go

The code assumes that specified host_switch_profile is always of type uplink which is incorrect.
Fixes: #1441

Add proper host_switch_profile type with id, while setting in hostswitch

---

website/docs/guides/upgrade.html.markdown

Updates the syntax of the `nsxt_upgrade_run` resource where the data sources were placed within the run resource instead of above it.
Renames some of the display names within the example:  predefined groups have a naming scheme which is set by NSX, and enhanced readability of hosts' data source display names.

docs: correct example in upgrade group

---

nsxt/policy_utils.go

Path parsing func parseStandardPolicyPath() didn't handle well project paths, seems like it could only handle sub-project objects.

Handle project path parsing properly

---

nsxt/resource_nsxt_compute_manager.go
website/docs/r/compute_manager.html.markdown

In compute manager resource, NSX no longer accepts false value for create_service_account attribute.
Since terraform sdk can't distinguish between unset value and false value for the attribute, we will ignore the attribute entirely for NSX 9.0 and above

Ignore create_service_account with NSX 9.0.0

---

nsxt/resource_nsxt_upgrade_prepare.go
website/docs/r/upgrade_prepare.html.markdown

Upgrade bundle contains the pre-checks as well. This attribute can be still used when a user would like to run pre-checks from a later build than the upgrade itself.

Pre-check bundle should be optional also for 4.1.1 and beyond

---

nsxt/resource_nsxt_policy_project_ip_address_allocation.go
nsxt/resource_nsxt_policy_project_ip_address_allocation_test.go
nsxt/resource_nsxt_vpc_ip_address_allocation_test.go

This follows fix on NSX, that supports update of generic fields, which was blocked earlier

Allow updating IP allocation under project or VPC

---

.github/workflows/codeql-analysis.yml

chore(gh): add codeql analysis

---

nsxt/resource_nsxt_policy_lb_virtual_server.go

Empty block can be configured when no required attributes are defined in the block. In this case nil protection is required, since empty block is presented as nil rather than empty map in the schema structure.

Fix crash related to empty block in lb_vs resource

---

nsxt/data_source_nsxt_policy_vm.go
nsxt/data_source_nsxt_policy_vm_test.go
website/docs/d/policy_vm.html.markdown

It's rather convenient to have the tags for a given VM when using the data source, so here is a suggested enhancement. This is my first encounter with this provider, so please let med know if there's any changes the maintainers would like to see implemented.
I've tested this with a debugger towards a local environement.

data.nsxt_policy_vm: exports tags

---

nsxt/removed_resource_wrapper.go

The wrapper function was updating the existing importer, but the replaced function ended up having the same pointer as the wrapper function, meaning that import would enter an infinite recursion loop.
Tested by doing import, read, update, and delete for
1) nsxt_logical_tier1_router
2) nsxt_ip_pool

ImporterWrapper: Allocate a new Importer object (#1481)

---

nsxt/resource_nsxt_edge_transport_node.go
website/docs/d/transport_node_realization.html.markdown
website/docs/r/edge_transport_node.html.markdown

Normally users create Edge Transport Nodes within NSX, which deploys them into the regsitered compute manager. However, users have the option to do the same by deploying the Edge appliance anywhere, outside NSX, and registering it with NSX using the Edge CLI or OVA parameters. Later, this Edge appliance can be converted into a transport node using NSX API - this change attempts to utilize this capability.
Fixes: #1459

Add support for Edge transport nodes which were created externally

---

nsxt/resource_nsxt_policy_project.go
website/docs/r/policy_project.html.markdown

This is relevant for NSX 9.0.0 onwards.
In addition, mark `default_security_profile` as Computed to avoid non-empty diff.

Add `vc_folder` flag to project definition.

---

nsxt/resource_nsxt_edge_transport_node.go

User may use system-defined hostswitch profiles while creating transport nodes, and should be retrieved as well as user defined hostswitch profiles.

Retrieve also system-defined hostswitch profile while creating transport nodes

---

website/docs/r/edge_transport_node.html.markdown

Edge transport node transport_zone and host_switch_id attributes can handle path parameters but it is better to avoid using it instead of id values. For now we only document this and will handle that within the code later on.

Fix edge transport node documentation

---

nsxt/resource_nsxt_upgrade_prepare.go

NSX v9.0 upgrade introduces few changes:
* A new upgrade component, 'FINALIZE_UPGRADE'.
* Pre-upgrading the HOST compoenent during the ESXi upgrade.
Upgrading the hosts outside of upgrading coordinator (by upgrading ESXi) affects the FINALIZE_UPGRADE component - it can be either in 'PAUSE' state, or 'NOT_STARTED'.

Handle v9.0 upgrade finalize case correctly

---

nsxt/resource_nsxt_policy_project_test.go

This function is not used and raises a linter error

Remove testAccNsxtPolicyProjectTemplateWithIPBlock

---

nsxt/provider.go

Removes the use of `io/ioutil`.
As of Go 1.16, the same functionality is now provided by package `io` or package `os`, and those implementations are preferred in new code.

chore: remove use of `io/ioutil`

---

nsxt/resource_nsxt_policy_group.go
nsxt/resource_nsxt_policy_group_test.go

This follows NSX allowing mixing some member types within same expression block, which was not allowed earlier.
Rather then following NSX validation for which member types mixes are permitted, terraform will let NSX do the validation for this part. Other validations on terraform side - such as same expression type - are not affected by this change.

Remove member type validation in group criteria

---

.golangci.yml

Updates `golangci-lint` configuration.
**BEFORE**:
```console
➜ golangci-lint run
WARN [config_reader] The configuration option `linters.errcheck.ignore` is deprecated, please use `linters.errcheck.exclude-functions`. 
```
**AFTER**:
```console
➜ golangci-lint run
nsxt/resource_nsxt_policy_project_test.go:572:6: func `testAccNsxtPolicyProjectTemplateWithIPBlock` is unused (unused)
func testAccNsxtPolicyProjectTemplateWithIPBlock(displayName string) string {
^
```

chore: update golangci-lint configuration

---

nsxt/resource_nsxt_compute_manager.go

In compute manager resource Read function, the code should not expect NSX to send back sensitive data. We need to keep intent value for sensitive data in state. This was already handled for password, this PR completes the support for other type of sensitive data.

Avoid resetting sensitive data in CM Read

---

.github/workflows/golangci-lint.yml

skip-pkg-cache and skip-build-cache has been removed in v6.x version of golangci-lint, and therefore removed from config. See here:
https://github.com/golangci/golangci-lint-action/blob/master/README.md#compatibility
This will suppress the warning below from golangci-lint execution:
```
Unexpected input(s) 'skip-pkg-cache', 'skip-build-cache', valid inputs are ['version', 'install-mode', 'working-directory', 'github-token', 'only-new-issues', 'skip-cache', 'skip-save-cache', 'problem-matchers', 'args', 'cache-invalidation-interval']
```

Remove golangci-lint parameters which are unsupported

---

nsxt/policy_utils.go

This change protects against nil value when empty credential block is provided.

Fix panic in compute manager

---

website/docs/r/policy_host_transport_node_collection.html.markdown

The recommended way to provide compute collection id is with nsxt_compute_collection data source

Fix documentation for host TN collection resource

---

nsxt/data_source_nsxt_policy_groups.go
nsxt/data_source_nsxt_policy_groups_test.go
nsxt/data_source_nsxt_policy_services.go
nsxt/data_source_nsxt_policy_services_test.go
nsxt/provider.go
website/docs/d/ns_services.html.markdown
website/docs/d/policy_groups.html.markdown
website/docs/d/policy_services.html.markdown

These data sources allows the retrieval of the entire tables from NSX to save multiple calls to the backend.
Fixes: #696

Implement map data sources for policy services and groups

---

nsxt/metadata/metadata.go

Debugging output can be turned on by setting:
```
export TF_LOG_METADATA_DEBUGGING=1
```

Suppress excessive output from metadata library

---

.github/workflows/release.yml

- Correct formatting.
- [Pin GitHub Actions to release commit SHA](https://docs.github.com/en/actions/security-for-github-actions/security-guides/security-hardening-for-github-actions#using-third-party-actions).

chore(gh): update release

---

nsxt/resource_nsxt_edge_transport_node.go
website/docs/r/edge_transport_node.html.markdown
website/docs/r/policy_host_transport_node.html.markdown
website/docs/r/policy_host_transport_node_profile.html.markdown

Deprecate list of host switch profiles, and introduce typed profile attributes instead - `uplink_profile` and `vtep_ha_profile`. This is because certain profile types are autoassigned by NSX, in which case permadiff is introduced, unless the user fixes it by adding the auto-assigned profile into resource intent.
Having type-specific computed attributes solves this problem.

Replace host switch profiles attr with typed ones

---

nsxt/policy_errors.go
nsxt/resource_nsxt_upgrade_run.go

The resource nsxt_upgrade_run crashed while receiving a 500 error while polling for upgrade status. This status should be handled as other statuses which we swallow while waiting for MP to restart.

Fix nsxt_upgrade_run crash

---

nsxt/policy_common.go
nsxt/resource_nsxt_policy_gateway_policy_test.go
nsxt/resource_nsxt_policy_security_policy_rule.go
nsxt/resource_nsxt_policy_security_policy_rule_test.go
nsxt/resource_nsxt_policy_security_policy_test.go
nsxt/resource_nsxt_policy_service.go
nsxt/resource_nsxt_policy_service_test.go
website/docs/r/policy_gateway_policy.html.markdown
website/docs/r/policy_security_policy.html.markdown
website/docs/r/policy_security_policy_rule.html.markdown

This follows API change on NSX that allows to specify explicit service entries on rule, as an alternative to service path.

Support service entries in policy rules

---

nsxt/gateway_common.go
nsxt/resource_nsxt_policy_tier0_gateway.go
nsxt/resource_nsxt_policy_tier0_gateway_interface_test.go
nsxt/resource_nsxt_policy_tier1_gateway.go
nsxt/resource_nsxt_policy_tier1_gateway_interface_test.go
nsxt/resource_nsxt_policy_tier1_gateway_test.go

This change removes ForceNew from nsx_id attribute in locale service schema, in order to avoid recreating the gateway when locale service is added.
Without this fix, adding locale_service within the gateway would trigger recreation even when nsx_id is not specified, since nsx_is is defined as Computed.

Avoid recreating gateway when locale service added

---

nsxt/resource_nsxt_upgrade_run.go
website/docs/r/upgrade_run.html.markdown

The upgrade run resource has some attributes which control the wait for the upgrade execution. However these aren't documented, and could be handy.
Also, change default initial delay to 5 minutes.

Document undocumented attributes of nsxt_upgrade_run

---

nsxt/gateway_common.go
nsxt/resource_nsxt_policy_tier0_gateway.go
nsxt/resource_nsxt_policy_tier0_gateway_test.go
nsxt/resource_nsxt_policy_tier1_gateway.go

When attribute is Computed, clearing the attribute is not flagged by terraform SDK as change in intent. This means user can not clear edge cluster path and convert gateway to Distributed Only mode.
In addition, fix log printouts.

Remove Computed from gateway edge cluster path

---

nsxt/resource_nsxt_upgrade_run.go

Upgrade run crashes while waiting for state, we should return nil when an error is returned.
To improve troubleshooting, added a few debug logs, and return nil explicitly when an error is raised.

Handle upgrade run crash, log returned error

---

nsxt/resource_nsxt_upgrade_run.go

Let the user control the number of retries which we execute while waiting for the upgrade coordinator status to change.

Add maximum retry count to nsxt_upgrade_run

---

nsxt/resource_nsxt_policy_intrusion_service_profile.go
nsxt/resource_nsxt_policy_tier0_gateway.go
nsxt/resource_nsxt_policy_tier0_gateway_interface.go
nsxt/resource_nsxt_upgrade_run.go
nsxt/segment_common.go
website/docs/r/policy_intrusion_service_profile.html.markdown

Empty block is represeted in schema by slice of size 1 with nil value. Wherever empty block is allowed (no required attributes), we should protect against nil values in slice.

Protect casting against nil conversion

---

nsxt/resource_nsxt_policy_group.go
website/docs/r/policy_group.html.markdown

NSX does not allow to update this attribute on existing group, hence it should be trigger recreation.

Mark group type as ForceNew

---

nsxt/resource_nsxt_policy_intrusion_service_profile.go
website/docs/r/policy_intrusion_service_profile.html.markdown

The NSXT terraform provider (resource "nsxt_policy_intrusion_service_profile") supports severities "LOW", "MEDIUM", "HIGH" and "CRITICAL". Adding "SUSPICIOUS" to the list.

Adding SUSPICIOUS severity support to nsxt_policy_intrusion_service_profile resource

---

nsxt/resource_nsxt_policy_lb_pool.go
website/docs/r/policy_lb_pool.html.markdown

IP addresses in SNAT can only be specified for certain snat type

Improve validation for LB pool resource

---

nsxt/policy_utils.go
nsxt/provider.go
nsxt/resource_nsxt_policy_edge_transport_node.go
website/docs/r/policy_edge_transport_node.html.markdown

For NSX v9.0, transport node API is deprecated and replaced with policy API which provides extra functionality.

Implement policy edge resource

---

website/docs/r/policy_tier0_gateway.html.markdown

nsxt_policy_tier0_gateway example contained force_whitelisting attribute which had been deprecated.

Remove depreceted attribute from tier0_gateway example

---

.github/ISSUE_TEMPLATE/bug.yml
.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/docs.yml
.github/ISSUE_TEMPLATE/enhancement.yml

Adds issue templates in the form format for:
- Bugs
- Documentation
- Enhancements

chore: add issue templates

---

nsxt/resource_nsxt_policy_tier0_gateway.go
nsxt/resource_nsxt_policy_tier0_gateway_gm_test.go
nsxt/resource_nsxt_policy_tier0_gateway_test.go
website/docs/r/policy_tier0_gateway.html.markdown

I'm omitting `connectivity` attribute from the docs since NSX ignores it. The fix in NSX will be available in next version, hence leaving support in the code.

Expose advanced_config in Tier0 Gateway

---

nsxt/validators.go

The code was relying on IPv6 string comparison to determine if IP provided in subnet mask was different from mask base. This comparison is incorrect for IPv6 since net library omits the last zero for ipv6.

Fix IPv6 validation in various resources

---

nsxt/resource_nsxt_vpc_connectivity_profile_test.go
nsxt/resource_nsxt_vpc_service_profile_test.go

Two parallel tests created profile with the same name, which resulted in failure in data source retrieval.
Avoid the issue by randomizing name in import test.
Signed-off-by: Anna Khmelnitsky <anna.khmelnitsky@broadcom.com>

Fix race condition in vpc profile tests

---

nsxt/resource_nsxt_upgrade_precheck_acknowledge.go
nsxt/resource_nsxt_upgrade_run.go

Upgrade run resource can activate pause_after_each_upgrade_unit attribute which pauses after each unit within the upgrade group.
The upgrade should also pause after before moving on to the next component type since a user might need to do some manual operation.
The UI has this capability.
Also, set the delay parameter in waitUpgradeForStatus only when needed:
During upgrade execution, There are long stretches of time where polling NSX has no value as Edges are restarted/hosts are being configured/Manager is being restarted. However in different cases polling can start immediately.

Fix upgrade pause issue

---

nsxt/data_source_nsxt_policy_edge_transport_node.go
nsxt/data_source_nsxt_policy_edge_transport_node_test.go
nsxt/provider.go
website/docs/d/policy_edge_node.html.markdown
website/docs/d/policy_edge_transport_node.html.markdown

This data source doesn't require the Edge cluster like nsxt_policy_edge_node, and retrieves the policy path of the edge node itself.

Add nsxt_policy_edge_transport_node data source

---

docs/resources/policy_edge_cluster.md

Documentation included reference to a data source which doesn't exist.

Fix documentation issue in nsxt_policy_edge_cluster

---

nsxt/resource_nsxt_policy_project_test.go

This test fails due to NSX change.

Fix TestAccResourceNsxtPolicyProject_900defaultSecurityProfile test

---

docs/resources/policy_edge_cluster.md
nsxt/resource_nsxt_policy_edge_cluster.go

The API call fails with an error when attribute is not set, so let's require it.

For policy edge cluster, edge_cluster_profile_path should be required

---

nsxt/resource_nsxt_policy_edge_transport_node.go

Such import causes a provider crash as SwitchSpec.Switches can be null (either of).

Handle import when edge appliance has no switch specs

---

.goreleaser.yml
terraform-registry-manifest.json

- Updates the GoReleaser configuration to v2.
- Uses the recommended order.
- Add the `terraform-registry-manifest.json` for the release workflow. [Reference](https://developer.hashicorp.com/terraform/tutorials/providers-plugin-framework/providers-plugin-framework-release-publish#verify-terraform-registry-manifest-file).
Before:
```shell
terraform-provider-nsxt on  chore(gh)/update-to-goreleaser-v2 via 🐹  
➜ goreleaser check
• only  version: 2  configuration files are supported, yours is  version: 0 , please update your configuration
• checking                                 path=.goreleaser.yml
• DEPRECATED:  archives.format  should not be used anymore, check https://goreleaser.com/deprecations#archivesformat for more info
• .goreleaser.yml …
```

chore(gh): update to goreleaser v2

---

nsxt/resource_nsxt_policy_ip_address_allocation.go
nsxt/resource_nsxt_policy_ip_address_allocation_test.go

When ip address allocation resource is used without specific IP, platform allocates the address from the pool asyncronously. Previously, wait for the allocation happened in Read flow. This is problematic, since if allocation fails, resource cannot be deleted unless -refresh=false option is used.
This change fixes the code to wait for allocation in create flow. If allocation fails, create fails as well.

Wait for ip address allocation on create

---

.github/workflows/release.yml

- Updates `actions/checkout` to v4.2.2.
- Updates `actions/setup-go` to v5.4.0.
- Updates `golangci/golangci-lint-action` to v7.0.0.
- Updates `golangci/golangci-lint-action` to use `latest` of `golangci-lint` to match `golangci-lint.yml`.
- Removes `skip-pkg-cache` and `skip-build-cache` options that were removed April 2024 in `golangci/golangci-lint-action` v5.0.0 asinc ethe cache management is handled in `actions/setup-go`. 
Ref: https://github.com/golangci/golangci-lint-action/releases/tag/v5.0.0

chore(gh): update release workflow

---

docs/data-sources/policy_edge_transport_node.md
docs/resources/policy_edge_transport_node.md

Data source doc filename is incorrectly suffixed.
Also add a comment for non-updatable attributes.

Edge transport node docfix

---

nsxt/data_source_nsxt_policy_transport_zone_test.go
nsxt/resource_nsxt_policy_edge_high_availability_profile_test.go
nsxt/resource_nsxt_policy_ip_block_quota.go
nsxt/resource_nsxt_policy_ip_block_quota_test.go
nsxt/resource_nsxt_policy_transit_gateway_attachment_test.go

The IpBlockQuota import test should not run on GM, and the create should not end with null ptr exception.
The PolicyEdgeHighAvailabilityProfile, PolicyTransitGatewayAttachment tests shouldn't run on GM as well.
TestAccDataSourceNsxtPolicyTransportZone_basic tests for realized_id - this has been introduced in 3.8.0 which wasn't tested against GM. As this attribute isn't set by GM, test has been split into a GM test an a LM test.

Address GM failures

---

docs/resources/policy_ip_block_quota.md

Visibility and IP address type are required attributes, and should appear in the example.

Fix doc for IP block quota resource

---

nsxt/data_source_nsxt_vpc.go
nsxt/resource_nsxt_vpc.go
nsxt/utils.go
nsxt/validators.go

This should be only supported for VPC resource and data source.

Validate that default project isn't specified in context block

---

.golangci.yml
nsxt/data_source_nsxt_policy_transport_zone.go

Modifies the conditional expression in `data_source_nsxt_policy_transport_zone.go` to address the QF1001 staticcheck warning.
```diff
- else if objName == "" && !(isDefault && transportType != "") {
+ else if objName == "" && (!isDefault || transportType == "") {
```
The diff of the expressions are logically equivalent according to De Morgan's law, which states that `!(A && B)` is equivalent to `(!A || !B)`. This change maintains identical behavior while expressing the condition in a more direct and easier-to-understand form that aligns with staticcheck.

fix: staticcheck QF1001

---

.golangci.yml
nsxt/provider_test.go

Omit redundant type from variable declaration
Ref: `staticcheck` [QF1011](https://staticcheck.dev/docs/checks#QF1011)

fix: staticcheck QF1011

---

.golangci.yml
nsxt/policy_common.go
nsxt/policy_search.go
nsxt/resource_nsxt_policy_tier1_gateway_interface_test.go
nsxt/utils_test.go

Refactors to use `strings.ReplaceAll` instead of `strings.Replace` with `n == -1`.
Ref: `staticcheck` [QF1004](https://staticcheck.dev/docs/checks#QF1004)

fix: staticcheck QF1004

---

docs/resources/policy_tier0_gateway.md
nsxt/resource_nsxt_policy_bgp_config.go
nsxt/resource_nsxt_policy_tier0_gateway.go
nsxt/resource_nsxt_policy_tier0_gateway_test.go

Since 4.2.1, inter_sr_ibgp is supported for VRF, when parent gateway has multi_vrf_inter_sr_routing flag enabled. This change:
1. Adds `multi_vrf_inter_sr_routing` T0 flag from NSX 4.2.1
2. Adds `enable_rd_per_edge` T0 flag from NSX 4.2.0
3. Allows to configure `inter_sr_ibgp` flag from NSX 4.2.1

Add new Tier0 flags and allow inter_sr for VRF

---

nsxt/resource_nsxt_policy_edge_cluster.go

NSX may not retain the order of the nodes within the cluster when index is not specified by the user.
So using order-less set is better in this case.

Ignore edge transport node order in cluster

---

nsxt/resource_nsxt_policy_lb_udp_monitor_profile_test.go

nsxt_policy_lb_udp_monitor_profile send and receive attributes became mandatory with v9.1.0.

Fix LB UDP profile test failures with v9.1.0

---

nsxt/resource_nsxt_policy_project_test.go
nsxt/resource_nsxt_policy_transit_gateway_attachment_test.go

Tests in v9.1.0 fail due to platform bug. To allow test execution against v9.1.0, fix this until the bug is fixed in NSX. Later we can revert this.

Address test failures with v9.1.0

---

docs/guides/faq.md
docs/guides/federation.md
docs/guides/multitenancy.md
docs/guides/upgrade.md
docs/guides/vmc.md

Cleans up the rendering for the providers guides:
- Update use of NSX-T to NSX.
- Updates titles and headers.
- Updates URLs as needed.
- Clarifys context, as needed.
This will clean up the following navigation and some of the included content.
Current:

docs: cleanup guides rendering

---

.golangci.yml

Removes duplicate golangci-lint exclusion for staticcheck.

chore: remove duplicate golangci-lint exclusion

---

docs/resources/policy_tier0_gateway.md
nsxt/resource_nsxt_policy_tier0_gateway.go
nsxt/resource_nsxt_policy_tier0_gateway_test.go

This attribute will be available from NSX 9.1.0 onwards

Expose tgw transit subnets attribute on Tier0

---

nsxt/metadata/metadata.go
nsxt/resource_nsxt_policy_ipsec_vpn_local_endpoint.go

Comments of the exported element do not start with the name.

chore: comments of exported element

---

docs/resources/policy_edge_transport_node.md

Using nsxt_policy_edge_transport_node data source in this use case is better than using nsxt_policy_edge_node.
While nsxt_policy_edge_node is a legacy DS which retrieves edge position with the cluster, nsxt_policy_edge_transport_node is used to retrieve the edge itself.

Fix policy_edge_transport_node doc

---

api/utl/api_util.go
docs/data-sources/policy_segment.md
docs/data-sources/policy_tier0_gateway.md
docs/data-sources/policy_tier1_gateway.md
nsxt/data_source_nsxt_policy_segment.go
nsxt/data_source_nsxt_policy_tier0_gateway.go
nsxt/data_source_nsxt_policy_tier1_gateway.go
nsxt/policy_common.go
nsxt/policy_search.go
nsxt/policy_utils.go
nsxt/provider.go
nsxt/resource_nsxt_policy_security_policy_rule.go
nsxt/utils.go

This change moves the is_global attribute for the T0 GW data source in the resource context.
To this aim this change:
- adds the context schema to the T0 GW data source
- adds the abiltiy of specifying a from_global boolean setting on the resource context
- changes TF session context generation to set the from_global setting. When this setting is true, project_id and vpc_id will be ignored as resources coming from global manager cannot have a multi-tenancy scope

Tier1/Segment DS: Allow fetching global resources, move is_global into context

---

docs/resources/policy_host_transport_node_collection.md
nsxt/resource_nsxt_policy_host_transport_node_collection.go

Name is misleading, as this attribute is actually a policy path. Replaced this with an attribute with a correct name and marked the old one as deprecated.
Partially fixes: #1716

Deprecate sub_cluster_id in host_transport_node_collection

---

nsxt/resource_nsxt_policy_transit_gateway.go

nsxt_policy_transit_gateway resource crashed when called with empty span list.

Handle crash in policy transit gateway

---

docs/index.md

Correct list of pre-configured retry statuses

---

nsxt/resource_nsxt_policy_gateway_connection_test.go

Tests were skipped and therefore weren't failing.

Fix tests for policy gateway connection.

---

docs/data-sources/policy_gateway_connection.md
docs/data-sources/policy_gateway_locale_service.md

Samples for nsxt_policy_gateway_connection and
nsxt_policy_gateway_connection_locale_service
were using an invalid path for the tier0 gateway.

[DOC] Fix some incorrect resource usage samples

---

nsxt/policy_common.go

When a rule was created with an empty service_entries block, the provider crashed. This change addresses that bug.
Fixes: #1782

Handle empty service_entries block case in nsxt_policy_security_policy

---

nsxt/resource_nsxt_policy_lb_udp_monitor_profile_test.go

nsxt_policy_lb_udp_monitor_profile send and receive attributes became mandatory with v4.2.3

[3.10.0]Fix LB UDP profile test failures with v4.2.3

---

nsxt/resource_nsxt_upgrade_run.go

When the user pauses after each upgrade unit, the upgrade_run resource might exit before the upgrade is reaching a permanent state. This fix should correct this.

[3.10.0]Handle upgrade run test failures

---

nsxt/policy_common.go

When a rule was created with an empty service_entries block, the provider crashed. This change addresses that bug.
Fixes: #1782

[3.10.0]Handle empty service_entries block case in nsxt_policy_security_policy

---

docs/resources/vpc_subnet.md

For isolated subnets, users must specify ip_addresses.

[DOC] VPC subnet: ip_addresses are required when access_mode is isolated

---

docs/resources/policy_bgp_config.md
docs/resources/policy_tier0_gateway.md

Update documentation for Tier0 and BGP config resources as it is incorrectly stating the default value for inter_sr_ibgp is True.

Doc: inter_sr_ibgp does not default to active.

---

nsxt/resource_nsxt_policy_edge_transport_node.go

Some attributes were set incorrectly, which generated a schema set issues.

Fix schema set errors in policy edge resource

---

docs/resources/policy_tier0_gateway_ha_vip_config.md
docs/resources/policy_tier0_gateway_interface.md

The example provided in documentation will cause a realization failure in NSX due to overlapping subnet ranges.
This change fixes the subnets allocated to the gateway interfaces to prevent this issue.

[DOC] Fix invalid example for nsxt_policy_tier0_gateway_ha_vip_config

---

docs/resources/policy_ip_block.md
nsxt/resource_nsxt_policy_ip_block.go
nsxt/resource_nsxt_policy_ip_block_test.go

When the API has a list of complex objects, we use singular naming, e.g
```
range {
start = ...
end = ...
}
```
instead of:
```
ranges {
start = ...
end = ...
}
```
which is confusing - as each instance is represented by a separate block.

Use singular naming for range attribute

---

nsxt/segment_common.go

This is caused by adding an empty "l2_extesion" block to the segment.
Fixes: #1827

Interface conversion error when applying config to VLAN Backed

---

nsxt/resource_nsxt_policy_ipsec_vpn_service.go

For nsxt_policy_ipsec_vpn_service resource, one of the above is required. Use AtLeastOneOf to fail the plan if both are missing.
Fixes: #1833

Force specification of either locale_service_path or gateway_path
