README.md

Correct the license link target

---

nsxt/resource_nsxt_ip_block_subnet_test.go

IP block subnet will be better supported by the NSX on version 2.3

Update ip block subnet version to 2.3

---

nsxt/data_source_nsxt_edge_cluster.go
nsxt/data_source_nsxt_logical_tier0_router.go
nsxt/data_source_nsxt_ns_service.go
nsxt/data_source_nsxt_switching_profile.go
nsxt/data_source_nsxt_transport_zone.go

Data source can be retrieved by ID or name.
In most cases we support name prefix, but still need to prefer a full name match

Improve data source search by full name/prefix

---

nsxt/provider.go
nsxt/resource_nsxt_qos_switching_profile.go
nsxt/resource_nsxt_qos_switching_profile_test.go
vendor/github.com/vmware/go-vmware-nsxt/logical_switching_api.go
vendor/github.com/vmware/go-vmware-nsxt/manager/qos_base_rate_shaper.go
vendor/vendor.json

Add qos switching profile as a resource

---

nsxt/resource_nsxt_firewall_section.go
nsxt/resource_nsxt_firewall_section_test.go
nsxt/utils.go

Fix firewall section rules multiple source/dest support

---

nsxt/provider.go
nsxt/resource_nsxt_dhcp_server_ip_pool.go
nsxt/resource_nsxt_dhcp_server_ip_pool_test.go
nsxt/resource_nsxt_logical_dhcp_server.go
nsxt/utils.go
website/docs/r/dhcp_server_ip_pool.html.markdown
website/docs/r/logical_dhcp_server.html.markdown
website/nsxt.erb

Import is not supported yet - will be addressed in follow-up.

Add IP pool resource for DHCP server

---

nsxt/resource_nsxt_lb_http_forwarding_rule.go
nsxt/resource_nsxt_lb_http_forwarding_rule_test.go

The platform narrowed down accepted status codes

Change lb http rule redirect status code

---

nsxt/resource_nsxt_logical_tier1_router.go

If T1 is not connected to edge cluster, failover mode is not set on
the backend. To avoid non-empty plan, set the mode to default value.

Set router failover mode to default if absent

---

nsxt/resource_nsxt_firewall_section.go

Ignore order of services in FW rules

---

nsxt/resource_nsxt_firewall_section.go
nsxt/resource_nsxt_firewall_section_test.go

In addition, fix default for ip_protocol in FW section.

And and acceptance test for edge FW

---

nsxt/resource_nsxt_firewall_section_test.go

The test is failing due to what seems to be issue in core terraform
https://github.com/hashicorp/terraform/issues/21012
This patch is a workaround to avoid test failure while the issue is
investigated.

Fix FW section test

---

go.mod
nsxt/provider.go
nsxt/provider_test.go
nsxt/resource_nsxt_firewall_section.go
nsxt/resource_nsxt_logical_tier1_router.go
nsxt/utils.go

The default was changed to True in NSXT 2.5
In addition, improve nsx version comparison.

Change router adv default according to nsx version

---

nsxt/resource_nsxt_logical_switch_test.go
website/docs/r/dhcp_relay_profile.html.markdown
website/docs/r/logical_switch.html.markdown

In addition, improve documentation

Add test for logical switch address binding

---

nsxt/resource_nsxt_logical_router_downlink_port.go
nsxt/resource_nsxt_logical_router_link_port_on_tier1.go

With import, required attributes can still be set to null.

Fix import crashes

---

nsxt/resource_nsxt_policy_tier0_gateway.go
nsxt/resource_nsxt_policy_tier1_gateway.go

Unset edge cluster is not returned in platform response.

Fix edge cluster assignment in gateways

---

nsxt/data_source_nsxt_firewall_section.go
nsxt/data_source_nsxt_firewall_section_test.go
nsxt/provider.go
website/docs/d/firewall_section.html.markdown
website/docs/r/firewall_section.html.markdown
website/nsxt.erb

This data source is added to old (non-policy) provider. It allows
to add section above pre-configured firewall section.

Add firewall section data source

---

nsxt/policy_errors.go
nsxt/resource_nsxt_policy_ip_pool_block_subnet.go

Provide more error information and avoid crash when connection error
occurs (such as connection timed out).
In addition, fix linter error.

Fix error handling

---

nsxt/provider.go
nsxt/provider_test.go

Included a line to support proxy from environment so it wont time out when beihnd a proxy

added proxy support

---

nsxt/data_source_nsxt_policy_ip_block.go
nsxt/data_source_nsxt_policy_ip_block_test.go
nsxt/data_source_nsxt_policy_ip_pool.go
nsxt/data_source_nsxt_policy_ip_pool_test.go
nsxt/provider.go
website/docs/d/policy_ip_block.html.markdown
website/docs/d/policy_ip_pool.html.markdown
website/nsxt.erb

Add nsxt_policy_ip_block and nsxt_policy_ip_pool data sources.

Add policy IPAM data sources

---

nsxt/resource_nsxt_policy_nat_rule.go

This is accoring to backend changes.

Add default value in policy_nat_rule

---

nsxt/resource_nsxt_policy_lb_pool.go

The platform provides a default setting for snat, hence the provider
nees to adjust.
In addition, this change avoids relying on converter errors when
checking snat type, and uses base class _Type setting instead.

Mark snat as Computed in policy lb pool

---

nsxt/data_source_nsxt_policy_segment_realization.go
nsxt/resource_nsxt_policy_segment_test.go
nsxt/segment_common.go

This works around an update bug in early platform versions.

Use put instead of patch in segment update

---

nsxt/resource_nsxt_policy_tier0_gateway.go
nsxt/resource_nsxt_policy_tier0_gateway_test.go
nsxt/validators.go

Following validation changes on backend, fix provider validaton and
corresponding tests for vrf attributes

Fix validation in policy vrf router

---

website/docs/d/certificate.html.markdown

Typo in title, this data source is a nsxt_certificate.

Update typo in title

---

nsxt/data_source_nsxt_policy_gateway_qos_profile_test.go
nsxt/data_source_nsxt_policy_ip_block_test.go
nsxt/data_source_nsxt_policy_realization_info_test.go
nsxt/data_source_nsxt_policy_segment_realization_test.go
nsxt/resource_nsxt_policy_tier0_gateway_interface.go
nsxt/resource_nsxt_policy_tier1_gateway.go
nsxt/resource_nsxt_policy_tier1_gateway_interface.go
nsxt/resource_nsxt_policy_tier1_gateway_test.go

In addition, some version-related fixes in resources.

Enforce version checks in acceptance tests

---

website/docs/index.html.markdown

Updated text and main (verified) example

Update document text and main example

---

website/docs/r/policy_bgp_neighbor.html.markdown
website/docs/r/policy_segment.html.markdown
website/docs/r/policy_tier0_gateway.html.markdown
website/docs/r/policy_vlan_segment.html.markdown

Mark transport zone as required segment, fix gateway example.

Fix and clarify policy documentation

---

nsxt/provider.go
website/docs/index.html.markdown
website/docs/r/policy_gateway_policy.html.markdown
website/docs/r/policy_group.html.markdown
website/docs/r/policy_security_policy.html.markdown

VMC environments are not yet officially supported with the provider.
After provider release this commit will be reverted.

Disable VMC temporarily

---

website/nsxt.erb

Restructure link order to suggest policy resources as preferred.

Rename old resources to Manager resources in doc

---

website/docs/r/policy_gateway_policy.html.markdown
website/docs/r/policy_nat_rule.html.markdown
website/docs/r/policy_static_route.html.markdown

Switch to new terraform syntax and mark rule scope as Required for
gateway policy.

Documentation update

---

website/docs/index.html.markdown

Quick note on DHCP compatibility.

Update with note on 3.0.0 compatibility of DHCP

---

nsxt/data_source_nsxt_policy_segment_realization.go
nsxt/segment_common.go

VM port is not released immediately on VM deletion, which results
in error deleting the segment.
With this change, provider will wait for ports to dissapear before
deleting the segment. This can cause a delayed error in case active
VMs are still attached to the segment.

Check for port existance on segment delete

---

nsxt/policy_utils.go
nsxt/resource_nsxt_policy_dhcp_relay.go
nsxt/resource_nsxt_policy_dhcp_server.go
nsxt/resource_nsxt_policy_gateway_policy.go
nsxt/resource_nsxt_policy_group.go
nsxt/resource_nsxt_policy_ip_address_allocation.go
nsxt/resource_nsxt_policy_ip_address_allocation_test.go
nsxt/resource_nsxt_policy_ip_block.go
nsxt/resource_nsxt_policy_ip_pool.go
nsxt/resource_nsxt_policy_lb_pool.go
nsxt/resource_nsxt_policy_lb_service.go
nsxt/resource_nsxt_policy_lb_virtual_server.go
nsxt/resource_nsxt_policy_security_policy.go
nsxt/resource_nsxt_policy_service.go
nsxt/resource_nsxt_policy_tier0_gateway.go
nsxt/resource_nsxt_policy_tier1_gateway.go
nsxt/segment_common.go

Resource existance check function should be aware of whether the
provider is a global manager.

Refactor resource existance detection helper

---

nsxt/policy_utils.go
nsxt/resource_nsxt_policy_tier0_gateway.go

Support for multiple locale services will be added later

Basic support for Tier0 on global manager

---

nsxt/data_source_nsxt_policy_edge_node.go
nsxt/data_source_nsxt_policy_lb_app_profile.go
nsxt/data_source_nsxt_policy_lb_monitor.go
nsxt/data_source_nsxt_policy_lb_persistence_profile.go
nsxt/segment_common.go

This is according to terraform plugin docs.

Change GetOkExists to GetOk for non-bool arguments

---

nsxt/resource_nsxt_policy_gateway_policy.go
nsxt/resource_nsxt_policy_gateway_policy_test.go

GM Gateway Policy Support

---

nsxt/gateway_common.go
nsxt/resource_nsxt_policy_tier0_gateway.go
nsxt/resource_nsxt_policy_tier0_gateway_test.go
website/docs/r/policy_tier0_gateway.html.markdown

This is for local manager only. Global Manager support will follow.

Support route redistribution config for T0

---

nsxt/resource_nsxt_policy_tier0_gateway_interface_test.go
nsxt/resource_nsxt_policy_tier1_gateway_interface_test.go

NSX fails to re-create objects with same ID within short time period.

Do not set nsx_id in gateway tests

---

nsxt/provider.go
nsxt/resource_nsxt_policy_gateway_prefix_list.go
nsxt/resource_nsxt_policy_gateway_prefix_list_test.go
nsxt/resource_nsxt_policy_nat_rule.go
website/docs/r/policy_gateway_prefix_list.html.markdown
website/nsxt.erb

Support policy gateway prefix lists

---

nsxt/resource_nsxt_policy_bgp_config_test.go
nsxt/resource_nsxt_policy_bgp_neighbor.go
nsxt/resource_nsxt_policy_bgp_neighbor_test.go
nsxt/resource_nsxt_policy_tier0_gateway.go
nsxt/validators.go
website/docs/r/policy_bgp_neighbor.html.markdown

Affected resources: bgp neighbor, bgp config, T0 gateway.

Support BGP AS in ASDot format

---

website/docs/r/policy_segment.html.markdown

Smallfix docs/r/policy_segment.html.markdown

---

nsxt/provider.go
nsxt/validators.go

In addition, allow specifying https schema in host.

Improve hostname validation in provider

---

nsxt/gateway_common.go
nsxt/resource_nsxt_policy_security_policy_test.go
nsxt/resource_nsxt_policy_tier0_gateway.go
nsxt/resource_nsxt_policy_tier0_gateway_gm_test.go
nsxt/resource_nsxt_policy_tier0_gateway_interface.go
nsxt/resource_nsxt_policy_tier0_gateway_interface_test.go
nsxt/resource_nsxt_policy_tier1_gateway.go
website/docs/r/policy_tier0_gateway_interface.html.markdown

Enable_pim is not supported with GM

Enable_pim is not supported with GM

---

nsxt/data_source_nsxt_ns_group.go

Getting the NS groups is limited to 50 per page, even if specified otherwise due to an
api limitation. Adding pagination to overcome this limitation.

Use pagination in ns-group data source read

---

nsxt/gateway_common.go
nsxt/resource_nsxt_policy_tier0_gateway.go
nsxt/resource_nsxt_policy_tier1_gateway.go

This will reduce the number of conflicts during update

Update GM locale services only if changed

---

nsxt/provider.go
nsxt/resource_nsxt_policy_predefined_gateway_policy.go
nsxt/resource_nsxt_policy_predefined_security_policy.go
nsxt/resource_nsxt_policy_predefined_security_policy_test.go
nsxt/resource_nsxt_policy_security_policy.go
website/docs/r/policy_predefined_security_policy.html.markdown

This is actually default security policy, named for consistency with
predefined gateway policy (which is not necessarily default).
This resource allows to modify default layer2 or default layer3
security policy.

Expose predefined security policy resource

---

nsxt/data_source_nsxt_policy_security_policy_test.go
nsxt/resource_nsxt_policy_predefined_security_policy_test.go

This change disables corresponding tests.

Latest NSX GM doesn't have default security policy

---

nsxt/data_source_nsxt_policy_security_policy.go

This attribute can serve as both input and output

Set is_default in security policy data source

---

website/docs/d/policy_segment_realization.html.markdown
website/docs/r/policy_predefined_gateway_policy.html.markdown
website/docs/r/policy_predefined_security_policy.html.markdown

In addition, fix segment realization info sample.

Clarify documentation for predefined policies

---

tools/data_source_nsxt_policy_doc_template
tools/data_source_nsxt_policy_template
tools/data_source_nsxt_policy_test_template
tools/resource_nsxt_policy_doc_template
tools/resource_nsxt_policy_template
tools/resource_nsxt_policy_test_template
website/docs/r/policy_tier0_gateway.html.markdown

* To reflect SDK move
* To support GM
* Catch up with documentation changes

Update policygen tool

---

nsxt/policy_common.go
nsxt/provider.go
nsxt/resource_nsxt_policy_dhcp_v4_static_binding_test.go
nsxt/resource_nsxt_policy_fixed_segment.go
nsxt/resource_nsxt_policy_fixed_segment_test.go
nsxt/resource_nsxt_policy_gateway_prefix_list.go
nsxt/resource_nsxt_policy_nat_rule.go
nsxt/resource_nsxt_policy_segment.go
nsxt/resource_nsxt_policy_static_route.go
nsxt/resource_nsxt_policy_vlan_segment.go
nsxt/resource_nsxt_policy_vlan_segment_test.go
nsxt/segment_common.go
website/docs/r/policy_fixed_segment.html.markdown

On VMC, fixed segments are exposed in UI. For consistency, we provide support for fixed segments here as well. Segment profiles are not supported as of today since the sdk lacks this support for now.

Expose fixed policy segment resource

---

.travis.yml

Also remove go vetter since its covered by golangci job

Add website-lint to CI

---

nsxt/provider.go
nsxt/resource_nsxt_policy_dhcp_v6_static_binding.go
nsxt/resource_nsxt_policy_dns_forwarder_zone.go
nsxt/resource_nsxt_policy_dns_forwarder_zone_test.go
nsxt/resource_nsxt_policy_gateway_dns_forwarder.go
nsxt/resource_nsxt_policy_gateway_dns_forwarder_test.go
nsxt/resource_nsxt_policy_gateway_prefix_list_test.go
nsxt/resource_nsxt_policy_nat_rule_test.go
nsxt/segment_common.go
nsxt/utils_test.go
tools/policygen.py
tools/resource_nsxt_policy_template
website/docs/r/policy_dns_forwarder_zone.html.markdown
website/docs/r/policy_gateway_dns_forwarder.html.markdown

Add the following resources:
* nsxt_policy_dns_forwarder_zone
* nsxt_policy_gateway_dns_forwarder
In addition, enhance generator to avoid double policy keyword for
resources that contain Policy prefix in sdk model.

Add dns forwarder resources

---

nsxt/data_source_nsxt_policy_bfd_profile.go
nsxt/data_source_nsxt_policy_bfd_profile_test.go
nsxt/provider.go
tools/data_source_nsxt_policy_test_template
tools/resource_nsxt_policy_template
tools/resource_nsxt_policy_test_template
website/docs/d/policy_bfd_profile.html.markdown

Plus some fixes in generator templates

Add BFD Profile data source

---

CHANGELOG.md
website/docs/guides/faq.html.markdown
website/docs/r/policy_fixed_segment.html.markdown
website/docs/r/policy_segment.html.markdown

In addition, add FAQ to documentation

Update changelog towards 3.1.1

---

nsxt/data_source_nsxt_policy_bfd_profile.go
nsxt/data_source_nsxt_policy_bfd_profile_test.go
nsxt/data_source_nsxt_policy_certificate.go
nsxt/data_source_nsxt_policy_context_profile.go
nsxt/data_source_nsxt_policy_dhcp_server.go
nsxt/data_source_nsxt_policy_edge_cluster.go
nsxt/data_source_nsxt_policy_edge_node.go
nsxt/data_source_nsxt_policy_gateway_policy.go
nsxt/data_source_nsxt_policy_gateway_qos_profile.go
nsxt/data_source_nsxt_policy_group.go
nsxt/data_source_nsxt_policy_ip_discovery_profile.go
nsxt/data_source_nsxt_policy_ipv6_dad_profile.go
nsxt/data_source_nsxt_policy_ipv6_ndra_profile.go
nsxt/data_source_nsxt_policy_mac_discovery_profile.go
nsxt/data_source_nsxt_policy_qos_profile.go
nsxt/data_source_nsxt_policy_security_policy.go
nsxt/data_source_nsxt_policy_segment_security_profile.go
nsxt/data_source_nsxt_policy_service.go
nsxt/data_source_nsxt_policy_site.go
nsxt/data_source_nsxt_policy_spoofguard_profile.go
nsxt/data_source_nsxt_policy_tier0_gateway.go
nsxt/data_source_nsxt_policy_tier1_gateway.go
nsxt/data_source_nsxt_policy_transport_zone.go
nsxt/policy_search.go
nsxt/utils_test.go
website/docs/d/policy_bfd_profile.html.markdown

In preparation for dropping support for NSX < 3.0.0, this change
expands search API data source solution to Local Manager. New data
source will be implemented using search.

Expand search capabilities to Local Manager

---

nsxt/provider.go
nsxt/resource_nsxt_policy_evpn_tenant.go
nsxt/resource_nsxt_policy_evpn_tenant_test.go
website/docs/r/policy_evpn_tenant.html.markdown

Expose EVPN Tenant resource

---

nsxt/data_source_nsxt_policy_vni_pool_test.go
nsxt/gateway_common.go
nsxt/provider.go
nsxt/provider_test.go
nsxt/resource_nsxt_policy_evpn_config_test.go
nsxt/resource_nsxt_policy_evpn_tenant_test.go
nsxt/resource_nsxt_policy_evpn_tunnel_endpoint.go
nsxt/resource_nsxt_policy_evpn_tunnel_endpoint_test.go
nsxt/utils_test.go
website/docs/r/policy_evpn_tunnel_endpoint.html.markdown

In addition, improve test resource name randomization

Expose EVPN tunnel endpoint resource

---

nsxt/resource_nsxt_policy_gateway_route_map.go

Set can be configured regardless of criteria type

Always allow to specify set in route map criteria

---

nsxt/gateway_common.go
nsxt/resource_nsxt_policy_evpn_config_test.go
nsxt/resource_nsxt_policy_evpn_tenant_test.go
nsxt/resource_nsxt_policy_evpn_tunnel_endpoint_test.go
nsxt/resource_nsxt_policy_gateway_redistribution_config.go
nsxt/resource_nsxt_policy_gateway_redistribution_config_test.go
nsxt/resource_nsxt_policy_intrusion_service_policy_test.go
nsxt/resource_nsxt_policy_intrusion_service_profile_test.go
nsxt/resource_nsxt_policy_ospf_area_test.go
nsxt/resource_nsxt_policy_ospf_config_test.go
nsxt/resource_nsxt_policy_security_policy_test.go
nsxt/resource_nsxt_policy_static_route_bfd_peer_test.go
nsxt/resource_nsxt_policy_tier0_gateway_interface_test.go
nsxt/resource_nsxt_policy_vlan_segment_test.go
nsxt/segment_common.go
website/docs/r/policy_evpn_config.html.markdown
website/docs/r/policy_evpn_tenant.html.markdown
website/docs/r/policy_evpn_tunnel_endpoint.html.markdown
website/docs/r/policy_gateway_redistribution_config.html.markdown
website/docs/r/policy_intrusion_service_policy.html.markdown
website/docs/r/policy_intrusion_service_profile.html.markdown
website/docs/r/policy_ospf_area.html.markdown
website/docs/r/policy_ospf_config.html.markdown
website/docs/r/policy_tier0_gateway.html.markdown

Add version clarification in docs

Fix provider to still support NSX 3.0 line

---

nsxt/data_source_nsxt_policy_certificate.go

The data source used incorrect resource name and thus failed to
work on global manager. We switch to search-based data source
implementation.

Fix policy certificate data source

---

website/docs/r/policy_gateway_redistribution_config.html.markdown

Signed-off-by: Madhukar Krishnarao <krishnaraom@vmware.com>

nsxt_policy_site should be a data source

---

nsxt/resource_nsxt_policy_gateway_route_map.go
nsxt/resource_nsxt_policy_gateway_route_map_test.go
nsxt/validators.go

The path should allow multiple areas with space delimiter

Fix AS path validation in route map

---

nsxt/gateway_common.go
nsxt/resource_nsxt_policy_gateway_redistribution_config.go
nsxt/resource_nsxt_policy_gateway_redistribution_config_test.go

Add newly available attributes, and fix potential crash.

Enhance redistribution config resource

---

nsxt/resource_nsxt_policy_intrusion_service_profile.go
nsxt/resource_nsxt_policy_intrusion_service_profile_test.go

This is following platform changes that reorders items in response.

Use schema Set for attributes in ids profiles

---

nsxt/resource_nsxt_policy_service.go

This retry is temporary until SDK-based provider-wide retry is introduced.

Add retry to service deletion

---

CHANGELOG.md
website/docs/d/ns_groups.html.markdown
website/docs/d/ns_services.html.markdown
website/docs/d/policy_lb_service.html.markdown

Prepare for 3.2.5 release

---

nsxt/policy_utils.go
nsxt/provider.go
nsxt/resource_nsxt_policy_gateway_redistribution_config.go
nsxt/resource_nsxt_policy_gateway_redistribution_config_test.go
nsxt/resource_nsxt_policy_group.go
nsxt/resource_nsxt_policy_service.go
vendor/github.com/vmware/vsphere-automation-sdk-go/runtime/protocol/client/middleware/retry/retry.go
vendor/modules.txt
website/docs/index.html.markdown
website/docs/r/policy_lb_virtual_server.html.markdown

This change removes previous resource-based retry support.

Global retry support using SDK feature

---

nsxt/provider.go
nsxt/resource_nsxt_policy_mac_discovery_profile.go
nsxt/resource_nsxt_policy_mac_discovery_profile_test.go
website/docs/r/policy_mac_discovery_profile.html.markdown

Add new ressource (policy) mac_discovery_profiles

Add Ressource Policy MAC Discovery Profiles

---

.github/workflows/golangci-lint.yml

Upgrade linter version

---

README.md
website/docs/guides/faq.html.markdown
website/docs/guides/vmc.html.markdown
website/docs/r/policy_gateway_dns_forwarder.html.markdown

Documentation fixes and improvements

---

nsxt/resource_nsxt_policy_gateway_redistribution_config.go
nsxt/resource_nsxt_policy_tier0_gateway_ha_vip_config.go

Support retry for HA VIP delete

---

CHANGELOG.md
website/docs/d/policy_vms.html.markdown
website/docs/r/policy_mac_discovery_profile.html.markdown

Prepare for 3.2.6 bugfix release

---

nsxt/resource_nsxt_policy_tier0_gateway_ha_vip_config_test.go

In addition, enable test that covers retry scenario

Adjust HA VIP test to latest NSX release

---

nsxt/data_source_nsxt_policy_mac_discovery_profile_test.go
nsxt/provider.go
nsxt/provider_test.go
nsxt/resource_nsxt_policy_group_test.go
nsxt/resource_nsxt_policy_lb_virtual_server_test.go
nsxt/resource_nsxt_policy_tier0_gateway_interface_test.go
nsxt/resource_nsxt_policy_tier1_gateway.go

In addition, optimize acc tests by cashing policy connector

Fix potential sigsegv in policy retry mechanism

---

website/docs/r/policy_tier0_gateway_ha_vip_config.html.markdown

Clarify documention for Gateway HA VIP

---

tools/policygen.py
tools/resource_nsxt_policy_template

Following changes in SDK, update generation scripts.
In addition, improve generation for list attributes.

Update generation script

---

nsxt/provider.go
nsxt/resource_nsxt_policy_ipsec_vpn_dpd_profile.go
nsxt/resource_nsxt_policy_ipsec_vpn_dpd_profile_test.go
nsxt/resource_nsxt_policy_ipsec_vpn_ike_profile.go
nsxt/resource_nsxt_policy_ipsec_vpn_ike_profile_test.go
nsxt/resource_nsxt_policy_ipsec_vpn_tunnel_profile.go
nsxt/resource_nsxt_policy_ipsec_vpn_tunnel_profile_test.go
website/docs/r/policy_ipsec_vpn_dpd_profile.html.markdown
website/docs/r/policy_ipsec_vpn_ike_profile.html.markdown
website/docs/r/policy_ipsec_vpn_tunnel_profile.html.markdown

Support VPN profiles

---

nsxt/policy_common.go

Otherwise rule order may be compromised.

Make sure to path sequence id in FW rules

---

nsxt/resource_nsxt_policy_bgp_neighbor.go
nsxt/resource_nsxt_policy_bgp_neighbor_test.go

Import support for BGP neighbor on GM

---

nsxt/resource_nsxt_policy_ipsec_vpn_session.go
nsxt/resource_nsxt_policy_ipsec_vpn_session_test.go
nsxt/resource_nsxt_policy_l2_vpn_session.go
nsxt/resource_nsxt_policy_l2_vpn_session_test.go
website/docs/r/policy_ipsec_vpn_session.markdown
website/docs/r/policy_l2_vpn_service.html.markdown

In addition, improve test coverage for these resources.

Support import for VPN session resources

---

nsxt/resource_nsxt_policy_ipsec_vpn_service.go
nsxt/resource_nsxt_policy_ipsec_vpn_service_test.go
nsxt/resource_nsxt_policy_l2_vpn_service.go
nsxt/resource_nsxt_policy_l2_vpn_service_test.go
website/docs/r/policy_ipsec_vpn_service.html.markdown
website/docs/r/policy_l2_vpn_service.html.markdown

Signed-off-by: Shizhao Liu lshizhao@vmware.com

Import support for VPN services

---

nsxt/data_source_nsxt_policy_realization_info_test.go
nsxt/data_source_nsxt_policy_service_test.go
nsxt/resource_nsxt_policy_fixed_segment_test.go
nsxt/resource_nsxt_policy_qos_profile_test.go
nsxt/resource_nsxt_policy_segment_test.go
website/docs/r/policy_ipsec_vpn_dpd_profile.html.markdown

Adjust tests to recent NSX versions

---

CHANGELOG.md
nsxt/data_source_nsxt_policy_realization_info_test.go
nsxt/data_source_nsxt_policy_service_test.go
nsxt/resource_nsxt_policy_fixed_segment_test.go
nsxt/resource_nsxt_policy_segment_test.go
website/docs/d/policy_ipsec_vpn_local_endpoint.html.markdown
website/docs/d/policy_ipsec_vpn_service.html.markdown
website/docs/d/policy_l2_vpn_service.html.markdown
website/docs/guides/faq.html.markdown
website/docs/r/policy_ipsec_vpn_dpd_profile.html.markdown
website/docs/r/policy_ipsec_vpn_ike_profile.html.markdown
website/docs/r/policy_ipsec_vpn_local_endpoint.html.markdown
website/docs/r/policy_ipsec_vpn_service.html.markdown
website/docs/r/policy_ipsec_vpn_session.markdown
website/docs/r/policy_ipsec_vpn_tunnel_profile.html.markdown
website/docs/r/policy_l2_vpn_service.html.markdown
website/docs/r/policy_l2_vpn_session.markdown

Prepare for 3.2.9 release

---

go.sum

Clean up dependencies

---

nsxt/resource_nsxt_policy_ipsec_vpn_session.go
website/docs/r/policy_ipsec_vpn_session.markdown
website/docs/r/policy_l2_vpn_session.markdown

Signed-off-by: Shizhao Liu <lshizhao@vmware.com>

Doc fix for vpn session resources

---

nsxt/provider.go
nsxt/resource_nsxt_policy_ip_discovery_profile.go
nsxt/resource_nsxt_policy_ip_discovery_profile_test.go
website/docs/r/policy_ip_discovery_profile.html.markdown

Signed-off-by: Kobi Samoray <ksamoray@vmware.com>
Fixes #414

Add support for IP discovery profile resource

---

.github/workflows/golangci-lint.yml

Fix linter job

---

CHANGELOG.md
README.md

Prepare for 3.3.0 release

---

tools/diffy/diffy.py

Diffy tool will now print out diff in enumeration values between two NSX specs

Support enum delta in diffy tool

---

.golangci.yml
nsxt/resource_nsxt_policy_tier0_gateway.go

In addition, some fixes related to new linter checks

Cleanup golangci-lint config

---

nsxt/resource_nsxt_policy_ip_address_allocation.go

When name, description or tag attributes are modified, ForceNew is not necessary.

Avoid recreation of ip address allocation resource

---

nsxt/data_source_nsxt_policy_project.go
nsxt/data_source_nsxt_policy_project_test.go
nsxt/provider.go
nsxt/utils_test.go
vendor/github.com/vmware/vsphere-automation-sdk-go/services/nsxt/orgs/OrgsPackageTypes.go
vendor/github.com/vmware/vsphere-automation-sdk-go/services/nsxt/orgs/ProjectsClient.go
vendor/github.com/vmware/vsphere-automation-sdk-go/services/nsxt/orgs/ProjectsTypes.go
vendor/github.com/vmware/vsphere-automation-sdk-go/services/nsxt/orgs/SharedWithMeClient.go
vendor/github.com/vmware/vsphere-automation-sdk-go/services/nsxt/orgs/SharedWithMeTypes.go
vendor/modules.txt
website/docs/d/policy_project.html.markdown

Add a data source for multitenancy project object.

Multitenancy project data source

---

website/docs/d/policy_project.html.markdown
website/docs/guides/multitenancy.html.markdown
website/docs/r/policy_project.html.markdown

Add general multitenancy guide

Multitenancy documentation

---

nsxt/provider.go

fix NSX version initialization on VMC

---

nsxt/policy_errors.go
nsxt/resource_nsxt_policy_gateway_dns_forwarder.go
nsxt/resource_nsxt_policy_nat_rule.go
nsxt/resource_nsxt_policy_static_route.go

T0 gateways do not have multitenancy support

Error use of multitenancy with T0 gateways

---

nsxt/resource_nsxt_policy_segment_security_profile.go
nsxt/resource_nsxt_policy_segment_security_profile_test.go
website/docs/r/policy_segment_security_profile.html.markdown

Import  code for multitenancy environment was missing, as well as tests and documentation.

policy_segment_security_profile multitenancy import

---

nsxt/provider.go
nsxt/resource_nsxt_manager_cluster.go
website/docs/r/manager_cluster.html.markdown

Implement NSXT Manager cluster resource.
The resource can be used to join additional nodes into the cluster of the host node in terraform provider config.
Deletion of this resource will detach these nodes from the cluster.

Implement NSXT Manager Cluster resource

---

nsxt/resource_nsxt_edge_cluster.go
nsxt/resource_nsxt_policy_transport_zone.go
nsxt/resource_nsxt_uplink_host_switch_profile.go
website/docs/r/policy_transport_zone.html.markdown
website/docs/r/uplink_host_switch_profile.html.markdown

In addition, remove readonly field from write flow in edge cluster resource.

Add realized_id attribute to policy fabric objects

---

nsxt/resource_nsxt_policy_gateway_dns_forwarder.go

Otherwise diff is detected on read

Change forwarder zone list to Set

---

nsxt/resource_nsxt_transport_node.go
website/docs/d/transport_node_realization.html.markdown
website/docs/r/transport_node.html.markdown

To match the naming convention rename pnics (plural) ->pnic (singular)

Rename pnics to pnic

---

.gitignore

This is a follow-up PR of PR #962.

Ignore vendor folder

---

nsxt/provider.go

With recent VMC rollouts, /node/version API is available, although only accesible with Bearer token auth.
This change switches to use it, rather than determining version with newly exposed APIs. In case version API is not accesible, old workaround is still applied.

Use version API for VMC

---

nsxt/resource_nsxt_edge_cluster.go
website/docs/r/edge_cluster.html.markdown

This PR should wait for PR #957 to be merged.

Failure Domain in Edge Cluster

---

nsxt/resource_nsxt_transport_node.go
website/docs/r/transport_node.html.markdown

Various NSX versions expose different transport node attribute sets.

Support transport node API of various versions

---

nsxt/resource_nsxt_policy_tier0_gateway_interface_test.go
nsxt/resource_nsxt_policy_tier0_gateway_test.go
nsxt/resource_nsxt_policy_tier1_gateway_interface_test.go

Add missing context in T1 GW interface tests

---

website/docs/d/compute_collection.html.markdown
website/docs/r/failure_domain.html.markdown

Address a couple of glitches in the documentation.

Fixes to documentation

---

nsxt/resource_nsxt_compute_manager.go

Revision is needed to perform updates

Support revision in compute manager resource

---

nsxt/resource_nsxt_policy_host_transport_node.go
website/docs/r/policy_host_transport_node.html.markdown

1. Change thumbprint from optional to required.
2. Fix indentation issue

Fix Host Transport Node doc issue

---

nsxt/data_source_nsxt_policy_gateway_dns_forwarder.go
nsxt/provider.go
nsxt/resource_nsxt_policy_gateway_dns_forwarder_test.go
website/docs/d/policy_context_profile.html.markdown
website/docs/d/policy_gateway_dns_forwarder.html.markdown

Adds a data source for Gateway DNS Forwarder.
Fixes #821

Datasource Gateway DNS Forwarder

---

nsxt/resource_nsxt_cluster_virtual_ip.go

Fix some issue with cluster virtual IP resource including:
1. Resource is presented in .tfstate file even if creation failed because ID was set before the client sets virtual IP
2. Error message does not show details and error code of invalid_request failure, use handleCreate/update function in the resource to get these details.

Fix issue with ClusterVirtualIP resource

---

nsxt/policy_errors.go
nsxt/resource_nsxt_cluster_virtual_ip.go
website/docs/r/cluster_virtual_ip.html.markdown

In addition, improve error reporting

Add NSX version check to cluster IP resource

---

nsxt/resource_nsxt_policy_host_transport_node_collection.go

Revision was not set for nsxt_policy_host_transport_node_profile resource.

host_transport_node_profile update bug

---

nsxt/data_source_nsxt_policy_edge_node.go

member index should be set also when not matching member_index attribute.

Set member index when matching display name

---

nsxt/resource_nsxt_edge_transport_node.go

standard_host_switch attribute was not being populated during import/read.

Fix edge_transport_node import issue

---

website/docs/r/policy_user_management_role_binding.html.markdown

This change highlights dependencies of this resource in documentation.

Update documentation for nsxt_policy_user_management_role_binding

---

nsxt/data_source_nsxt_policy_vtep_ha_host_switch_profile.go
nsxt/provider.go
nsxt/resource_nsxt_policy_uplink_host_switch_profile_test.go
nsxt/resource_nsxt_policy_vtep_ha_host_switch_profile.go
nsxt/resource_nsxt_policy_vtep_ha_host_switch_profile_test.go
website/docs/d/policy_vtep_ha_host_switch_profile.html.markdown
website/docs/r/policy_vtep_ha_host_switch_profile.html.markdown

Implement VTEP HA resource and data source

---

website/docs/r/policy_vtep_ha_host_switch_profile.html.markdown

Fix some issue in VTEP host switch profile doc

Documentation fix

---

nsxt/resource_nsxt_edge_transport_node.go

When destroying a topology which has an edge nodes that were provisioned on a compute manager, there's a case where the compute manager is deleted before the edge VM is destroyed - that causes a failure.
This change waits for the deletion is complete, to satisfy the compute manager dependency.

Stall delete operation until deletion is complete

---

nsxt/resource_nsxt_edge_transport_node.go

Static IP assignment did not work due to a bug.
Fixes: #1153

Fix static_ip handling for ip_assignment

---

nsxt/utils.go

Report detailed error message when NSX version is retrieved

Improve error messaging on connection test

---

nsxt/data_source_nsxt_compute_manager_realization.go
nsxt/data_source_nsxt_policy_host_transport_node_collection_realization.go
nsxt/data_source_nsxt_transport_node_realization.go

This changes the behavior of fabric data sources to fail in case of realization error.

Refactor fabric realization data sources

---

website/docs/r/lb_http_response_rewrite_rule.html.markdown

This change remove some extra brackets in the "Importing" section

[DOC] Remove garbage text in lb_http_response_rewrite_rule.html.markdown

---

nsxt/data_source_nsxt_manager_info.go
nsxt/data_source_nsxt_manager_info_test.go
nsxt/provider.go
website/docs/d/manager_info.html.markdown

A container for various information about the NSX manager.
For now, retrieves the software version of the manager.

Manager info data source

---

nsxt/validator_test.go
nsxt/validators.go

The new validator will serve auto-generated resources based on formats specified in NSX spec

Add validators and improve validator testing

---

nsxt/metadata/metadata.go
nsxt/metadata/metadata_poly_test.go
nsxt/metadata/metadata_test.go

Instead of passing a false/zero value, add some tests for OmitIfEmpty case

Handle OmitIfEmpty for bool and int types

---

nsxt/provider.go
nsxt/resource_nsxt_vpc_subnet.go
nsxt/resource_nsxt_vpc_subnet_test.go
website/docs/r/vpc_subnet.html.markdown

PR contains two commits - the first has the autogenerated files and the second, all the manual edits required to make it work.
As the generator is still being debugged, I'd rather keep it so - so I can regenerate whenever something is fixed in the generator (at least of as long as this PR isn't merged).

VPC subnet resource implmentation

---

nsxt/resource_nsxt_upgrade_prepare.go

Validate that supplied URLs for upgrade preparation is:
* Not empty, for upgarde bundle
* While uploading, NSX sometimes mishandles the upload and doesn't return proper error, which crashes the provider.

Upgrade URL validations

---

nsxt/resource_nsxt_vpc_subnet.go
nsxt/resource_nsxt_vpc_subnet_test.go
website/docs/r/vpc_subnet.html.markdown

Regenerated with args:
VpcSubnet --client-name Subnet --vpc-only --no-api-wrapper
and reapplied manual changes over patch.

Revise VPC subnet resource with latest generator

---

nsxt/resource_nsxt_upgrade_run.go

Some host upgrade groups, e.g the one for non-clustered ESXi hosts change their ID attribute during reset operation. As this causes the upgrade to fail when they're referenced by the run resource, cache the upgrade group list before calling Reset() and lookup the new ID of the group which replaces the old one.

Handle upgrade unit groups which are lost in reset

---

website/docs/r/policy_host_transport_node_profile.html.markdown
website/docs/r/vpc_gateway_policy.html.markdown
website/docs/r/vpc_group.html.markdown

Fix vpc_group, vpc_gateway_policy, nsxt_policy_host_transport_node_profile documents

Documentation fixes

---

nsxt/resource_nsxt_upgrade_run.go

Display proper error when upgrade run fails while waiting for status.

Upgrade run error reporting

---

nsxt/data_source_nsxt_vpc_group.go
nsxt/provider.go
nsxt/resource_nsxt_vpc_group_test.go
website/docs/d/vpc_group.html.markdown

Test for this data source is covered together with VPC group resource test.

Add VPC group data source

---

nsxt/resource_nsxt_vpc_service_profile.go
nsxt/validators.go

In nsxt_vpc_service_profile resource. This could be handy elsewhere.

Validate that NTP server is host or IP

---

website/docs/r/policy_project.html.markdown

Add description for:
- activate_default_dfw_rules
- external_ipv4_blocks
- tgw_external_connection

Add new project properties to documentation

---

nsxt/resource_nsxt_upgrade_run.go

Upgrade run does not resume when all the groups of previous component have completed successfully

Fix upgrade run with pause malfunctions

---

nsxt/provider.go
nsxt/resource_nsxt_policy_transit_gateway.go
nsxt/resource_nsxt_policy_transit_gateway_attachment_test.go
nsxt/resource_nsxt_policy_transit_gateway_test.go
nsxt/resource_nsxt_vpc_connectivity_profile_test.go
nsxt/resource_nsxt_vpc_test.go
website/docs/r/policy_transit_gateway.html.markdown
website/docs/r/vpc_connectivity_profile.html.markdown

Rename nsxt_transit_gateway to nsxt_policy_transit_gateway

---

website/docs/r/policy_distributed_vlan_connection.html.markdown
website/docs/r/vpc_service_profile.html.markdown

VPC Service Profile
- Amend available mode values for dhcp_config to reflect recent enum values
- Add advanced_config attributes in dhcp_config settings
Distributed VLAN connection
- Fix incorrect IP addresses used in sample

Documentation updates for VPC2.0 resources

---

nsxt/resource_nsxt_vpc_subnet.go

This PR follows the same logic we have on segment resource in order to make sure all auto-created VPC subnet ports were deleted before attempting subnet deletion

Validate no port on VPC subnet before deletion

---

website/docs/r/policy_transit_gateway_attachment.html.markdown

- Include parent_path as it's mandatory
- Ensure connection_path references a GW Connection object

[Documentation] Amend sample for TGW attachment resource

---

nsxt/provider.go
nsxt/resource_nsxt_policy_security_policy_rule.go
nsxt/resource_nsxt_policy_security_policy_rule_test.go

Due to a incorrect code, this attributed was defined as read-only

Allow configuration of nsx_id in policy rule

---

nsxt/data_source_nsxt_policy_transit_gateway_nat.go
nsxt/provider.go
nsxt/resource_nsxt_policy_transit_gateway_nat_rule.go
nsxt/resource_nsxt_policy_transit_gateway_nat_rule_test.go
website/docs/d/policy_transit_gateway_nat.html.markdown
website/docs/r/policy_transit_gateway_nat_rule.html.markdown

This change adds NAT data source and NAT rule resource. NAT resource reuses the schema from VPC nat resource.

TGW NAT support

---

.github/workflows/golangci-lint.yml
.github/workflows/golangci-ut.yml
.github/workflows/release.yml
.github/workflows/website-lint.yml

Due to deprecation of these which are used.

Update GitHub actions to latest versions

---

website/docs/r/project_ip_address_allocation.html.markdown

Use correct resource name for the above in documentation

Fix documention for nsxt_policy_project_ip_address_allocation

---

website/docs/r/policy_transit_gateway_nat_rule.html.markdown

Correct resource name to correct value.

Fix doc for TGW NAT rule

---

README.md

Also amend copyright statement and fix a typo.

README: Add NSX 4.2 to supported version

---

LICENSE

- Updates the `LICENSE` to the standard [Mozilla Public License Version 2.0](https://www.mozilla.org/en-US/MPL/2.0/) format.
- Updates the filename to match our standard of `LICENSE`.

chore: update `LICENSE`

---

NOTICE

- Updates the `NOTICE` to reflect Broadcom.
- Updates the filename to match our standard of `NOTICE`.

chore: update `NOTICE`

---

nsxt/resource_nsxt_policy_project.go

nsxt_policy_project has a default_security_profile attribute but it was not handled correctly in read operation.

Handle default_security_profile attribute in project read func

---

.github/workflows/website-lint.yml

- Correct formatting.
- [Pin GitHub Actions to release commit SHA](https://docs.github.com/en/actions/security-for-github-actions/security-guides/security-hardening-for-github-actions#using-third-party-actions).

chore(gh): update website lint

---

nsxt/data_source_nsxt_policy_bridge_profile_test.go
nsxt/resource_nsxt_policy_project_test.go
nsxt/resource_nsxt_vpc_subnet_test.go

Address test failures for v9.0 test executions

Fix test failures for v9.0

---

nsxt/resource_nsxt_upgrade_run.go

In some cases a component is flagged as upgraded successfully while the resource attempts to upgrade it anyway.
This can be avoided by validating the status before starting to busy-wait for upgrade completion.

In upgrade_run, verify that a component is not already upgraded successfully

---

nsxt/resource_nsxt_edge_transport_node.go
website/docs/r/edge_transport_node.html.markdown
website/docs/r/policy_host_transport_node.html.markdown
website/docs/r/policy_host_transport_node_profile.html.markdown

This reverts commit 0cde51e5520002d49aff0a84e1293df11e449222.

Revert "Replace host switch profiles attr with typed ones"

---

nsxt/resource_nsxt_edge_transport_node.go

In this case, IPv6 assignment type needs to be set in request, even though only STATIC type is actually supported.

Support IPv6 assignment in edge management subnet

---

nsxt/resource_nsxt_policy_lb_virtual_server.go

Build requires make fmt to pass, fix some issue with resource_nsxt_policy_lb_virtual_server.go

Fix build failures

---

nsxt/resource_nsxt_policy_tier1_gateway.go

The added validation ensures ha mode 'NONE' can not be configured if edge cluster is specified.

Improve validation for T1 Gateway

---

nsxt/resource_nsxt_policy_lb_pool.go

The preivous validation was located outside the relevant block

Refix the snat automap validation

---

go.mod
go.sum
nsxt/data_source_nsxt_policy_group_test.go

The runtime update addresses the issue of data source search based on display name that contains the "&" character.

Update SDK to fix special char issue

---

.github/workflows/golangci-lint.yml

Use of older lint version fails PR #1570

Update golangci-lint version

---

GNUmakefile

This is useful for debugging the provider using dlv

Add a debug build target to makefile

---

nsxt/resource_nsxt_policy_edge_transport_node.go
website/docs/r/policy_edge_transport_node.html.markdown

Support import-in-create use case for OVA-created edge appliances

Add OVA-edge support to policy edge resource

---

nsxt/data_source_nsxt_policy_tags.go
nsxt/data_source_nsxt_policy_tags_test.go
nsxt/provider.go
website/docs/d/policy_tags.html.markdown

Adding a data source for retrieving the tags based on a scope

Adding a data source for retrieving the tags based on a scope

---

nsxt/policy_utils.go
nsxt/resource_nsxt_vpc_test.go

The provider will allow special characters other than those reserved for URI

Ease validation on project and vpc ids

---

nsxt/data_source_nsxt_policy_bridge_profile_test.go

MP API the test was using is no longer available

Fix bridge profile test for recent NSX version

---

website/docs/d/transport_node_realization.html.markdown
website/docs/r/policy_edge_transport_node.html.markdown

Documentation for the resource above had the wrong IP assignment type witin the example.

Fix nsxt_policy_edge_transport_node doc

---

nsxt/provider.go

With big configurations, excessive log load it hard to navigate. This PR allows to filter printed logs by a string in URI

Allow filtering detailed HTTP logs

---

nsxt/resource_nsxt_policy_edge_cluster.go

This case causes a provider crash, and should be checked

Handle allocation_rules = nil case in policy_edge_cluster

---

docs/data-sources/policy_edge_high_availability_profile.md
nsxt/data_source_nsxt_policy_edge_high_availability_profile.go
nsxt/data_source_nsxt_policy_edge_high_availability_profile_test.go
nsxt/provider.go

Add Edge high availability profile data source

---

go.mod
go.sum
nsxt/resource_nsxt_policy_edge_cluster.go
nsxt/resource_nsxt_policy_group.go

Use the dev branch of the SDK to obtain the latest API changes.

Use dev branch of SDK for 9.1 development

---

.golangci.yml
nsxt/gateway_common.go
nsxt/provider.go

Merges conditional assignment into variable declaration.
Ref: `staticcheck` [QF1007](https://staticcheck.dev/docs/checks#QF1007)

fix: staticcheck QF1007

---

.golangci.yml
nsxt/gateway_common.go
nsxt/metadata/metadata.go
nsxt/metadata/metadata_poly_test.go
nsxt/metadata/metadata_test.go
nsxt/resource_nsxt_edge_transport_node.go
nsxt/resource_nsxt_nat_rule.go
nsxt/resource_nsxt_policy_edge_transport_node.go
nsxt/resource_nsxt_policy_gateway_flood_protection_profile_binding.go
nsxt/resource_nsxt_policy_group.go
nsxt/resource_nsxt_policy_intrusion_service_profile.go
nsxt/resource_nsxt_policy_lb_pool.go
nsxt/resource_nsxt_policy_lb_virtual_server.go
nsxt/resource_nsxt_policy_ldap_identity_source.go
nsxt/resource_nsxt_policy_service.go
nsxt/resource_nsxt_upgrade_prepare.go

Refactors to use a tagged switch instead of an `if/else-if` chain.
Ref: `staticcheck` [QF1003](https://staticcheck.dev/docs/checks#QF1003)

fix: staticcheck QF1003

---

nsxt/data_source_nsxt_policy_security_policy.go
nsxt/data_source_nsxt_policy_transit_gateway.go
nsxt/data_source_nsxt_project_ip_address_allocation.go
nsxt/data_source_nsxt_vpc_connectivity_profile.go
nsxt/data_source_nsxt_vpc_group.go
nsxt/data_source_nsxt_vpc_ip_address_allocation.go
nsxt/data_source_nsxt_vpc_nat.go
nsxt/data_source_nsxt_vpc_service_profile.go
nsxt/data_source_nsxt_vpc_subnet.go
nsxt/policy_common.go
nsxt/resource_nsxt_policy_group.go
nsxt/resource_nsxt_policy_project_ip_address_allocation.go
nsxt/resource_nsxt_policy_transit_gateway.go
nsxt/resource_nsxt_vpc_connectivity_profile.go
nsxt/resource_nsxt_vpc_ip_address_allocation.go
nsxt/resource_nsxt_vpc_service_profile.go
nsxt/resource_nsxt_vpc_static_routes.go
nsxt/resource_nsxt_vpc_subnet.go

Multiple objects should be allowed to have default project assigned via context.

Allow usage of default project for various objects

---

nsxt/data_source_nsxt_policy_project_test.go
nsxt/resource_nsxt_policy_dns_forwarder_zone.go
nsxt/util/utils.go

Removes redundant import aliases.

refactor: redundant import alias

---

nsxt/resource_nsxt_firewall_section_test.go
nsxt/resource_nsxt_policy_ip_address_allocation.go

refactor: redundant type conversion

---

nsxt/resource_nsxt_dhcp_server_ip_pool_test.go
nsxt/resource_nsxt_dhcp_server_profile_test.go
nsxt/resource_nsxt_firewall_section_test.go
nsxt/resource_nsxt_ip_pool_allocation_ip_address_test.go
nsxt/resource_nsxt_lb_http_virtual_server_test.go
nsxt/resource_nsxt_lb_l7_monitor_test.go
nsxt/resource_nsxt_lb_service_test.go
nsxt/resource_nsxt_logical_dhcp_port_test.go
nsxt/resource_nsxt_logical_dhcp_server_test.go
nsxt/resource_nsxt_logical_port_test.go
nsxt/resource_nsxt_logical_router_centralized_service_port_test.go
nsxt/resource_nsxt_logical_router_downlink_port_test.go
nsxt/resource_nsxt_logical_router_link_port_on_tier0_test.go
nsxt/resource_nsxt_logical_router_link_port_on_tier1_test.go
nsxt/resource_nsxt_logical_switch_test.go
nsxt/resource_nsxt_logical_tier0_router_test.go
nsxt/resource_nsxt_logical_tier1_router_test.go
nsxt/resource_nsxt_nat_rule_test.go
nsxt/resource_nsxt_ns_group_test.go
nsxt/resource_nsxt_static_route_test.go
nsxt/resource_nsxt_vlan_logical_switch_test.go

Removes legacy interpolation for data sources in acceptance tests.

refactor: remove legacy interpolation

---

nsxt/resource_nsxt_cluster_virtual_ip.go

Remove global variables that are defined and never used.

chore: unused variables

---

docs/guides/upgrade.md
docs/resources/upgrade_run.md

NSX versions have specific limitations in certain cases, those are enlisted in the product upgrade doc.

Add a reference to the upgrade guide in upgrade docs

---

docs/data-sources/policy_edge_transport_node_realization.md
docs/resources/policy_edge_transport_node.md
nsxt/data_source_nsxt_policy_edge_transport_node_realization.go
nsxt/provider.go

Also update nsxt_policy_edge_transport_node documentatation to use new DS.

Implement policy edge transport node realization datasource

---

docs/resources/policy_host_transport_node_collection.md
nsxt/resource_nsxt_policy_host_transport_node_collection.go

This is a new addition for NSX v9.1.0

Add network_span_paths attr to HostTransportNodeCollection

---

README.md

Also fix typo: 3.1.x was duplicate, 3.0.x was missing

Add NSX 9.0 support in readme

---

README.md

Also fix typo: 3.1.x was duplicate, 3.0.x was missing

README: Update supported NSX Versions

---

docs/resources/policy_transit_gateway.md
nsxt/resource_nsxt_policy_transit_gateway.go
nsxt/resource_nsxt_policy_transit_gateway_test.go

Add the span attributes to the transit gateway resource.

Transit gateway span attributes

---

docs/resources/policy_gateway_connection.md
nsxt/resource_nsxt_policy_gateway_connection.go
nsxt/resource_nsxt_policy_gateway_connection_test.go

Those features will be offered with NSX 9.1.0

Support more features for gateway connection

---

docs/resources/vpc_subnet.md

* Fix invalid example
* Add an additional example for private subnet
* Clarify ip_v4_subnet_size and ip_addresses are mutually exclusive

DOC: Fix and enhance doc for vpc_subnet resource

---

docs/data-sources/policy_edge_cluster.md
docs/data-sources/policy_network_span.md
nsxt/data_source_nsxt_policy_network_span.go
nsxt/data_source_nsxt_policy_network_span_test.go
nsxt/provider.go

To complete network span functionality.
Also some minor fix to policy edge cluster datasource.

Implement policy network span datasource

---

docs/resources/policy_transit_gateway_nat_rule.md
nsxt/resource_nsxt_policy_transit_gateway_attachment_test.go
nsxt/resource_nsxt_policy_transit_gateway_nat_rule.go
nsxt/resource_nsxt_policy_transit_gateway_nat_rule_test.go
nsxt/resource_nsxt_vpc_nat_rule.go

This is an optional attribute which is missing in TGW NAT rule schema.

Add scope attribute to transit gateway NAT rule resource

---

nsxt/resource_nsxt_upgrade_run.go

When the user pauses after each upgrade unit, the upgrade_run resource might exit before the upgrade is reaching a permanent state. This fix should correct this.

Handle upgrade run test failures

---

docs/resources/policy_edge_transport_node_rtep.md
nsxt/resource_nsxt_policy_edge_transport_node_rtep.go

RTEP creation fails when Policy Edge is not realized successfully.

Make sure that Edge is realized, before allowing creation of the RTEP

---

nsxt/policy_errors.go
nsxt/resource_nsxt_upgrade_run.go

Status check may result with BAD_REQUEST + 30023 error code. This case should be ignored.

Handle 30023 error correctly in upgrade-run

---

docs/data-sources/policy_share.md
nsxt/data_source_nsxt_policy_share.go
nsxt/provider.go
nsxt/resource_nsxt_policy_share_test.go
nsxt/resource_nsxt_policy_shared_resource_test.go

To complete sharing functionality, add a datasource for policy_share.

Add a policy_share datasource

---

docs/resources/policy_edge_transport_node_rtep.md
nsxt/resource_nsxt_policy_edge_transport_node_rtep.go

This reverts commit 4b3f44e58c110095ef871c92b813de146b2413d8.

Revert "Make sure that Edge is realized, before allowing creation of the RTEP. (#1775)"

---

docs/resources/policy_ipsec_vpn_service.md
docs/resources/policy_ipsec_vpn_session.md

Fix documentation issues for the following resources: nsxt_policy_ipsec_vpn_service
nsxt_policy_ipsec_vpn_session
Fixes: #1834, #1835

Fix documentation issues.
